/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class AIOpter {
  public static boolean SmoothCal(OptDataVector indatas, OptDataVector outData, double chordLength) {
    return AIOpterJNI.SmoothCal(OptDataVector.getCPtr(indatas), indatas, OptDataVector.getCPtr(outData), outData, chordLength);
  }

  public static BoolIntPair SplitDatas(OptDataVector indatas, double stGTLc, double edGTLc, double dSlopeRate, OptDataVector outData) {
    return new BoolIntPair(AIOpterJNI.SplitDatas(OptDataVector.getCPtr(indatas), indatas, stGTLc, edGTLc, dSlopeRate, OptDataVector.getCPtr(outData), outData), true);
  }

}
