/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class AIOpterJNI {
  static {
    // 先加载系统 x86_64 的 adolc，避免误用工作区中的 aarch64 版本。
 
    // 加载项目 JNI 主库。
    System.load("/home/albalest/AlignmentCoreForJavaOnLinux/lib/libCOptimizer.so");
  }


  public final static native long new_OptData__SWIG_0();
  public final static native long new_OptData__SWIG_1(double jarg1, double jarg2, double jarg3, double jarg4);
  public final static native long new_OptData__SWIG_2(double jarg1, double jarg2, double jarg3);
  public final static native long new_OptData__SWIG_3(double jarg1, double jarg2);
  public final static native void OptData_x_set(long jarg1, OptData jarg1_, double jarg2);
  public final static native double OptData_x_get(long jarg1, OptData jarg1_);
  public final static native void OptData_y_set(long jarg1, OptData jarg1_, double jarg2);
  public final static native double OptData_y_get(long jarg1, OptData jarg1_);
  public final static native void OptData_y_up_set(long jarg1, OptData jarg1_, double jarg2);
  public final static native double OptData_y_up_get(long jarg1, OptData jarg1_);
  public final static native void OptData_y_down_set(long jarg1, OptData jarg1_, double jarg2);
  public final static native double OptData_y_down_get(long jarg1, OptData jarg1_);
  public final static native void delete_OptData(long jarg1);
  public final static native long new_CommonConstrain();
  public final static native void CommonConstrain_m_ShortWaveLimit_set(long jarg1, CommonConstrain jarg1_, double jarg2);
  public final static native double CommonConstrain_m_ShortWaveLimit_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_ShortWaveLength_set(long jarg1, CommonConstrain jarg1_, double jarg2);
  public final static native double CommonConstrain_m_ShortWaveLength_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_ShortWaveIndexMargin_set(long jarg1, CommonConstrain jarg1_, int jarg2);
  public final static native int CommonConstrain_m_ShortWaveIndexMargin_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_LongWaveLimit_set(long jarg1, CommonConstrain jarg1_, double jarg2);
  public final static native double CommonConstrain_m_LongWaveLimit_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_LongWaveLength_set(long jarg1, CommonConstrain jarg1_, double jarg2);
  public final static native double CommonConstrain_m_LongWaveLength_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_LongWaveIndexMargin_set(long jarg1, CommonConstrain jarg1_, int jarg2);
  public final static native int CommonConstrain_m_LongWaveIndexMargin_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_SuperSlope_set(long jarg1, CommonConstrain jarg1_, double jarg2);
  public final static native double CommonConstrain_m_SuperSlope_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_factor_set(long jarg1, CommonConstrain jarg1_, double jarg2);
  public final static native double CommonConstrain_m_factor_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_isFixed_set(long jarg1, CommonConstrain jarg1_, boolean jarg2);
  public final static native boolean CommonConstrain_isFixed_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_isPlane_set(long jarg1, CommonConstrain jarg1_, boolean jarg2);
  public final static native boolean CommonConstrain_isPlane_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_isByVert_set(long jarg1, CommonConstrain jarg1_, boolean jarg2);
  public final static native boolean CommonConstrain_isByVert_get(long jarg1, CommonConstrain jarg1_);
  public final static native void CommonConstrain_m_CtrlCurve_set(long jarg1, CommonConstrain jarg1_, double jarg2);
  public final static native double CommonConstrain_m_CtrlCurve_get(long jarg1, CommonConstrain jarg1_);
  public final static native void delete_CommonConstrain(long jarg1);
  public final static native long new_Splineline__SWIG_0();
  public final static native long new_Splineline__SWIG_1(long jarg1, OptDataVector jarg1_);
  public final static native void delete_Splineline(long jarg1);
  public final static native boolean Splineline_ReInitData(long jarg1, Splineline jarg1_, long jarg2, OptDataVector jarg2_, long jarg3, OptDataVector jarg3_, long jarg4, OptDataVector jarg4_);
  public final static native boolean Splineline_Init(long jarg1, Splineline jarg1_, double jarg2);
  public final static native long Splineline_GetData(long jarg1, Splineline jarg1_);
  public final static native void Splineline_SetDatas(long jarg1, Splineline jarg1_, long jarg2, OptDataVector jarg2_);
  public final static native long Splineline_GetAllPickPts(long jarg1, Splineline jarg1_);
  public final static native int Splineline_GetPickPtsCount(long jarg1, Splineline jarg1_);
  public final static native long Splineline_PickPoint__SWIG_0(long jarg1, Splineline jarg1_, long jarg2, OptData jarg2_, double jarg3);
  public final static native long Splineline_PickPoint__SWIG_1(long jarg1, Splineline jarg1_, long jarg2, OptData jarg2_);
  public final static native boolean Splineline_RemovePickPoint(long jarg1, Splineline jarg1_, int jarg2);
  public final static native boolean Splineline_InsertPickPoint(long jarg1, Splineline jarg1_, long jarg2, OptData jarg2_);
  public final static native boolean Splineline_MovePickPoint(long jarg1, Splineline jarg1_, int jarg2, long jarg3, OptData jarg3_);
  public final static native long new_OpterProcesser(long jarg1, OptDataVector jarg1_, long jarg2, CommonConstrain jarg2_);
  public final static native void delete_OpterProcesser(long jarg1);
  public final static native long OpterProcesser_GetOptResult(long jarg1, OpterProcesser jarg1_);
  public final static native boolean OpterProcesser_StartOpt(long jarg1, OpterProcesser jarg1_);
  public final static native boolean OpterProcesser_StartOptPro(long jarg1, OpterProcesser jarg1_);
  public final static native boolean OpterProcesser_SmoothCalOpt(long jarg1, OpterProcesser jarg1_, long jarg2, OptDataVector jarg2_, double jarg3);
  public final static native boolean OpterProcesser_SmoothCalOrigin(long jarg1, OpterProcesser jarg1_, long jarg2, OptDataVector jarg2_, double jarg3);
  public final static native void OpterProcesser_m_constraints_set(long jarg1, OpterProcesser jarg1_, long jarg2, CommonConstrain jarg2_);
  public final static native long OpterProcesser_m_constraints_get(long jarg1, OpterProcesser jarg1_);
  public final static native boolean SmoothCal(long jarg1, OptDataVector jarg1_, long jarg2, OptDataVector jarg2_, double jarg3);
  public final static native long SplitDatas(long jarg1, OptDataVector jarg1_, double jarg2, double jarg3, double jarg4, long jarg5, OptDataVector jarg5_);
  public final static native long new_OptDataVector__SWIG_0();
  public final static native long new_OptDataVector__SWIG_1(long jarg1, OptDataVector jarg1_);
  public final static native boolean OptDataVector_isEmpty(long jarg1, OptDataVector jarg1_);
  public final static native void OptDataVector_clear(long jarg1, OptDataVector jarg1_);
  public final static native long new_OptDataVector__SWIG_2(int jarg1, long jarg2, OptData jarg2_);
  public final static native int OptDataVector_doCapacity(long jarg1, OptDataVector jarg1_);
  public final static native void OptDataVector_doReserve(long jarg1, OptDataVector jarg1_, int jarg2);
  public final static native int OptDataVector_doSize(long jarg1, OptDataVector jarg1_);
  public final static native void OptDataVector_doAdd__SWIG_0(long jarg1, OptDataVector jarg1_, long jarg2, OptData jarg2_);
  public final static native void OptDataVector_doAdd__SWIG_1(long jarg1, OptDataVector jarg1_, int jarg2, long jarg3, OptData jarg3_);
  public final static native long OptDataVector_doRemove(long jarg1, OptDataVector jarg1_, int jarg2);
  public final static native long OptDataVector_doGet(long jarg1, OptDataVector jarg1_, int jarg2);
  public final static native long OptDataVector_doSet(long jarg1, OptDataVector jarg1_, int jarg2, long jarg3, OptData jarg3_);
  public final static native void OptDataVector_doRemoveRange(long jarg1, OptDataVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_OptDataVector(long jarg1);
  public final static native long new_BoolIntPair__SWIG_0();
  public final static native long new_BoolIntPair__SWIG_1(boolean jarg1, int jarg2);
  public final static native long new_BoolIntPair__SWIG_2(long jarg1, BoolIntPair jarg1_);
  public final static native void BoolIntPair_first_set(long jarg1, BoolIntPair jarg1_, boolean jarg2);
  public final static native boolean BoolIntPair_first_get(long jarg1, BoolIntPair jarg1_);
  public final static native void BoolIntPair_second_set(long jarg1, BoolIntPair jarg1_, int jarg2);
  public final static native int BoolIntPair_second_get(long jarg1, BoolIntPair jarg1_);
  public final static native void delete_BoolIntPair(long jarg1);
}
