/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class BoolIntPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BoolIntPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoolIntPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(BoolIntPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIOpterJNI.delete_BoolIntPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoolIntPair() {
    this(AIOpterJNI.new_BoolIntPair__SWIG_0(), true);
  }

  public BoolIntPair(boolean first, int second) {
    this(AIOpterJNI.new_BoolIntPair__SWIG_1(first, second), true);
  }

  public BoolIntPair(BoolIntPair other) {
    this(AIOpterJNI.new_BoolIntPair__SWIG_2(BoolIntPair.getCPtr(other), other), true);
  }

  public void setFirst(boolean value) {
    AIOpterJNI.BoolIntPair_first_set(swigCPtr, this, value);
  }

  public boolean getFirst() {
    return AIOpterJNI.BoolIntPair_first_get(swigCPtr, this);
  }

  public void setSecond(int value) {
    AIOpterJNI.BoolIntPair_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return AIOpterJNI.BoolIntPair_second_get(swigCPtr, this);
  }

}
