/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class CommonConstrain {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CommonConstrain(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommonConstrain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CommonConstrain obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIOpterJNI.delete_CommonConstrain(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CommonConstrain() {
    this(AIOpterJNI.new_CommonConstrain(), true);
  }

  public void setM_ShortWaveLimit(double value) {
    AIOpterJNI.CommonConstrain_m_ShortWaveLimit_set(swigCPtr, this, value);
  }

  public double getM_ShortWaveLimit() {
    return AIOpterJNI.CommonConstrain_m_ShortWaveLimit_get(swigCPtr, this);
  }

  public void setM_ShortWaveLength(double value) {
    AIOpterJNI.CommonConstrain_m_ShortWaveLength_set(swigCPtr, this, value);
  }

  public double getM_ShortWaveLength() {
    return AIOpterJNI.CommonConstrain_m_ShortWaveLength_get(swigCPtr, this);
  }

  public void setM_ShortWaveIndexMargin(int value) {
    AIOpterJNI.CommonConstrain_m_ShortWaveIndexMargin_set(swigCPtr, this, value);
  }

  public int getM_ShortWaveIndexMargin() {
    return AIOpterJNI.CommonConstrain_m_ShortWaveIndexMargin_get(swigCPtr, this);
  }

  public void setM_LongWaveLimit(double value) {
    AIOpterJNI.CommonConstrain_m_LongWaveLimit_set(swigCPtr, this, value);
  }

  public double getM_LongWaveLimit() {
    return AIOpterJNI.CommonConstrain_m_LongWaveLimit_get(swigCPtr, this);
  }

  public void setM_LongWaveLength(double value) {
    AIOpterJNI.CommonConstrain_m_LongWaveLength_set(swigCPtr, this, value);
  }

  public double getM_LongWaveLength() {
    return AIOpterJNI.CommonConstrain_m_LongWaveLength_get(swigCPtr, this);
  }

  public void setM_LongWaveIndexMargin(int value) {
    AIOpterJNI.CommonConstrain_m_LongWaveIndexMargin_set(swigCPtr, this, value);
  }

  public int getM_LongWaveIndexMargin() {
    return AIOpterJNI.CommonConstrain_m_LongWaveIndexMargin_get(swigCPtr, this);
  }

  public void setM_SuperSlope(double value) {
    AIOpterJNI.CommonConstrain_m_SuperSlope_set(swigCPtr, this, value);
  }

  public double getM_SuperSlope() {
    return AIOpterJNI.CommonConstrain_m_SuperSlope_get(swigCPtr, this);
  }

  public void setM_factor(double value) {
    AIOpterJNI.CommonConstrain_m_factor_set(swigCPtr, this, value);
  }

  public double getM_factor() {
    return AIOpterJNI.CommonConstrain_m_factor_get(swigCPtr, this);
  }

  public void setIsFixed(boolean value) {
    AIOpterJNI.CommonConstrain_isFixed_set(swigCPtr, this, value);
  }

  public boolean getIsFixed() {
    return AIOpterJNI.CommonConstrain_isFixed_get(swigCPtr, this);
  }

  public void setIsPlane(boolean value) {
    AIOpterJNI.CommonConstrain_isPlane_set(swigCPtr, this, value);
  }

  public boolean getIsPlane() {
    return AIOpterJNI.CommonConstrain_isPlane_get(swigCPtr, this);
  }

  public void setIsByVert(boolean value) {
    AIOpterJNI.CommonConstrain_isByVert_set(swigCPtr, this, value);
  }

  public boolean getIsByVert() {
    return AIOpterJNI.CommonConstrain_isByVert_get(swigCPtr, this);
  }

  public void setM_CtrlCurve(double value) {
    AIOpterJNI.CommonConstrain_m_CtrlCurve_set(swigCPtr, this, value);
  }

  public double getM_CtrlCurve() {
    return AIOpterJNI.CommonConstrain_m_CtrlCurve_get(swigCPtr, this);
  }

}
