/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class OptData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OptData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIOpterJNI.delete_OptData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptData() {
    this(AIOpterJNI.new_OptData__SWIG_0(), true);
  }

  public OptData(double dX, double dY, double dY_U, double dY_L) {
    this(AIOpterJNI.new_OptData__SWIG_1(dX, dY, dY_U, dY_L), true);
  }

  public OptData(double dX, double dY, double dY_U) {
    this(AIOpterJNI.new_OptData__SWIG_2(dX, dY, dY_U), true);
  }

  public OptData(double dX, double dY) {
    this(AIOpterJNI.new_OptData__SWIG_3(dX, dY), true);
  }

  public void setX(double value) {
    AIOpterJNI.OptData_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return AIOpterJNI.OptData_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    AIOpterJNI.OptData_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return AIOpterJNI.OptData_y_get(swigCPtr, this);
  }

  public void setY_up(double value) {
    AIOpterJNI.OptData_y_up_set(swigCPtr, this, value);
  }

  public double getY_up() {
    return AIOpterJNI.OptData_y_up_get(swigCPtr, this);
  }

  public void setY_down(double value) {
    AIOpterJNI.OptData_y_down_set(swigCPtr, this, value);
  }

  public double getY_down() {
    return AIOpterJNI.OptData_y_down_get(swigCPtr, this);
  }

}
