/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class OptDataVector extends java.util.AbstractList<OptData> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptDataVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptDataVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OptDataVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIOpterJNI.delete_OptDataVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptDataVector(OptData[] initialElements) {
    this();
    reserve(initialElements.length);

    for (OptData element : initialElements) {
      add(element);
    }
  }

  public OptDataVector(Iterable<OptData> initialElements) {
    this();
    for (OptData element : initialElements) {
      add(element);
    }
  }

  public OptData get(int index) {
    return doGet(index);
  }

  public OptData set(int index, OptData e) {
    return doSet(index, e);
  }

  public boolean add(OptData e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, OptData e) {
    modCount++;
    doAdd(index, e);
  }

  public OptData remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public OptDataVector() {
    this(AIOpterJNI.new_OptDataVector__SWIG_0(), true);
  }

  public OptDataVector(OptDataVector other) {
    this(AIOpterJNI.new_OptDataVector__SWIG_1(OptDataVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AIOpterJNI.OptDataVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AIOpterJNI.OptDataVector_clear(swigCPtr, this);
  }

  public OptDataVector(int count, OptData value) {
    this(AIOpterJNI.new_OptDataVector__SWIG_2(count, OptData.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AIOpterJNI.OptDataVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AIOpterJNI.OptDataVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AIOpterJNI.OptDataVector_doSize(swigCPtr, this);
  }

  private void doAdd(OptData x) {
    AIOpterJNI.OptDataVector_doAdd__SWIG_0(swigCPtr, this, OptData.getCPtr(x), x);
  }

  private void doAdd(int index, OptData x) {
    AIOpterJNI.OptDataVector_doAdd__SWIG_1(swigCPtr, this, index, OptData.getCPtr(x), x);
  }

  private OptData doRemove(int index) {
    return new OptData(AIOpterJNI.OptDataVector_doRemove(swigCPtr, this, index), true);
  }

  private OptData doGet(int index) {
    return new OptData(AIOpterJNI.OptDataVector_doGet(swigCPtr, this, index), false);
  }

  private OptData doSet(int index, OptData val) {
    return new OptData(AIOpterJNI.OptDataVector_doSet(swigCPtr, this, index, OptData.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AIOpterJNI.OptDataVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
