/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class OpterProcesser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpterProcesser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpterProcesser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OpterProcesser obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIOpterJNI.delete_OpterProcesser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OpterProcesser(OptDataVector measureData, CommonConstrain constrain) {
    this(AIOpterJNI.new_OpterProcesser(OptDataVector.getCPtr(measureData), measureData, CommonConstrain.getCPtr(constrain), constrain), true);
  }

  public OptDataVector GetOptResult() {
    return new OptDataVector(AIOpterJNI.OpterProcesser_GetOptResult(swigCPtr, this), true);
  }

  public boolean StartOpt() {
    return AIOpterJNI.OpterProcesser_StartOpt(swigCPtr, this);
  }

  public boolean StartOptPro() {
    return AIOpterJNI.OpterProcesser_StartOptPro(swigCPtr, this);
  }

  public void setM_constraints(CommonConstrain value) {
    AIOpterJNI.OpterProcesser_m_constraints_set(swigCPtr, this, CommonConstrain.getCPtr(value), value);
  }

  public CommonConstrain getM_constraints() {
    long cPtr = AIOpterJNI.OpterProcesser_m_constraints_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CommonConstrain(cPtr, false);
  }

}
