/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlOpter;

public class Splineline {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Splineline(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Splineline obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Splineline obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AIOpterJNI.delete_Splineline(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Splineline() {
    this(AIOpterJNI.new_Splineline__SWIG_0(), true);
  }

  public Splineline(OptDataVector datas) {
    this(AIOpterJNI.new_Splineline__SWIG_1(OptDataVector.getCPtr(datas), datas), true);
  }

  public boolean ReInitData(OptDataVector optDatas, OptDataVector datas, OptDataVector pickedPts) {
    return AIOpterJNI.Splineline_ReInitData(swigCPtr, this, OptDataVector.getCPtr(optDatas), optDatas, OptDataVector.getCPtr(datas), datas, OptDataVector.getCPtr(pickedPts), pickedPts);
  }

  public boolean Init(double margin) {
    return AIOpterJNI.Splineline_Init(swigCPtr, this, margin);
  }

  public OptDataVector GetData() {
    return new OptDataVector(AIOpterJNI.Splineline_GetData(swigCPtr, this), true);
  }

  public void SetDatas(OptDataVector datas) {
    AIOpterJNI.Splineline_SetDatas(swigCPtr, this, OptDataVector.getCPtr(datas), datas);
  }

  public OptDataVector GetAllPickPts() {
    return new OptDataVector(AIOpterJNI.Splineline_GetAllPickPts(swigCPtr, this), true);
  }

  public int GetPickPtsCount() {
    return AIOpterJNI.Splineline_GetPickPtsCount(swigCPtr, this);
  }

  public BoolIntPair PickPoint(OptData datas, double tol) {
    return new BoolIntPair(AIOpterJNI.Splineline_PickPoint__SWIG_0(swigCPtr, this, OptData.getCPtr(datas), datas, tol), true);
  }

  public BoolIntPair PickPoint(OptData datas) {
    return new BoolIntPair(AIOpterJNI.Splineline_PickPoint__SWIG_1(swigCPtr, this, OptData.getCPtr(datas), datas), true);
  }

  public boolean RemovePickPoint(int nIndex) {
    return AIOpterJNI.Splineline_RemovePickPoint(swigCPtr, this, nIndex);
  }

  public boolean InsertPickPoint(OptData datas) {
    return AIOpterJNI.Splineline_InsertPickPoint(swigCPtr, this, OptData.getCPtr(datas), datas);
  }

  public boolean MovePickPoint(int index, OptData datas) {
    return AIOpterJNI.Splineline_MovePickPoint(swigCPtr, this, index, OptData.getCPtr(datas), datas);
  }

}
