/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class DoubleArr extends java.util.AbstractList<Double> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DoubleArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_DoubleArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleArr(double[] initialElements) {
    this();
    reserve(initialElements.length);

    for (double element : initialElements) {
      add(element);
    }
  }

  public DoubleArr(Iterable<Double> initialElements) {
    this();
    for (double element : initialElements) {
      add(element);
    }
  }

  public Double get(int index) {
    return doGet(index);
  }

  public Double set(int index, Double e) {
    return doSet(index, e);
  }

  public boolean add(Double e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Double e) {
    modCount++;
    doAdd(index, e);
  }

  public Double remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public DoubleArr() {
    this(BallastlessSCIPJNI.new_DoubleArr__SWIG_0(), true);
  }

  public DoubleArr(DoubleArr other) {
    this(BallastlessSCIPJNI.new_DoubleArr__SWIG_1(DoubleArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return BallastlessSCIPJNI.DoubleArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    BallastlessSCIPJNI.DoubleArr_clear(swigCPtr, this);
  }

  public DoubleArr(int count, double value) {
    this(BallastlessSCIPJNI.new_DoubleArr__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return BallastlessSCIPJNI.DoubleArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    BallastlessSCIPJNI.DoubleArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return BallastlessSCIPJNI.DoubleArr_doSize(swigCPtr, this);
  }

  private void doAdd(double x) {
    BallastlessSCIPJNI.DoubleArr_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, double x) {
    BallastlessSCIPJNI.DoubleArr_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private double doRemove(int index) {
    return BallastlessSCIPJNI.DoubleArr_doRemove(swigCPtr, this, index);
  }

  private double doGet(int index) {
    return BallastlessSCIPJNI.DoubleArr_doGet(swigCPtr, this, index);
  }

  private double doSet(int index, double val) {
    return BallastlessSCIPJNI.DoubleArr_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    BallastlessSCIPJNI.DoubleArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
