/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class OptConstrain {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptConstrain(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptConstrain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OptConstrain obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_OptConstrain(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptConstrain() {
    this(BallastlessSCIPJNI.new_OptConstrain(), true);
  }

  public void setSW_10(double value) {
    BallastlessSCIPJNI.OptConstrain_SW_10_set(swigCPtr, this, value);
  }

  public double getSW_10() {
    return BallastlessSCIPJNI.OptConstrain_SW_10_get(swigCPtr, this);
  }

  public void setSW_Length(double value) {
    BallastlessSCIPJNI.OptConstrain_SW_Length_set(swigCPtr, this, value);
  }

  public double getSW_Length() {
    return BallastlessSCIPJNI.OptConstrain_SW_Length_get(swigCPtr, this);
  }

  public void setLW_30(double value) {
    BallastlessSCIPJNI.OptConstrain_LW_30_set(swigCPtr, this, value);
  }

  public double getLW_30() {
    return BallastlessSCIPJNI.OptConstrain_LW_30_get(swigCPtr, this);
  }

  public void setLW_300(double value) {
    BallastlessSCIPJNI.OptConstrain_LW_300_set(swigCPtr, this, value);
  }

  public double getLW_300() {
    return BallastlessSCIPJNI.OptConstrain_LW_300_get(swigCPtr, this);
  }

  public void setLW_300_Considered(boolean value) {
    BallastlessSCIPJNI.OptConstrain_LW_300_Considered_set(swigCPtr, this, value);
  }

  public boolean getLW_300_Considered() {
    return BallastlessSCIPJNI.OptConstrain_LW_300_Considered_get(swigCPtr, this);
  }

  public void setGaugeL(double value) {
    BallastlessSCIPJNI.OptConstrain_GaugeL_set(swigCPtr, this, value);
  }

  public double getGaugeL() {
    return BallastlessSCIPJNI.OptConstrain_GaugeL_get(swigCPtr, this);
  }

  public void setGaugeRate(double value) {
    BallastlessSCIPJNI.OptConstrain_GaugeRate_set(swigCPtr, this, value);
  }

  public double getGaugeRate() {
    return BallastlessSCIPJNI.OptConstrain_GaugeRate_get(swigCPtr, this);
  }

  public void setMarginL(double value) {
    BallastlessSCIPJNI.OptConstrain_MarginL_set(swigCPtr, this, value);
  }

  public double getMarginL() {
    return BallastlessSCIPJNI.OptConstrain_MarginL_get(swigCPtr, this);
  }

  public void setTwistL(double value) {
    BallastlessSCIPJNI.OptConstrain_TwistL_set(swigCPtr, this, value);
  }

  public double getTwistL() {
    return BallastlessSCIPJNI.OptConstrain_TwistL_get(swigCPtr, this);
  }

  public void setIsFixed(boolean value) {
    BallastlessSCIPJNI.OptConstrain_isFixed_set(swigCPtr, this, value);
  }

  public boolean getIsFixed() {
    return BallastlessSCIPJNI.OptConstrain_isFixed_get(swigCPtr, this);
  }

  public void setRegressionFactor(double value) {
    BallastlessSCIPJNI.OptConstrain_regressionFactor_set(swigCPtr, this, value);
  }

  public double getRegressionFactor() {
    return BallastlessSCIPJNI.OptConstrain_regressionFactor_get(swigCPtr, this);
  }

  public void setMinFactor(double value) {
    BallastlessSCIPJNI.OptConstrain_minFactor_set(swigCPtr, this, value);
  }

  public double getMinFactor() {
    return BallastlessSCIPJNI.OptConstrain_minFactor_get(swigCPtr, this);
  }

  public void setIsDifferential(boolean value) {
    BallastlessSCIPJNI.OptConstrain_isDifferential_set(swigCPtr, this, value);
  }

  public boolean getIsDifferential() {
    return BallastlessSCIPJNI.OptConstrain_isDifferential_get(swigCPtr, this);
  }

  public void setBResultLongWave(boolean value) {
    BallastlessSCIPJNI.OptConstrain_bResultLongWave_set(swigCPtr, this, value);
  }

  public boolean getBResultLongWave() {
    return BallastlessSCIPJNI.OptConstrain_bResultLongWave_get(swigCPtr, this);
  }

  public void setUnitL_l(double value) {
    BallastlessSCIPJNI.OptConstrain_UnitL_l_set(swigCPtr, this, value);
  }

  public double getUnitL_l() {
    return BallastlessSCIPJNI.OptConstrain_UnitL_l_get(swigCPtr, this);
  }

  public void setUnitL_u(double value) {
    BallastlessSCIPJNI.OptConstrain_UnitL_u_set(swigCPtr, this, value);
  }

  public double getUnitL_u() {
    return BallastlessSCIPJNI.OptConstrain_UnitL_u_get(swigCPtr, this);
  }

  public void setUnitR_l(double value) {
    BallastlessSCIPJNI.OptConstrain_UnitR_l_set(swigCPtr, this, value);
  }

  public double getUnitR_l() {
    return BallastlessSCIPJNI.OptConstrain_UnitR_l_get(swigCPtr, this);
  }

  public void setUnitR_u(double value) {
    BallastlessSCIPJNI.OptConstrain_UnitR_u_set(swigCPtr, this, value);
  }

  public double getUnitR_u() {
    return BallastlessSCIPJNI.OptConstrain_UnitR_u_get(swigCPtr, this);
  }

  public void setNPtCount(int value) {
    BallastlessSCIPJNI.OptConstrain_nPtCount_set(swigCPtr, this, value);
  }

  public int getNPtCount() {
    return BallastlessSCIPJNI.OptConstrain_nPtCount_get(swigCPtr, this);
  }

}
