/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class OptValueData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptValueData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptValueData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OptValueData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_OptValueData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptValueData() {
    this(BallastlessSCIPJNI.new_OptValueData(), true);
  }

  public void setXOpt_L(double value) {
    BallastlessSCIPJNI.OptValueData_xOpt_L_set(swigCPtr, this, value);
  }

  public double getXOpt_L() {
    return BallastlessSCIPJNI.OptValueData_xOpt_L_get(swigCPtr, this);
  }

  public void setXOpt_R(double value) {
    BallastlessSCIPJNI.OptValueData_xOpt_R_set(swigCPtr, this, value);
  }

  public double getXOpt_R() {
    return BallastlessSCIPJNI.OptValueData_xOpt_R_get(swigCPtr, this);
  }

  public void setYOpt_L(double value) {
    BallastlessSCIPJNI.OptValueData_yOpt_L_set(swigCPtr, this, value);
  }

  public double getYOpt_L() {
    return BallastlessSCIPJNI.OptValueData_yOpt_L_get(swigCPtr, this);
  }

  public void setYOpt_R(double value) {
    BallastlessSCIPJNI.OptValueData_yOpt_R_set(swigCPtr, this, value);
  }

  public double getYOpt_R() {
    return BallastlessSCIPJNI.OptValueData_yOpt_R_get(swigCPtr, this);
  }

}
