/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class OptValArr extends java.util.AbstractList<OptValueData> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptValArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptValArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OptValArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_OptValArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptValArr(OptValueData[] initialElements) {
    this();
    reserve(initialElements.length);

    for (OptValueData element : initialElements) {
      add(element);
    }
  }

  public OptValArr(Iterable<OptValueData> initialElements) {
    this();
    for (OptValueData element : initialElements) {
      add(element);
    }
  }

  public OptValueData get(int index) {
    return doGet(index);
  }

  public OptValueData set(int index, OptValueData e) {
    return doSet(index, e);
  }

  public boolean add(OptValueData e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, OptValueData e) {
    modCount++;
    doAdd(index, e);
  }

  public OptValueData remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public OptValArr() {
    this(BallastlessSCIPJNI.new_OptValArr__SWIG_0(), true);
  }

  public OptValArr(OptValArr other) {
    this(BallastlessSCIPJNI.new_OptValArr__SWIG_1(OptValArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return BallastlessSCIPJNI.OptValArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    BallastlessSCIPJNI.OptValArr_clear(swigCPtr, this);
  }

  public OptValArr(int count, OptValueData value) {
    this(BallastlessSCIPJNI.new_OptValArr__SWIG_2(count, OptValueData.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return BallastlessSCIPJNI.OptValArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    BallastlessSCIPJNI.OptValArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return BallastlessSCIPJNI.OptValArr_doSize(swigCPtr, this);
  }

  private void doAdd(OptValueData x) {
    BallastlessSCIPJNI.OptValArr_doAdd__SWIG_0(swigCPtr, this, OptValueData.getCPtr(x), x);
  }

  private void doAdd(int index, OptValueData x) {
    BallastlessSCIPJNI.OptValArr_doAdd__SWIG_1(swigCPtr, this, index, OptValueData.getCPtr(x), x);
  }

  private OptValueData doRemove(int index) {
    return new OptValueData(BallastlessSCIPJNI.OptValArr_doRemove(swigCPtr, this, index), true);
  }

  private OptValueData doGet(int index) {
    return new OptValueData(BallastlessSCIPJNI.OptValArr_doGet(swigCPtr, this, index), false);
  }

  private OptValueData doSet(int index, OptValueData val) {
    return new OptValueData(BallastlessSCIPJNI.OptValArr_doSet(swigCPtr, this, index, OptValueData.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    BallastlessSCIPJNI.OptValArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
