/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class PickPt {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PickPt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PickPt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PickPt obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_PickPt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PickPt(double dX, double dY) {
    this(BallastlessSCIPJNI.new_PickPt(dX, dY), true);
  }

  public void setX(double value) {
    BallastlessSCIPJNI.PickPt_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return BallastlessSCIPJNI.PickPt_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    BallastlessSCIPJNI.PickPt_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return BallastlessSCIPJNI.PickPt_y_get(swigCPtr, this);
  }

}
