/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class PickPtArr extends java.util.AbstractList<PickPt> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PickPtArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PickPtArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PickPtArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_PickPtArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PickPtArr(PickPt[] initialElements) {
    this();
    reserve(initialElements.length);

    for (PickPt element : initialElements) {
      add(element);
    }
  }

  public PickPtArr(Iterable<PickPt> initialElements) {
    this();
    for (PickPt element : initialElements) {
      add(element);
    }
  }

  public PickPt get(int index) {
    return doGet(index);
  }

  public PickPt set(int index, PickPt e) {
    return doSet(index, e);
  }

  public boolean add(PickPt e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, PickPt e) {
    modCount++;
    doAdd(index, e);
  }

  public PickPt remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public PickPtArr() {
    this(BallastlessSCIPJNI.new_PickPtArr__SWIG_0(), true);
  }

  public PickPtArr(PickPtArr other) {
    this(BallastlessSCIPJNI.new_PickPtArr__SWIG_1(PickPtArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return BallastlessSCIPJNI.PickPtArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    BallastlessSCIPJNI.PickPtArr_clear(swigCPtr, this);
  }

  public PickPtArr(int count, PickPt value) {
    this(BallastlessSCIPJNI.new_PickPtArr__SWIG_2(count, PickPt.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return BallastlessSCIPJNI.PickPtArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    BallastlessSCIPJNI.PickPtArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return BallastlessSCIPJNI.PickPtArr_doSize(swigCPtr, this);
  }

  private void doAdd(PickPt x) {
    BallastlessSCIPJNI.PickPtArr_doAdd__SWIG_0(swigCPtr, this, PickPt.getCPtr(x), x);
  }

  private void doAdd(int index, PickPt x) {
    BallastlessSCIPJNI.PickPtArr_doAdd__SWIG_1(swigCPtr, this, index, PickPt.getCPtr(x), x);
  }

  private PickPt doRemove(int index) {
    return new PickPt(BallastlessSCIPJNI.PickPtArr_doRemove(swigCPtr, this, index), true);
  }

  private PickPt doGet(int index) {
    return new PickPt(BallastlessSCIPJNI.PickPtArr_doGet(swigCPtr, this, index), false);
  }

  private PickPt doSet(int index, PickPt val) {
    return new PickPt(BallastlessSCIPJNI.PickPtArr_doSet(swigCPtr, this, index, PickPt.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    BallastlessSCIPJNI.PickPtArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
