/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class RailRelativeAPI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RailRelativeAPI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RailRelativeAPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RailRelativeAPI obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_RailRelativeAPI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RailRelativeAPI() {
    this(BallastlessSCIPJNI.new_RailRelativeAPI__SWIG_0(), true);
  }

  public RailRelativeAPI(RailOptArr datas, RelativeOptPara constrain) {
    this(BallastlessSCIPJNI.new_RailRelativeAPI__SWIG_1(RailOptArr.getCPtr(datas), datas, RelativeOptPara.getCPtr(constrain), constrain), true);
  }

  public boolean StartOptHori() {
    return BallastlessSCIPJNI.RailRelativeAPI_StartOptHori(swigCPtr, this);
  }

  public boolean StartOptVert() {
    return BallastlessSCIPJNI.RailRelativeAPI_StartOptVert(swigCPtr, this);
  }

  public OptValArr GetResult() {
    return new OptValArr(BallastlessSCIPJNI.RailRelativeAPI_GetResult(swigCPtr, this), true);
  }

}
