/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class RailAPI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RailAPI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RailAPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RailAPI obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_RailAPI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RailAPI() {
    this(BallastlessSCIPJNI.new_RailAPI__SWIG_0(), true);
  }

  public RailAPI(RtSurveyPtArr datas, OptConstrain constrain) {
    this(BallastlessSCIPJNI.new_RailAPI__SWIG_1(RtSurveyPtArr.getCPtr(datas), datas, OptConstrain.getCPtr(constrain), constrain), true);
  }

  public boolean StartOptHori() {
    return BallastlessSCIPJNI.RailAPI_StartOptHori(swigCPtr, this);
  }

  public boolean StartOptVert() {
    return BallastlessSCIPJNI.RailAPI_StartOptVert(swigCPtr, this);
  }

  public boolean StartOptHoriForLong() {
    return BallastlessSCIPJNI.RailAPI_StartOptHoriForLong(swigCPtr, this);
  }

  public boolean StartOptVertForLong() {
    return BallastlessSCIPJNI.RailAPI_StartOptVertForLong(swigCPtr, this);
  }

  public OptValArr GetResult() {
    return new OptValArr(BallastlessSCIPJNI.RailAPI_GetResult(swigCPtr, this), true);
  }

  public void GetPicks(PickPtArr leftPts, PickPtArr rightPts) {
    BallastlessSCIPJNI.RailAPI_GetPicks(swigCPtr, this, PickPtArr.getCPtr(leftPts), leftPts, PickPtArr.getCPtr(rightPts), rightPts);
  }

  public static void ChordLineFor300(DoubleArr datas, DoubleArr results) {
    BallastlessSCIPJNI.RailAPI_ChordLineFor300(DoubleArr.getCPtr(datas), datas, DoubleArr.getCPtr(results), results);
  }

  public static void ChordLineFor30(DoubleArr datas, DoubleArr results) {
    BallastlessSCIPJNI.RailAPI_ChordLineFor30(DoubleArr.getCPtr(datas), datas, DoubleArr.getCPtr(results), results);
  }

  public static void ChordLineFor10(DoubleArr datas, DoubleArr results) {
    BallastlessSCIPJNI.RailAPI_ChordLineFor10(DoubleArr.getCPtr(datas), datas, DoubleArr.getCPtr(results), results);
  }

  public static boolean _RoundForResultHCompare(DoubleArr leftMargin, DoubleArr rightMargin, OptValArr optDatas, double upVal, double downVal, double dVal) {
    return BallastlessSCIPJNI.RailAPI__RoundForResultHCompare__SWIG_0(DoubleArr.getCPtr(leftMargin), leftMargin, DoubleArr.getCPtr(rightMargin), rightMargin, OptValArr.getCPtr(optDatas), optDatas, upVal, downVal, dVal);
  }

  public static boolean _RoundForResultHCompare(DoubleArr leftMargin, DoubleArr rightMargin, OptValArr optDatas, double upVal, double downVal) {
    return BallastlessSCIPJNI.RailAPI__RoundForResultHCompare__SWIG_1(DoubleArr.getCPtr(leftMargin), leftMargin, DoubleArr.getCPtr(rightMargin), rightMargin, OptValArr.getCPtr(optDatas), optDatas, upVal, downVal);
  }

  public static boolean _RoundForResultVCompare(DoubleArr leftMargin, DoubleArr rightMargin, OptValArr optDatas, double upVal, double downVal, double dVal) {
    return BallastlessSCIPJNI.RailAPI__RoundForResultVCompare__SWIG_0(DoubleArr.getCPtr(leftMargin), leftMargin, DoubleArr.getCPtr(rightMargin), rightMargin, OptValArr.getCPtr(optDatas), optDatas, upVal, downVal, dVal);
  }

  public static boolean _RoundForResultVCompare(DoubleArr leftMargin, DoubleArr rightMargin, OptValArr optDatas, double upVal, double downVal) {
    return BallastlessSCIPJNI.RailAPI__RoundForResultVCompare__SWIG_1(DoubleArr.getCPtr(leftMargin), leftMargin, DoubleArr.getCPtr(rightMargin), rightMargin, OptValArr.getCPtr(optDatas), optDatas, upVal, downVal);
  }

}
