/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class RailOptVal {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RailOptVal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RailOptVal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RailOptVal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_RailOptVal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RailOptVal() {
    this(BallastlessSCIPJNI.new_RailOptVal__SWIG_0(), true);
  }

  public RailOptVal(double dMileage, double originL, double originR, double margin, double twist, double dUpL, double dLowL, double dUpR, double dLowR) {
    this(BallastlessSCIPJNI.new_RailOptVal__SWIG_1(dMileage, originL, originR, margin, twist, dUpL, dLowL, dUpR, dLowR), true);
  }

  public void setM_mileage(double value) {
    BallastlessSCIPJNI.RailOptVal_m_mileage_set(swigCPtr, this, value);
  }

  public double getM_mileage() {
    return BallastlessSCIPJNI.RailOptVal_m_mileage_get(swigCPtr, this);
  }

  public void setOrigin_L(double value) {
    BallastlessSCIPJNI.RailOptVal_origin_L_set(swigCPtr, this, value);
  }

  public double getOrigin_L() {
    return BallastlessSCIPJNI.RailOptVal_origin_L_get(swigCPtr, this);
  }

  public void setOrigin_R(double value) {
    BallastlessSCIPJNI.RailOptVal_origin_R_set(swigCPtr, this, value);
  }

  public double getOrigin_R() {
    return BallastlessSCIPJNI.RailOptVal_origin_R_get(swigCPtr, this);
  }

  public void setM_margin(double value) {
    BallastlessSCIPJNI.RailOptVal_m_margin_set(swigCPtr, this, value);
  }

  public double getM_margin() {
    return BallastlessSCIPJNI.RailOptVal_m_margin_get(swigCPtr, this);
  }

  public void setM_twist(double value) {
    BallastlessSCIPJNI.RailOptVal_m_twist_set(swigCPtr, this, value);
  }

  public double getM_twist() {
    return BallastlessSCIPJNI.RailOptVal_m_twist_get(swigCPtr, this);
  }

  public void setM_UpL(double value) {
    BallastlessSCIPJNI.RailOptVal_m_UpL_set(swigCPtr, this, value);
  }

  public double getM_UpL() {
    return BallastlessSCIPJNI.RailOptVal_m_UpL_get(swigCPtr, this);
  }

  public void setM_LowL(double value) {
    BallastlessSCIPJNI.RailOptVal_m_LowL_set(swigCPtr, this, value);
  }

  public double getM_LowL() {
    return BallastlessSCIPJNI.RailOptVal_m_LowL_get(swigCPtr, this);
  }

  public void setM_UpR(double value) {
    BallastlessSCIPJNI.RailOptVal_m_UpR_set(swigCPtr, this, value);
  }

  public double getM_UpR() {
    return BallastlessSCIPJNI.RailOptVal_m_UpR_get(swigCPtr, this);
  }

  public void setM_LowR(double value) {
    BallastlessSCIPJNI.RailOptVal_m_LowR_set(swigCPtr, this, value);
  }

  public double getM_LowR() {
    return BallastlessSCIPJNI.RailOptVal_m_LowR_get(swigCPtr, this);
  }

}
