/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class RailOptArr extends java.util.AbstractList<RailOptVal> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RailOptArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RailOptArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RailOptArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_RailOptArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RailOptArr(RailOptVal[] initialElements) {
    this();
    reserve(initialElements.length);

    for (RailOptVal element : initialElements) {
      add(element);
    }
  }

  public RailOptArr(Iterable<RailOptVal> initialElements) {
    this();
    for (RailOptVal element : initialElements) {
      add(element);
    }
  }

  public RailOptVal get(int index) {
    return doGet(index);
  }

  public RailOptVal set(int index, RailOptVal e) {
    return doSet(index, e);
  }

  public boolean add(RailOptVal e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, RailOptVal e) {
    modCount++;
    doAdd(index, e);
  }

  public RailOptVal remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public RailOptArr() {
    this(BallastlessSCIPJNI.new_RailOptArr__SWIG_0(), true);
  }

  public RailOptArr(RailOptArr other) {
    this(BallastlessSCIPJNI.new_RailOptArr__SWIG_1(RailOptArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return BallastlessSCIPJNI.RailOptArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    BallastlessSCIPJNI.RailOptArr_clear(swigCPtr, this);
  }

  public RailOptArr(int count, RailOptVal value) {
    this(BallastlessSCIPJNI.new_RailOptArr__SWIG_2(count, RailOptVal.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return BallastlessSCIPJNI.RailOptArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    BallastlessSCIPJNI.RailOptArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return BallastlessSCIPJNI.RailOptArr_doSize(swigCPtr, this);
  }

  private void doAdd(RailOptVal x) {
    BallastlessSCIPJNI.RailOptArr_doAdd__SWIG_0(swigCPtr, this, RailOptVal.getCPtr(x), x);
  }

  private void doAdd(int index, RailOptVal x) {
    BallastlessSCIPJNI.RailOptArr_doAdd__SWIG_1(swigCPtr, this, index, RailOptVal.getCPtr(x), x);
  }

  private RailOptVal doRemove(int index) {
    return new RailOptVal(BallastlessSCIPJNI.RailOptArr_doRemove(swigCPtr, this, index), true);
  }

  private RailOptVal doGet(int index) {
    return new RailOptVal(BallastlessSCIPJNI.RailOptArr_doGet(swigCPtr, this, index), false);
  }

  private RailOptVal doSet(int index, RailOptVal val) {
    return new RailOptVal(BallastlessSCIPJNI.RailOptArr_doSet(swigCPtr, this, index, RailOptVal.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    BallastlessSCIPJNI.RailOptArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
