/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class RailTrackSurveyPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RailTrackSurveyPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RailTrackSurveyPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RailTrackSurveyPoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_RailTrackSurveyPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RailTrackSurveyPoint() {
    this(BallastlessSCIPJNI.new_RailTrackSurveyPoint(), true);
  }

  public void setMileage(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_mileage_set(swigCPtr, this, value);
  }

  public double getMileage() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_mileage_get(swigCPtr, this);
  }

  public void setX_L(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_x_L_set(swigCPtr, this, value);
  }

  public double getX_L() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_x_L_get(swigCPtr, this);
  }

  public void setX_R(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_x_R_set(swigCPtr, this, value);
  }

  public double getX_R() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_x_R_get(swigCPtr, this);
  }

  public void setY_L(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_y_L_set(swigCPtr, this, value);
  }

  public double getY_L() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_y_L_get(swigCPtr, this);
  }

  public void setY_R(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_y_R_set(swigCPtr, this, value);
  }

  public double getY_R() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_y_R_get(swigCPtr, this);
  }

  public void setGauge(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_gauge_set(swigCPtr, this, value);
  }

  public double getGauge() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_gauge_get(swigCPtr, this);
  }

  public void setMargin(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_margin_set(swigCPtr, this, value);
  }

  public double getMargin() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_margin_get(swigCPtr, this);
  }

  public void setX_L_Con_l(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_x_L_Con_l_set(swigCPtr, this, value);
  }

  public double getX_L_Con_l() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_x_L_Con_l_get(swigCPtr, this);
  }

  public void setX_L_Con_u(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_x_L_Con_u_set(swigCPtr, this, value);
  }

  public double getX_L_Con_u() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_x_L_Con_u_get(swigCPtr, this);
  }

  public void setX_R_Con_l(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_x_R_Con_l_set(swigCPtr, this, value);
  }

  public double getX_R_Con_l() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_x_R_Con_l_get(swigCPtr, this);
  }

  public void setX_R_Con_u(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_x_R_Con_u_set(swigCPtr, this, value);
  }

  public double getX_R_Con_u() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_x_R_Con_u_get(swigCPtr, this);
  }

  public void setY_L_Con_l(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_y_L_Con_l_set(swigCPtr, this, value);
  }

  public double getY_L_Con_l() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_y_L_Con_l_get(swigCPtr, this);
  }

  public void setY_L_Con_u(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_y_L_Con_u_set(swigCPtr, this, value);
  }

  public double getY_L_Con_u() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_y_L_Con_u_get(swigCPtr, this);
  }

  public void setY_R_Con_l(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_y_R_Con_l_set(swigCPtr, this, value);
  }

  public double getY_R_Con_l() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_y_R_Con_l_get(swigCPtr, this);
  }

  public void setY_R_Con_u(double value) {
    BallastlessSCIPJNI.RailTrackSurveyPoint_y_R_Con_u_set(swigCPtr, this, value);
  }

  public double getY_R_Con_u() {
    return BallastlessSCIPJNI.RailTrackSurveyPoint_y_R_Con_u_get(swigCPtr, this);
  }

}
