/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class RelativeOptPara {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RelativeOptPara(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelativeOptPara obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RelativeOptPara obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_RelativeOptPara(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RelativeOptPara() {
    this(BallastlessSCIPJNI.new_RelativeOptPara__SWIG_0(), true);
  }

  public RelativeOptPara(boolean bFixed, double dL, double dU, double dLowL, double dUpL, double dLowR, double dUpR) {
    this(BallastlessSCIPJNI.new_RelativeOptPara__SWIG_1(bFixed, dL, dU, dLowL, dUpL, dLowR, dUpR), true);
  }

  public void setIsFixed(boolean value) {
    BallastlessSCIPJNI.RelativeOptPara_isFixed_set(swigCPtr, this, value);
  }

  public boolean getIsFixed() {
    return BallastlessSCIPJNI.RelativeOptPara_isFixed_get(swigCPtr, this);
  }

  public void setGaugeU(double value) {
    BallastlessSCIPJNI.RelativeOptPara_gaugeU_set(swigCPtr, this, value);
  }

  public double getGaugeU() {
    return BallastlessSCIPJNI.RelativeOptPara_gaugeU_get(swigCPtr, this);
  }

  public void setGaugeL(double value) {
    BallastlessSCIPJNI.RelativeOptPara_gaugeL_set(swigCPtr, this, value);
  }

  public double getGaugeL() {
    return BallastlessSCIPJNI.RelativeOptPara_gaugeL_get(swigCPtr, this);
  }

  public void setUnit_Low_L(double value) {
    BallastlessSCIPJNI.RelativeOptPara_unit_Low_L_set(swigCPtr, this, value);
  }

  public double getUnit_Low_L() {
    return BallastlessSCIPJNI.RelativeOptPara_unit_Low_L_get(swigCPtr, this);
  }

  public void setUnit_Up_L(double value) {
    BallastlessSCIPJNI.RelativeOptPara_unit_Up_L_set(swigCPtr, this, value);
  }

  public double getUnit_Up_L() {
    return BallastlessSCIPJNI.RelativeOptPara_unit_Up_L_get(swigCPtr, this);
  }

  public void setUnit_Low_R(double value) {
    BallastlessSCIPJNI.RelativeOptPara_unit_Low_R_set(swigCPtr, this, value);
  }

  public double getUnit_Low_R() {
    return BallastlessSCIPJNI.RelativeOptPara_unit_Low_R_get(swigCPtr, this);
  }

  public void setUnit_Up_R(double value) {
    BallastlessSCIPJNI.RelativeOptPara_unit_Up_R_set(swigCPtr, this, value);
  }

  public double getUnit_Up_R() {
    return BallastlessSCIPJNI.RelativeOptPara_unit_Up_R_get(swigCPtr, this);
  }

}
