/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlBallastlessRailOpter;

public class RtSurveyPtArr extends java.util.AbstractList<RailTrackSurveyPoint> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RtSurveyPtArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RtSurveyPtArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RtSurveyPtArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BallastlessSCIPJNI.delete_RtSurveyPtArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RtSurveyPtArr(RailTrackSurveyPoint[] initialElements) {
    this();
    reserve(initialElements.length);

    for (RailTrackSurveyPoint element : initialElements) {
      add(element);
    }
  }

  public RtSurveyPtArr(Iterable<RailTrackSurveyPoint> initialElements) {
    this();
    for (RailTrackSurveyPoint element : initialElements) {
      add(element);
    }
  }

  public RailTrackSurveyPoint get(int index) {
    return doGet(index);
  }

  public RailTrackSurveyPoint set(int index, RailTrackSurveyPoint e) {
    return doSet(index, e);
  }

  public boolean add(RailTrackSurveyPoint e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, RailTrackSurveyPoint e) {
    modCount++;
    doAdd(index, e);
  }

  public RailTrackSurveyPoint remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public RtSurveyPtArr() {
    this(BallastlessSCIPJNI.new_RtSurveyPtArr__SWIG_0(), true);
  }

  public RtSurveyPtArr(RtSurveyPtArr other) {
    this(BallastlessSCIPJNI.new_RtSurveyPtArr__SWIG_1(RtSurveyPtArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return BallastlessSCIPJNI.RtSurveyPtArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    BallastlessSCIPJNI.RtSurveyPtArr_clear(swigCPtr, this);
  }

  public RtSurveyPtArr(int count, RailTrackSurveyPoint value) {
    this(BallastlessSCIPJNI.new_RtSurveyPtArr__SWIG_2(count, RailTrackSurveyPoint.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return BallastlessSCIPJNI.RtSurveyPtArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    BallastlessSCIPJNI.RtSurveyPtArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return BallastlessSCIPJNI.RtSurveyPtArr_doSize(swigCPtr, this);
  }

  private void doAdd(RailTrackSurveyPoint x) {
    BallastlessSCIPJNI.RtSurveyPtArr_doAdd__SWIG_0(swigCPtr, this, RailTrackSurveyPoint.getCPtr(x), x);
  }

  private void doAdd(int index, RailTrackSurveyPoint x) {
    BallastlessSCIPJNI.RtSurveyPtArr_doAdd__SWIG_1(swigCPtr, this, index, RailTrackSurveyPoint.getCPtr(x), x);
  }

  private RailTrackSurveyPoint doRemove(int index) {
    return new RailTrackSurveyPoint(BallastlessSCIPJNI.RtSurveyPtArr_doRemove(swigCPtr, this, index), true);
  }

  private RailTrackSurveyPoint doGet(int index) {
    return new RailTrackSurveyPoint(BallastlessSCIPJNI.RtSurveyPtArr_doGet(swigCPtr, this, index), false);
  }

  private RailTrackSurveyPoint doSet(int index, RailTrackSurveyPoint val) {
    return new RailTrackSurveyPoint(BallastlessSCIPJNI.RtSurveyPtArr_doSet(swigCPtr, this, index, RailTrackSurveyPoint.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    BallastlessSCIPJNI.RtSurveyPtArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
