/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class AL_Point3d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AL_Point3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AL_Point3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AL_Point3d obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_AL_Point3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    AlignmentAllJNI.AL_Point3d_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return AlignmentAllJNI.AL_Point3d_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    AlignmentAllJNI.AL_Point3d_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return AlignmentAllJNI.AL_Point3d_y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    AlignmentAllJNI.AL_Point3d_z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return AlignmentAllJNI.AL_Point3d_z_get(swigCPtr, this);
  }

  public AL_Point3d() {
    this(AlignmentAllJNI.new_AL_Point3d__SWIG_0(), true);
  }

  public AL_Point3d(double _x, double _y, double _z) {
    this(AlignmentAllJNI.new_AL_Point3d__SWIG_1(_x, _y, _z), true);
  }

  public double distance(AL_Point3d pt) {
    return AlignmentAllJNI.AL_Point3d_distance(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public double distance2D(AL_Point3d pt) {
    return AlignmentAllJNI.AL_Point3d_distance2D(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public AL_Vector3d toVector3d() {
    return new AL_Vector3d(AlignmentAllJNI.AL_Point3d_toVector3d(swigCPtr, this), true);
  }

  public AL_Point3d Add(AL_Vector3d v) {
    return new AL_Point3d(AlignmentAllJNI.AL_Point3d_Add(swigCPtr, this, AL_Vector3d.getCPtr(v), v), true);
  }

  public AL_Vector3d Subtract(AL_Point3d pt2) {
    return new AL_Vector3d(AlignmentAllJNI.AL_Point3d_Subtract(swigCPtr, this, AL_Point3d.getCPtr(pt2), pt2), true);
  }

  public AL_Point3d Multiply(double dFactor) {
    return new AL_Point3d(AlignmentAllJNI.AL_Point3d_Multiply(swigCPtr, this, dFactor), true);
  }

  public AL_Point3d Devision(double dFactor) {
    return new AL_Point3d(AlignmentAllJNI.AL_Point3d_Devision(swigCPtr, this, dFactor), true);
  }

  public AL_Point3d to2D() {
    return new AL_Point3d(AlignmentAllJNI.AL_Point3d_to2D(swigCPtr, this), true);
  }

  public void negate() {
    AlignmentAllJNI.AL_Point3d_negate(swigCPtr, this);
  }

  public static AL_Point3d Origin() {
    return new AL_Point3d(AlignmentAllJNI.AL_Point3d_Origin(), true);
  }

  public static AL_Point3d ConvPt(AL_Vector3d vec) {
    return new AL_Point3d(AlignmentAllJNI.AL_Point3d_ConvPt(AL_Vector3d.getCPtr(vec), vec), true);
  }

}
