/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class AL_Vector3d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AL_Vector3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AL_Vector3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AL_Vector3d obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_AL_Vector3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    AlignmentAllJNI.AL_Vector3d_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return AlignmentAllJNI.AL_Vector3d_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    AlignmentAllJNI.AL_Vector3d_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return AlignmentAllJNI.AL_Vector3d_y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    AlignmentAllJNI.AL_Vector3d_z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return AlignmentAllJNI.AL_Vector3d_z_get(swigCPtr, this);
  }

  public AL_Vector3d() {
    this(AlignmentAllJNI.new_AL_Vector3d__SWIG_0(), true);
  }

  public AL_Vector3d(double _x, double _y, double _z) {
    this(AlignmentAllJNI.new_AL_Vector3d__SWIG_1(_x, _y, _z), true);
  }

  public void normalize() {
    AlignmentAllJNI.AL_Vector3d_normalize(swigCPtr, this);
  }

  public AL_Vector3d to2D() {
    return new AL_Vector3d(AlignmentAllJNI.AL_Vector3d_to2D(swigCPtr, this), true);
  }

  public AL_Vector3d normal() {
    return new AL_Vector3d(AlignmentAllJNI.AL_Vector3d_normal(swigCPtr, this), true);
  }

  public AL_Vector3d Multiply(double dFactor) {
    return new AL_Vector3d(AlignmentAllJNI.AL_Vector3d_Multiply(swigCPtr, this, dFactor), true);
  }

  public AL_Vector3d crossProduct(AL_Vector3d v) {
    return new AL_Vector3d(AlignmentAllJNI.AL_Vector3d_crossProduct(swigCPtr, this, AL_Vector3d.getCPtr(v), v), true);
  }

  public double crossProductValue(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_crossProductValue(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

  public double dotProduct(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_dotProduct(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

  public double dotProduct2D(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_dotProduct2D(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

  public void rotateBy(double angle) {
    AlignmentAllJNI.AL_Vector3d_rotateBy(swigCPtr, this, angle);
  }

  public AL_Vector3d rotate(double angle) {
    return new AL_Vector3d(AlignmentAllJNI.AL_Vector3d_rotate(swigCPtr, this, angle), true);
  }

  public double angleTo(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_angleTo(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

  public double angleTo2D(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_angleTo2D(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

  public double angle() {
    return AlignmentAllJNI.AL_Vector3d_angle(swigCPtr, this);
  }

  public double angleCCWTo2D(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_angleCCWTo2D(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

  public void negate() {
    AlignmentAllJNI.AL_Vector3d_negate(swigCPtr, this);
  }

  public double length() {
    return AlignmentAllJNI.AL_Vector3d_length(swigCPtr, this);
  }

  public double lengthSq() {
    return AlignmentAllJNI.AL_Vector3d_lengthSq(swigCPtr, this);
  }

  public double length2D() {
    return AlignmentAllJNI.AL_Vector3d_length2D(swigCPtr, this);
  }

  public boolean isParallel(AL_Vector3d v, double dtol) {
    return AlignmentAllJNI.AL_Vector3d_isParallel__SWIG_0(swigCPtr, this, AL_Vector3d.getCPtr(v), v, dtol);
  }

  public boolean isParallel(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_isParallel__SWIG_1(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

  public boolean isParallel2D(AL_Vector3d v, double dtol) {
    return AlignmentAllJNI.AL_Vector3d_isParallel2D__SWIG_0(swigCPtr, this, AL_Vector3d.getCPtr(v), v, dtol);
  }

  public boolean isParallel2D(AL_Vector3d v) {
    return AlignmentAllJNI.AL_Vector3d_isParallel2D__SWIG_1(swigCPtr, this, AL_Vector3d.getCPtr(v), v);
  }

}
