/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALArc extends ALElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ALArc(long cPtr, boolean cMemoryOwn) {
    super(AlignmentAllJNI.ALArc_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALArc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AlignmentAllJNI.delete_ALArc(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ALArc() {
    this(AlignmentAllJNI.new_ALArc__SWIG_0(), true);
  }

  public ALArc(AL_Point3d stPt, AL_Vector3d stVec, double length, double stMileage, double radius, int dir, int number) {
    this(AlignmentAllJNI.new_ALArc__SWIG_1(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, length, stMileage, radius, dir, number), true);
  }

  public ALArc(AL_Point3d stPt, AL_Vector3d stVec, double length, double stMileage, double radius, int dir) {
    this(AlignmentAllJNI.new_ALArc__SWIG_2(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, length, stMileage, radius, dir), true);
  }

  public ALArc(AL_Point3d edPt, AL_Vector3d edVec, double length, double edMileage, int dir, double radius, int number) {
    this(AlignmentAllJNI.new_ALArc__SWIG_3(AL_Point3d.getCPtr(edPt), edPt, AL_Vector3d.getCPtr(edVec), edVec, length, edMileage, dir, radius, number), true);
  }

  public ALArc(AL_Point3d edPt, AL_Vector3d edVec, double length, double edMileage, int dir, double radius) {
    this(AlignmentAllJNI.new_ALArc__SWIG_4(AL_Point3d.getCPtr(edPt), edPt, AL_Vector3d.getCPtr(edVec), edVec, length, edMileage, dir, radius), true);
  }

  public ALArc(AL_Point3d stPt, AL_Point3d edPt, double stMileage, double radius, int dir, int number) {
    this(AlignmentAllJNI.new_ALArc__SWIG_5(AL_Point3d.getCPtr(stPt), stPt, AL_Point3d.getCPtr(edPt), edPt, stMileage, radius, dir, number), true);
  }

  public ALArc(AL_Point3d stPt, AL_Point3d edPt, double stMileage, double radius, int dir) {
    this(AlignmentAllJNI.new_ALArc__SWIG_6(AL_Point3d.getCPtr(stPt), stPt, AL_Point3d.getCPtr(edPt), edPt, stMileage, radius, dir), true);
  }

  public ALArc(AL_Point3d stPt, AL_Point3d edPt, double radius, int dir, int number) {
    this(AlignmentAllJNI.new_ALArc__SWIG_7(AL_Point3d.getCPtr(stPt), stPt, AL_Point3d.getCPtr(edPt), edPt, radius, dir, number), true);
  }

  public ALArc(AL_Point3d stPt, AL_Point3d edPt, double radius, int dir) {
    this(AlignmentAllJNI.new_ALArc__SWIG_8(AL_Point3d.getCPtr(stPt), stPt, AL_Point3d.getCPtr(edPt), edPt, radius, dir), true);
  }

  public boolean GetPointByRM(AL_Point3d pt, AL_Vector3d vec, double rm) {
    return AlignmentAllJNI.ALArc_GetPointByRM(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, AL_Vector3d.getCPtr(vec), vec, rm);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt, double dTol) {
    return AlignmentAllJNI.ALArc_GetPerPtByOutPoint__SWIG_0(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt, dTol);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt) {
    return AlignmentAllJNI.ALArc_GetPerPtByOutPoint__SWIG_1(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt);
  }

  public boolean GetRMByPoint(double[] rm, AL_Point3d pt) {
    return AlignmentAllJNI.ALArc_GetRMByPoint(swigCPtr, this, rm, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean GetHeightByRM(double[] height, double rm) {
    return AlignmentAllJNI.ALArc_GetHeightByRM(swigCPtr, this, height, rm);
  }

  public ALElement Clone() {
    long cPtr = AlignmentAllJNI.ALArc_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  public boolean GetRangePts(ALPoint3dArr offsetPts, ALVector3dArr vecs, double dMargin, double dStartMileage, double dEndMileage) {
    return AlignmentAllJNI.ALArc_GetRangePts(swigCPtr, this, ALPoint3dArr.getCPtr(offsetPts), offsetPts, ALVector3dArr.getCPtr(vecs), vecs, dMargin, dStartMileage, dEndMileage);
  }

}
