/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALChain {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ALChain(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALChain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ALChain obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ALChain(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ALChain() {
    this(AlignmentAllJNI.new_ALChain__SWIG_0(), true);
  }

  public ALChain(double dPreMileage, double dSubMileage, String strWord) {
    this(AlignmentAllJNI.new_ALChain__SWIG_1(dPreMileage, dSubMileage, strWord), true);
  }

  public void setM_PreMileage(double value) {
    AlignmentAllJNI.ALChain_m_PreMileage_set(swigCPtr, this, value);
  }

  public double getM_PreMileage() {
    return AlignmentAllJNI.ALChain_m_PreMileage_get(swigCPtr, this);
  }

  public void setM_SubMileage(double value) {
    AlignmentAllJNI.ALChain_m_SubMileage_set(swigCPtr, this, value);
  }

  public double getM_SubMileage() {
    return AlignmentAllJNI.ALChain_m_SubMileage_get(swigCPtr, this);
  }

  public void setM_Word(String value) {
    AlignmentAllJNI.ALChain_m_Word_set(swigCPtr, this, value);
  }

  public String getM_Word() {
    return AlignmentAllJNI.ALChain_m_Word_get(swigCPtr, this);
  }

}
