/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public final class ALDIR {
  public final static int AL_LEFT = -1;
  public final static int AL_CENTER = 0;
  public final static int AL_RIGHT = 1;
}

