/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public final class ALELETYPE {
  public final static int ELE_EDGE = 0;
  public final static int ELE_CURVE = 1;
  public final static int ELE_PRETRAN = 2;
  public final static int ELE_SUBTRAN = 3;
  public final static int ELE_NULL = 10;
}

