/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALElementPtrArr extends java.util.AbstractList<ALElement> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ALElementPtrArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALElementPtrArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ALElementPtrArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ALElementPtrArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ALElementPtrArr(ALElement[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ALElement element : initialElements) {
      add(element);
    }
  }

  public ALElementPtrArr(Iterable<ALElement> initialElements) {
    this();
    for (ALElement element : initialElements) {
      add(element);
    }
  }

  public ALElement get(int index) {
    return doGet(index);
  }

  public ALElement set(int index, ALElement e) {
    return doSet(index, e);
  }

  public boolean add(ALElement e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ALElement e) {
    modCount++;
    doAdd(index, e);
  }

  public ALElement remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public ALElementPtrArr() {
    this(AlignmentAllJNI.new_ALElementPtrArr__SWIG_0(), true);
  }

  public ALElementPtrArr(ALElementPtrArr other) {
    this(AlignmentAllJNI.new_ALElementPtrArr__SWIG_1(ALElementPtrArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.ALElementPtrArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.ALElementPtrArr_clear(swigCPtr, this);
  }

  public ALElementPtrArr(int count, ALElement value) {
    this(AlignmentAllJNI.new_ALElementPtrArr__SWIG_2(count, ALElement.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.ALElementPtrArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.ALElementPtrArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.ALElementPtrArr_doSize(swigCPtr, this);
  }

  private void doAdd(ALElement x) {
    AlignmentAllJNI.ALElementPtrArr_doAdd__SWIG_0(swigCPtr, this, ALElement.getCPtr(x), x);
  }

  private void doAdd(int index, ALElement x) {
    AlignmentAllJNI.ALElementPtrArr_doAdd__SWIG_1(swigCPtr, this, index, ALElement.getCPtr(x), x);
  }

  private ALElement doRemove(int index) {
    long cPtr = AlignmentAllJNI.ALElementPtrArr_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  private ALElement doGet(int index) {
    long cPtr = AlignmentAllJNI.ALElementPtrArr_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  private ALElement doSet(int index, ALElement val) {
    long cPtr = AlignmentAllJNI.ALElementPtrArr_doSet(swigCPtr, this, index, ALElement.getCPtr(val), val);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.ALElementPtrArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
