/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ALElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ALElement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_startPoint(AL_Point3d value) {
    AlignmentAllJNI.ALElement_m_startPoint_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_startPoint() {
    long cPtr = AlignmentAllJNI.ALElement_m_startPoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_startVector(AL_Vector3d value) {
    AlignmentAllJNI.ALElement_m_startVector_set(swigCPtr, this, AL_Vector3d.getCPtr(value), value);
  }

  public AL_Vector3d getM_startVector() {
    long cPtr = AlignmentAllJNI.ALElement_m_startVector_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Vector3d(cPtr, false);
  }

  public void setM_length(double value) {
    AlignmentAllJNI.ALElement_m_length_set(swigCPtr, this, value);
  }

  public double getM_length() {
    return AlignmentAllJNI.ALElement_m_length_get(swigCPtr, this);
  }

  public void setM_startMileage(double value) {
    AlignmentAllJNI.ALElement_m_startMileage_set(swigCPtr, this, value);
  }

  public double getM_startMileage() {
    return AlignmentAllJNI.ALElement_m_startMileage_get(swigCPtr, this);
  }

  public void setM_type(int value) {
    AlignmentAllJNI.ALElement_m_type_set(swigCPtr, this, value);
  }

  public int getM_type() {
    return AlignmentAllJNI.ALElement_m_type_get(swigCPtr, this);
  }

  public void setM_direction(int value) {
    AlignmentAllJNI.ALElement_m_direction_set(swigCPtr, this, value);
  }

  public int getM_direction() {
    return AlignmentAllJNI.ALElement_m_direction_get(swigCPtr, this);
  }

  public void setM_radius(double value) {
    AlignmentAllJNI.ALElement_m_radius_set(swigCPtr, this, value);
  }

  public double getM_radius() {
    return AlignmentAllJNI.ALElement_m_radius_get(swigCPtr, this);
  }

  public void setM_superEle(double value) {
    AlignmentAllJNI.ALElement_m_superEle_set(swigCPtr, this, value);
  }

  public double getM_superEle() {
    return AlignmentAllJNI.ALElement_m_superEle_get(swigCPtr, this);
  }

  public void setM_jdNumber(int value) {
    AlignmentAllJNI.ALElement_m_jdNumber_set(swigCPtr, this, value);
  }

  public int getM_jdNumber() {
    return AlignmentAllJNI.ALElement_m_jdNumber_get(swigCPtr, this);
  }

  public void setM_lenDiff(double value) {
    AlignmentAllJNI.ALElement_m_lenDiff_set(swigCPtr, this, value);
  }

  public double getM_lenDiff() {
    return AlignmentAllJNI.ALElement_m_lenDiff_get(swigCPtr, this);
  }

  public void setM_endPoint(AL_Point3d value) {
    AlignmentAllJNI.ALElement_m_endPoint_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_endPoint() {
    long cPtr = AlignmentAllJNI.ALElement_m_endPoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_endVector(AL_Vector3d value) {
    AlignmentAllJNI.ALElement_m_endVector_set(swigCPtr, this, AL_Vector3d.getCPtr(value), value);
  }

  public AL_Vector3d getM_endVector() {
    long cPtr = AlignmentAllJNI.ALElement_m_endVector_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Vector3d(cPtr, false);
  }

  public void setM_endMileage(double value) {
    AlignmentAllJNI.ALElement_m_endMileage_set(swigCPtr, this, value);
  }

  public double getM_endMileage() {
    return AlignmentAllJNI.ALElement_m_endMileage_get(swigCPtr, this);
  }

  public void SetJdNumber(int number) {
    AlignmentAllJNI.ALElement_SetJdNumber(swigCPtr, this, number);
  }

  public boolean GetPointByRM(AL_Point3d pt, AL_Vector3d vec, double rm) {
    return AlignmentAllJNI.ALElement_GetPointByRM(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, AL_Vector3d.getCPtr(vec), vec, rm);
  }

  public boolean GetRMByPoint(double[] rm, AL_Point3d pt) {
    return AlignmentAllJNI.ALElement_GetRMByPoint(swigCPtr, this, rm, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt, double dTol) {
    return AlignmentAllJNI.ALElement_GetPerPtByOutPoint__SWIG_0(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt, dTol);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt) {
    return AlignmentAllJNI.ALElement_GetPerPtByOutPoint__SWIG_1(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt);
  }

  public void CalDiff() {
    AlignmentAllJNI.ALElement_CalDiff(swigCPtr, this);
  }

  public boolean GetHeightByRM(double[] height, double rm) {
    return AlignmentAllJNI.ALElement_GetHeightByRM(swigCPtr, this, height, rm);
  }

  public ALElement Clone() {
    long cPtr = AlignmentAllJNI.ALElement_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  public boolean isInRange(double rm) {
    return AlignmentAllJNI.ALElement_isInRange(swigCPtr, this, rm);
  }

  public boolean GetRangePts(ALPoint3dArr offsetPts, ALVector3dArr vecs, double dMargin, double dStartMileage, double dEndMileage) {
    return AlignmentAllJNI.ALElement_GetRangePts(swigCPtr, this, ALPoint3dArr.getCPtr(offsetPts), offsetPts, ALVector3dArr.getCPtr(vecs), vecs, dMargin, dStartMileage, dEndMileage);
  }

  public boolean IntersectWithLine(AL_Point3d linePt, AL_Vector3d lineVec, ALPoint3dArr interPts) {
    return AlignmentAllJNI.ALElement_IntersectWithLine(swigCPtr, this, AL_Point3d.getCPtr(linePt), linePt, AL_Vector3d.getCPtr(lineVec), lineVec, ALPoint3dArr.getCPtr(interPts), interPts);
  }

  public static ALElement Create(AL_Point3d stPt, AL_Vector3d stVec, double dLen, double dStLc, int type, int dir, double dRadius, double dSuperEle, int jdNumber, double dLendiff, double secondRadius) {
    long cPtr = AlignmentAllJNI.ALElement_Create__SWIG_0(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, dLen, dStLc, type, dir, dRadius, dSuperEle, jdNumber, dLendiff, secondRadius);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  public static ALElement Create(AL_Point3d stPt, AL_Vector3d stVec, double dLen, double dStLc, int type, int dir, double dRadius, double dSuperEle, int jdNumber, double dLendiff) {
    long cPtr = AlignmentAllJNI.ALElement_Create__SWIG_1(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, dLen, dStLc, type, dir, dRadius, dSuperEle, jdNumber, dLendiff);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

}
