/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALGradeChangePoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ALGradeChangePoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALGradeChangePoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ALGradeChangePoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ALGradeChangePoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ALGradeChangePoint() {
    this(AlignmentAllJNI.new_ALGradeChangePoint__SWIG_0(), true);
  }

  public ALGradeChangePoint(double dMileage, double dHeight, double dRadius) {
    this(AlignmentAllJNI.new_ALGradeChangePoint__SWIG_1(dMileage, dHeight, dRadius), true);
  }

  public ALGradeChangePoint(double dMileage, double dSlopeLen, double dGradient, double dRadius) {
    this(AlignmentAllJNI.new_ALGradeChangePoint__SWIG_2(dMileage, dSlopeLen, dGradient, dRadius), true);
  }

  public static void CalVertPara(ALGradeChangePoint pt1, ALGradeChangePoint pt2, SWIGTYPE_p_double dT, double[] dE) {
    AlignmentAllJNI.ALGradeChangePoint_CalVertPara(ALGradeChangePoint.getCPtr(pt1), pt1, ALGradeChangePoint.getCPtr(pt2), pt2, SWIGTYPE_p_double.getCPtr(dT), dE);
  }

  public void Offset(double dDis) {
    AlignmentAllJNI.ALGradeChangePoint_Offset(swigCPtr, this, dDis);
  }

  public void setM_RealMilage(double value) {
    AlignmentAllJNI.ALGradeChangePoint_m_RealMilage_set(swigCPtr, this, value);
  }

  public double getM_RealMilage() {
    return AlignmentAllJNI.ALGradeChangePoint_m_RealMilage_get(swigCPtr, this);
  }

  public void setM_Height(double value) {
    AlignmentAllJNI.ALGradeChangePoint_m_Height_set(swigCPtr, this, value);
  }

  public double getM_Height() {
    return AlignmentAllJNI.ALGradeChangePoint_m_Height_get(swigCPtr, this);
  }

  public void setM_Radius(double value) {
    AlignmentAllJNI.ALGradeChangePoint_m_Radius_set(swigCPtr, this, value);
  }

  public double getM_Radius() {
    return AlignmentAllJNI.ALGradeChangePoint_m_Radius_get(swigCPtr, this);
  }

  public void setM_SlopeLength(double value) {
    AlignmentAllJNI.ALGradeChangePoint_m_SlopeLength_set(swigCPtr, this, value);
  }

  public double getM_SlopeLength() {
    return AlignmentAllJNI.ALGradeChangePoint_m_SlopeLength_get(swigCPtr, this);
  }

  public void setM_Gradient(double value) {
    AlignmentAllJNI.ALGradeChangePoint_m_Gradient_set(swigCPtr, this, value);
  }

  public double getM_Gradient() {
    return AlignmentAllJNI.ALGradeChangePoint_m_Gradient_get(swigCPtr, this);
  }

  public void setM_dir(int value) {
    AlignmentAllJNI.ALGradeChangePoint_m_dir_set(swigCPtr, this, value);
  }

  public int getM_dir() {
    return AlignmentAllJNI.ALGradeChangePoint_m_dir_get(swigCPtr, this);
  }

  public void setM_ZYpt(AL_Point3d value) {
    AlignmentAllJNI.ALGradeChangePoint_m_ZYpt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_ZYpt() {
    long cPtr = AlignmentAllJNI.ALGradeChangePoint_m_ZYpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_YZpt(AL_Point3d value) {
    AlignmentAllJNI.ALGradeChangePoint_m_YZpt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_YZpt() {
    long cPtr = AlignmentAllJNI.ALGradeChangePoint_m_YZpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_cenPt(AL_Point3d value) {
    AlignmentAllJNI.ALGradeChangePoint_m_cenPt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_cenPt() {
    long cPtr = AlignmentAllJNI.ALGradeChangePoint_m_cenPt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_tanLen(double value) {
    AlignmentAllJNI.ALGradeChangePoint_m_tanLen_set(swigCPtr, this, value);
  }

  public double getM_tanLen() {
    return AlignmentAllJNI.ALGradeChangePoint_m_tanLen_get(swigCPtr, this);
  }

  public void setM_E0(double value) {
    AlignmentAllJNI.ALGradeChangePoint_m_E0_set(swigCPtr, this, value);
  }

  public double getM_E0() {
    return AlignmentAllJNI.ALGradeChangePoint_m_E0_get(swigCPtr, this);
  }

  public void setM_bOverlaped(boolean value) {
    AlignmentAllJNI.ALGradeChangePoint_m_bOverlaped_set(swigCPtr, this, value);
  }

  public boolean getM_bOverlaped() {
    return AlignmentAllJNI.ALGradeChangePoint_m_bOverlaped_get(swigCPtr, this);
  }

}
