/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class AlignmentFittingUndoManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AlignmentFittingUndoManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AlignmentFittingUndoManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AlignmentFittingUndoManager obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_AlignmentFittingUndoManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AlignmentFittingUndoManager(long maxHistorySize, long maxMemoryMB) {
    this(AlignmentAllJNI.new_AlignmentFittingUndoManager__SWIG_0(maxHistorySize, maxMemoryMB), true);
  }

  public AlignmentFittingUndoManager(long maxHistorySize) {
    this(AlignmentAllJNI.new_AlignmentFittingUndoManager__SWIG_1(maxHistorySize), true);
  }

  public AlignmentFittingUndoManager() {
    this(AlignmentAllJNI.new_AlignmentFittingUndoManager__SWIG_2(), true);
  }

  public void BindFitting(AlignmentFitting fitting) {
    AlignmentAllJNI.AlignmentFittingUndoManager_BindFitting(swigCPtr, this, AlignmentFitting.getCPtr(fitting), fitting);
  }

  public void SaveSnapshot(String description) {
    AlignmentAllJNI.AlignmentFittingUndoManager_SaveSnapshot__SWIG_0(swigCPtr, this, description);
  }

  public void SaveSnapshot() {
    AlignmentAllJNI.AlignmentFittingUndoManager_SaveSnapshot__SWIG_1(swigCPtr, this);
  }

  public boolean Undo() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_Undo(swigCPtr, this);
  }

  public boolean Redo() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_Redo(swigCPtr, this);
  }

  public void Clear() {
    AlignmentAllJNI.AlignmentFittingUndoManager_Clear(swigCPtr, this);
  }

  public boolean RollbackTo(String description) {
    return AlignmentAllJNI.AlignmentFittingUndoManager_RollbackTo(swigCPtr, this, description);
  }

  public boolean CanUndo() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_CanUndo(swigCPtr, this);
  }

  public boolean CanRedo() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_CanRedo(swigCPtr, this);
  }

  public long GetUndoCount() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_GetUndoCount(swigCPtr, this);
  }

  public long GetRedoCount() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_GetRedoCount(swigCPtr, this);
  }

  public long GetMemoryUsage() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_GetMemoryUsage(swigCPtr, this);
  }

  public String GetNextUndoDescription() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_GetNextUndoDescription(swigCPtr, this);
  }

  public String GetNextRedoDescription() {
    return AlignmentAllJNI.AlignmentFittingUndoManager_GetNextRedoDescription(swigCPtr, this);
  }

  public void RemoveSnapshots(int start, int end) {
    AlignmentAllJNI.AlignmentFittingUndoManager_RemoveSnapshots(swigCPtr, this, start, end);
  }

}
