/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class AlignmentFitting {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AlignmentFitting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AlignmentFitting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AlignmentFitting obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_AlignmentFitting(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AlignmentFitting(SingleAlignmentBase pLine, SurveyDatas pSurveyDatas) {
    this(AlignmentAllJNI.new_AlignmentFitting(SingleAlignmentBase.getCPtr(pLine), pLine, SurveyDatas.getCPtr(pSurveyDatas), pSurveyDatas), true);
  }

  public void SetAlignment(SingleAlignmentBase pLine) {
    AlignmentAllJNI.AlignmentFitting_SetAlignment(swigCPtr, this, SingleAlignmentBase.getCPtr(pLine), pLine);
  }

  public SingleAlignmentBase GetAlignment() {
    long cPtr = AlignmentAllJNI.AlignmentFitting_GetAlignment(swigCPtr, this);
    return (cPtr == 0) ? null : new SingleAlignmentBase(cPtr, true);
  }

  public void SetSurveyDatas(SurveyDatas pSurveyDatas) {
    AlignmentAllJNI.AlignmentFitting_SetSurveyDatas(swigCPtr, this, SurveyDatas.getCPtr(pSurveyDatas), pSurveyDatas);
  }

  public SurveyDatas GetSurveyDatas() {
    long cPtr = AlignmentAllJNI.AlignmentFitting_GetSurveyDatas(swigCPtr, this);
    return (cPtr == 0) ? null : new SurveyDatas(cPtr, true);
  }

  public boolean FittingHori_Init(boolean isBest) {
    return AlignmentAllJNI.AlignmentFitting_FittingHori_Init__SWIG_0(swigCPtr, this, isBest);
  }

  public boolean FittingHori_Init() {
    return AlignmentAllJNI.AlignmentFitting_FittingHori_Init__SWIG_1(swigCPtr, this);
  }

  public boolean FittingHori_BestFit() {
    return AlignmentAllJNI.AlignmentFitting_FittingHori_BestFit(swigCPtr, this);
  }

  public boolean FittingHori_BestFitByConfig(InterPtArr curInterPts, FittingModeArr types) {
    return AlignmentAllJNI.AlignmentFitting_FittingHori_BestFitByConfig(swigCPtr, this, InterPtArr.getCPtr(curInterPts), curInterPts, FittingModeArr.getCPtr(types), types);
  }

  public boolean CalHoriMargin(boolean isCorrectLine) {
    return AlignmentAllJNI.AlignmentFitting_CalHoriMargin__SWIG_0(swigCPtr, this, isCorrectLine);
  }

  public boolean CalHoriMargin() {
    return AlignmentAllJNI.AlignmentFitting_CalHoriMargin__SWIG_1(swigCPtr, this);
  }

  public StaticsDataHori GetStaticsDataHori() {
    return new StaticsDataHori(AlignmentAllJNI.AlignmentFitting_GetStaticsDataHori(swigCPtr, this), true);
  }

  public boolean RelocateSpecialPt() {
    return AlignmentAllJNI.AlignmentFitting_RelocateSpecialPt(swigCPtr, this);
  }

  public boolean FittingHori_byManual(boolean isbest) {
    return AlignmentAllJNI.AlignmentFitting_FittingHori_byManual__SWIG_0(swigCPtr, this, isbest);
  }

  public boolean FittingHori_byManual() {
    return AlignmentAllJNI.AlignmentFitting_FittingHori_byManual__SWIG_1(swigCPtr, this);
  }

  public boolean InsertInterPtsForMultiLine(int nInterIndex, InterPtArr intertPts, ALPoint3dArr linePts, ALVector3dArr lineVecs) {
    return AlignmentAllJNI.AlignmentFitting_InsertInterPtsForMultiLine(swigCPtr, this, nInterIndex, InterPtArr.getCPtr(intertPts), intertPts, ALPoint3dArr.getCPtr(linePts), linePts, ALVector3dArr.getCPtr(lineVecs), lineVecs);
  }

  public boolean GetSurveyPointsByRange(SurveyVector datas, double stRealLc, double enRealLc) {
    return AlignmentAllJNI.AlignmentFitting_GetSurveyPointsByRange(swigCPtr, this, SurveyVector.getCPtr(datas), datas, stRealLc, enRealLc);
  }

  public boolean RotateLine(int nIndex, double dAngle, boolean isFixedFront) {
    return AlignmentAllJNI.AlignmentFitting_RotateLine(swigCPtr, this, nIndex, dAngle, isFixedFront);
  }

  public boolean RotateLineByFixedPoint(int nIndex, double dMargin, boolean isFixedFront) {
    return AlignmentAllJNI.AlignmentFitting_RotateLineByFixedPoint(swigCPtr, this, nIndex, dMargin, isFixedFront);
  }

  public boolean InitMultiLine(int nIndex) {
    return AlignmentAllJNI.AlignmentFitting_InitMultiLine(swigCPtr, this, nIndex);
  }

  public boolean UpDataHoriLineByMultiLine() {
    return AlignmentAllJNI.AlignmentFitting_UpDataHoriLineByMultiLine(swigCPtr, this);
  }

  public CMultiLine GetMultiLine() {
    long cPtr = AlignmentAllJNI.AlignmentFitting_GetMultiLine(swigCPtr, this);
    return (cPtr == 0) ? null : new CMultiLine(cPtr, true);
  }

  public boolean InitCurveDesigner(int nStInterPtIndex, int nEndInterPtIndex, boolean bSpecialize) {
    return AlignmentAllJNI.AlignmentFitting_InitCurveDesigner__SWIG_0(swigCPtr, this, nStInterPtIndex, nEndInterPtIndex, bSpecialize);
  }

  public boolean InitCurveDesigner(int nStInterPtIndex, int nEndInterPtIndex) {
    return AlignmentAllJNI.AlignmentFitting_InitCurveDesigner__SWIG_1(swigCPtr, this, nStInterPtIndex, nEndInterPtIndex);
  }

  public ComCurveDesigner GetCurveDesigner() {
    long cPtr = AlignmentAllJNI.AlignmentFitting_GetCurveDesigner(swigCPtr, this);
    return (cPtr == 0) ? null : new ComCurveDesigner(cPtr, true);
  }

  public boolean UpdataHoriLineByCurveDesigner() {
    return AlignmentAllJNI.AlignmentFitting_UpdataHoriLineByCurveDesigner(swigCPtr, this);
  }

  public boolean FittingVert_Init() {
    return AlignmentAllJNI.AlignmentFitting_FittingVert_Init(swigCPtr, this);
  }

  public boolean CalVertMargin(boolean isStatic, int type) {
    return AlignmentAllJNI.AlignmentFitting_CalVertMargin__SWIG_0(swigCPtr, this, isStatic, type);
  }

  public boolean CalVertMargin(boolean isStatic) {
    return AlignmentAllJNI.AlignmentFitting_CalVertMargin__SWIG_1(swigCPtr, this, isStatic);
  }

  public boolean CalVertMargin() {
    return AlignmentAllJNI.AlignmentFitting_CalVertMargin__SWIG_2(swigCPtr, this);
  }

  public void CalSuperEle() {
    AlignmentAllJNI.AlignmentFitting_CalSuperEle(swigCPtr, this);
  }

  public StaticsDataVert GetStaticsDataVert() {
    return new StaticsDataVert(AlignmentAllJNI.AlignmentFitting_GetStaticsDataVert(swigCPtr, this), true);
  }

  public void ReCalMileage() {
    AlignmentAllJNI.AlignmentFitting_ReCalMileage(swigCPtr, this);
  }

  public boolean AutoFitVertRadius() {
    return AlignmentAllJNI.AlignmentFitting_AutoFitVertRadius__SWIG_0(swigCPtr, this);
  }

  public boolean AutoFitVertRadius(int nIndex) {
    return AlignmentAllJNI.AlignmentFitting_AutoFitVertRadius__SWIG_1(swigCPtr, this, nIndex);
  }

  public SurveyParaHori GetParaHori() {
    return new SurveyParaHori(AlignmentAllJNI.AlignmentFitting_GetParaHori(swigCPtr, this), true);
  }

  public void SetParaHori(SurveyParaHori para) {
    AlignmentAllJNI.AlignmentFitting_SetParaHori(swigCPtr, this, SurveyParaHori.getCPtr(para), para);
  }

  public SurveyParaVert GetParaVert() {
    return new SurveyParaVert(AlignmentAllJNI.AlignmentFitting_GetParaVert(swigCPtr, this), true);
  }

  public void SetParaVert(SurveyParaVert para) {
    AlignmentAllJNI.AlignmentFitting_SetParaVert(swigCPtr, this, SurveyParaVert.getCPtr(para), para);
  }

}
