/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class AlignmentCoreJava {
  public static double getALTOL() {
    return AlignmentAllJNI.ALTOL_get();
  }

  public static double getAL_PI() {
    return AlignmentAllJNI.AL_PI_get();
  }

  public static AL_Point3d VectorToPoint(AL_Vector3d vec) {
    return new AL_Point3d(AlignmentAllJNI.VectorToPoint(AL_Vector3d.getCPtr(vec), vec), true);
  }

  public static double getMAX_RADIUS() {
    return AlignmentAllJNI.MAX_RADIUS_get();
  }

}
