/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class AlignmentManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AlignmentManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AlignmentManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AlignmentManager obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public static AlignmentManager GetInstance() {
    long cPtr = AlignmentAllJNI.AlignmentManager_GetInstance();
    return (cPtr == 0) ? null : new AlignmentManager(cPtr, false);
  }

  public boolean RegisterAlignment(SingleAlignmentBase line) {
    return AlignmentAllJNI.AlignmentManager_RegisterAlignment(swigCPtr, this, SingleAlignmentBase.getCPtr(line), line);
  }

  public boolean GetAlignment(String alignmentName, SWIGTYPE_p_p_AlignmentCore__SingleAlignmentBase line) {
    return AlignmentAllJNI.AlignmentManager_GetAlignment(swigCPtr, this, alignmentName, SWIGTYPE_p_p_AlignmentCore__SingleAlignmentBase.getCPtr(line));
  }

}
