/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALIntersectionPoint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ALIntersectionPoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALIntersectionPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ALIntersectionPoint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ALIntersectionPoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ALIntersectionPoint() {
    this(AlignmentAllJNI.new_ALIntersectionPoint__SWIG_0(), true);
  }

  public ALIntersectionPoint(AL_Point3d pt, double dRadius, double dPreL, double dSubL) {
    this(AlignmentAllJNI.new_ALIntersectionPoint__SWIG_1(AL_Point3d.getCPtr(pt), pt, dRadius, dPreL, dSubL), true);
  }

  public static boolean CalculateIntersectionPoint(ALElementPtrArr eles, ALIntersectionPoint stPt, ALIntersectionPoint interPt, ALIntersectionPoint endpt, int nIndex, boolean plusLastLine) {
    return AlignmentAllJNI.ALIntersectionPoint_CalculateIntersectionPoint__SWIG_0(ALElementPtrArr.getCPtr(eles), eles, ALIntersectionPoint.getCPtr(stPt), stPt, ALIntersectionPoint.getCPtr(interPt), interPt, ALIntersectionPoint.getCPtr(endpt), endpt, nIndex, plusLastLine);
  }

  public static boolean CalculateIntersectionPoint(ALElementPtrArr eles, ALIntersectionPoint stPt, ALIntersectionPoint interPt, ALIntersectionPoint endpt, int nIndex) {
    return AlignmentAllJNI.ALIntersectionPoint_CalculateIntersectionPoint__SWIG_1(ALElementPtrArr.getCPtr(eles), eles, ALIntersectionPoint.getCPtr(stPt), stPt, ALIntersectionPoint.getCPtr(interPt), interPt, ALIntersectionPoint.getCPtr(endpt), endpt, nIndex);
  }

  public void Uniform(AL_Point3d pt, double realMl, AL_Vector3d vec) {
    AlignmentAllJNI.ALIntersectionPoint_Uniform(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, realMl, AL_Vector3d.getCPtr(vec), vec);
  }

  public ALEvaluationVector SuperCheck(SuperCheckData checkRes) {
    return new ALEvaluationVector(AlignmentAllJNI.ALIntersectionPoint_SuperCheck(swigCPtr, this, SuperCheckData.getCPtr(checkRes), checkRes), true);
  }

  public void SetSuperEleByRelease() {
    AlignmentAllJNI.ALIntersectionPoint_SetSuperEleByRelease(swigCPtr, this);
  }

  public void SetSuperEleData(ALIntersectionPoint interPt) {
    AlignmentAllJNI.ALIntersectionPoint_SetSuperEleData(swigCPtr, this, ALIntersectionPoint.getCPtr(interPt), interPt);
  }

  public double GetAngle() {
    return AlignmentAllJNI.ALIntersectionPoint_GetAngle(swigCPtr, this);
  }

  public void GetTLen(SWIGTYPE_p_double preLen, SWIGTYPE_p_double subLen) {
    AlignmentAllJNI.ALIntersectionPoint_GetTLen(swigCPtr, this, SWIGTYPE_p_double.getCPtr(preLen), SWIGTYPE_p_double.getCPtr(subLen));
  }

  public void ModifyParaByComCurve(ALIntersectionPoint interPt, boolean isFront) {
    AlignmentAllJNI.ALIntersectionPoint_ModifyParaByComCurve(swigCPtr, this, ALIntersectionPoint.getCPtr(interPt), interPt, isFront);
  }

  public void ModifyMLByAdd(double dMl) {
    AlignmentAllJNI.ALIntersectionPoint_ModifyMLByAdd(swigCPtr, this, dMl);
  }

  public double GetPreTan() {
    return AlignmentAllJNI.ALIntersectionPoint_GetPreTan(swigCPtr, this);
  }

  public double GetSubTan() {
    return AlignmentAllJNI.ALIntersectionPoint_GetSubTan(swigCPtr, this);
  }

  public void setM_Point(AL_Point3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Point_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Point() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_Point_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_Radius(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Radius_set(swigCPtr, this, value);
  }

  public double getM_Radius() {
    return AlignmentAllJNI.ALIntersectionPoint_m_Radius_get(swigCPtr, this);
  }

  public void setM_PreLen(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_PreLen_set(swigCPtr, this, value);
  }

  public double getM_PreLen() {
    return AlignmentAllJNI.ALIntersectionPoint_m_PreLen_get(swigCPtr, this);
  }

  public void setM_SubLen(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_SubLen_set(swigCPtr, this, value);
  }

  public double getM_SubLen() {
    return AlignmentAllJNI.ALIntersectionPoint_m_SubLen_get(swigCPtr, this);
  }

  public void setM_Dir(int value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Dir_set(swigCPtr, this, value);
  }

  public int getM_Dir() {
    return AlignmentAllJNI.ALIntersectionPoint_m_Dir_get(swigCPtr, this);
  }

  public void setM_CenterPoint(AL_Point3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_CenterPoint_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_CenterPoint() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_CenterPoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_ZHml(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_ZHml_set(swigCPtr, this, value);
  }

  public double getM_ZHml() {
    return AlignmentAllJNI.ALIntersectionPoint_m_ZHml_get(swigCPtr, this);
  }

  public void setM_HZml(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_HZml_set(swigCPtr, this, value);
  }

  public double getM_HZml() {
    return AlignmentAllJNI.ALIntersectionPoint_m_HZml_get(swigCPtr, this);
  }

  public void setM_HYml(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_HYml_set(swigCPtr, this, value);
  }

  public double getM_HYml() {
    return AlignmentAllJNI.ALIntersectionPoint_m_HYml_get(swigCPtr, this);
  }

  public void setM_YHml(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_YHml_set(swigCPtr, this, value);
  }

  public double getM_YHml() {
    return AlignmentAllJNI.ALIntersectionPoint_m_YHml_get(swigCPtr, this);
  }

  public void setM_ZHpt(AL_Point3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_ZHpt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_ZHpt() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_ZHpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_HZpt(AL_Point3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_HZpt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_HZpt() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_HZpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_HYpt(AL_Point3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_HYpt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_HYpt() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_HYpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_YHpt(AL_Point3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_YHpt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_YHpt() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_YHpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_ZHvec(AL_Vector3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_ZHvec_set(swigCPtr, this, AL_Vector3d.getCPtr(value), value);
  }

  public AL_Vector3d getM_ZHvec() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_ZHvec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Vector3d(cPtr, false);
  }

  public void setM_HZvec(AL_Vector3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_HZvec_set(swigCPtr, this, AL_Vector3d.getCPtr(value), value);
  }

  public AL_Vector3d getM_HZvec() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_HZvec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Vector3d(cPtr, false);
  }

  public void setM_HYvec(AL_Vector3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_HYvec_set(swigCPtr, this, AL_Vector3d.getCPtr(value), value);
  }

  public AL_Vector3d getM_HYvec() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_HYvec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Vector3d(cPtr, false);
  }

  public void setM_YHvec(AL_Vector3d value) {
    AlignmentAllJNI.ALIntersectionPoint_m_YHvec_set(swigCPtr, this, AL_Vector3d.getCPtr(value), value);
  }

  public AL_Vector3d getM_YHvec() {
    long cPtr = AlignmentAllJNI.ALIntersectionPoint_m_YHvec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Vector3d(cPtr, false);
  }

  public void setM_Number(int value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Number_set(swigCPtr, this, value);
  }

  public int getM_Number() {
    return AlignmentAllJNI.ALIntersectionPoint_m_Number_get(swigCPtr, this);
  }

  public void setM_Name(String value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Name_set(swigCPtr, this, value);
  }

  public String getM_Name() {
    return AlignmentAllJNI.ALIntersectionPoint_m_Name_get(swigCPtr, this);
  }

  public void setM_SuperEle(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_SuperEle_set(swigCPtr, this, value);
  }

  public double getM_SuperEle() {
    return AlignmentAllJNI.ALIntersectionPoint_m_SuperEle_get(swigCPtr, this);
  }

  public void setM_SE_preLen(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_SE_preLen_set(swigCPtr, this, value);
  }

  public double getM_SE_preLen() {
    return AlignmentAllJNI.ALIntersectionPoint_m_SE_preLen_get(swigCPtr, this);
  }

  public void setM_SE_subLen(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_SE_subLen_set(swigCPtr, this, value);
  }

  public double getM_SE_subLen() {
    return AlignmentAllJNI.ALIntersectionPoint_m_SE_subLen_get(swigCPtr, this);
  }

  public void setM_ZH_Offset(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_ZH_Offset_set(swigCPtr, this, value);
  }

  public double getM_ZH_Offset() {
    return AlignmentAllJNI.ALIntersectionPoint_m_ZH_Offset_get(swigCPtr, this);
  }

  public void setM_HZ_Offset(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_HZ_Offset_set(swigCPtr, this, value);
  }

  public double getM_HZ_Offset() {
    return AlignmentAllJNI.ALIntersectionPoint_m_HZ_Offset_get(swigCPtr, this);
  }

  public void setM_E(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_E_set(swigCPtr, this, value);
  }

  public double getM_E() {
    return AlignmentAllJNI.ALIntersectionPoint_m_E_get(swigCPtr, this);
  }

  public void setM_Speed_Limited(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Speed_Limited_set(swigCPtr, this, value);
  }

  public double getM_Speed_Limited() {
    return AlignmentAllJNI.ALIntersectionPoint_m_Speed_Limited_get(swigCPtr, this);
  }

  public void setM_Speed_Cargo(double value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Speed_Cargo_set(swigCPtr, this, value);
  }

  public double getM_Speed_Cargo() {
    return AlignmentAllJNI.ALIntersectionPoint_m_Speed_Cargo_get(swigCPtr, this);
  }

  public void setM_Type(int value) {
    AlignmentAllJNI.ALIntersectionPoint_m_Type_set(swigCPtr, this, value);
  }

  public int getM_Type() {
    return AlignmentAllJNI.ALIntersectionPoint_m_Type_get(swigCPtr, this);
  }

}
