/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALLine extends ALElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ALLine(long cPtr, boolean cMemoryOwn) {
    super(AlignmentAllJNI.ALLine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALLine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AlignmentAllJNI.delete_ALLine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ALLine() {
    this(AlignmentAllJNI.new_ALLine__SWIG_0(), true);
  }

  public ALLine(AL_Point3d stPt, AL_Vector3d stVec, double length, double stMileage, int nInterIndex) {
    this(AlignmentAllJNI.new_ALLine__SWIG_1(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, length, stMileage, nInterIndex), true);
  }

  public ALLine(AL_Point3d stPt, AL_Point3d edPt, double stMileage, int nInterIndex) {
    this(AlignmentAllJNI.new_ALLine__SWIG_2(AL_Point3d.getCPtr(stPt), stPt, AL_Point3d.getCPtr(edPt), edPt, stMileage, nInterIndex), true);
  }

  public boolean GetPointByRM(AL_Point3d pt, AL_Vector3d vec, double rm) {
    return AlignmentAllJNI.ALLine_GetPointByRM(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, AL_Vector3d.getCPtr(vec), vec, rm);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt, double dTol) {
    return AlignmentAllJNI.ALLine_GetPerPtByOutPoint__SWIG_0(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt, dTol);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt) {
    return AlignmentAllJNI.ALLine_GetPerPtByOutPoint__SWIG_1(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt);
  }

  public boolean GetRMByPoint(double[] rm, AL_Point3d pt) {
    return AlignmentAllJNI.ALLine_GetRMByPoint(swigCPtr, this, rm, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean GetHeightByRM(double[] height, double rm) {
    return AlignmentAllJNI.ALLine_GetHeightByRM(swigCPtr, this, height, rm);
  }

  public ALElement Clone() {
    long cPtr = AlignmentAllJNI.ALLine_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  public boolean GetRangePts(ALPoint3dArr offsetPts, ALVector3dArr vecs, double dMargin, double dStartMileage, double dEndMileage) {
    return AlignmentAllJNI.ALLine_GetRangePts(swigCPtr, this, ALPoint3dArr.getCPtr(offsetPts), offsetPts, ALVector3dArr.getCPtr(vecs), vecs, dMargin, dStartMileage, dEndMileage);
  }

}
