/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public final class ALMARKSIDE {
  public final static int MARK_LEFT = -1;
  public final static int MARK_RIGHT = 1;
}

