/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALPoint3dArr extends java.util.AbstractList<AL_Point3d> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ALPoint3dArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALPoint3dArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ALPoint3dArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ALPoint3dArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ALPoint3dArr(AL_Point3d[] initialElements) {
    this();
    reserve(initialElements.length);

    for (AL_Point3d element : initialElements) {
      add(element);
    }
  }

  public ALPoint3dArr(Iterable<AL_Point3d> initialElements) {
    this();
    for (AL_Point3d element : initialElements) {
      add(element);
    }
  }

  public AL_Point3d get(int index) {
    return doGet(index);
  }

  public AL_Point3d set(int index, AL_Point3d e) {
    return doSet(index, e);
  }

  public boolean add(AL_Point3d e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, AL_Point3d e) {
    modCount++;
    doAdd(index, e);
  }

  public AL_Point3d remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public ALPoint3dArr() {
    this(AlignmentAllJNI.new_ALPoint3dArr__SWIG_0(), true);
  }

  public ALPoint3dArr(ALPoint3dArr other) {
    this(AlignmentAllJNI.new_ALPoint3dArr__SWIG_1(ALPoint3dArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.ALPoint3dArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.ALPoint3dArr_clear(swigCPtr, this);
  }

  public ALPoint3dArr(int count, AL_Point3d value) {
    this(AlignmentAllJNI.new_ALPoint3dArr__SWIG_2(count, AL_Point3d.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.ALPoint3dArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.ALPoint3dArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.ALPoint3dArr_doSize(swigCPtr, this);
  }

  private void doAdd(AL_Point3d x) {
    AlignmentAllJNI.ALPoint3dArr_doAdd__SWIG_0(swigCPtr, this, AL_Point3d.getCPtr(x), x);
  }

  private void doAdd(int index, AL_Point3d x) {
    AlignmentAllJNI.ALPoint3dArr_doAdd__SWIG_1(swigCPtr, this, index, AL_Point3d.getCPtr(x), x);
  }

  private AL_Point3d doRemove(int index) {
    return new AL_Point3d(AlignmentAllJNI.ALPoint3dArr_doRemove(swigCPtr, this, index), true);
  }

  private AL_Point3d doGet(int index) {
    return new AL_Point3d(AlignmentAllJNI.ALPoint3dArr_doGet(swigCPtr, this, index), false);
  }

  private AL_Point3d doSet(int index, AL_Point3d val) {
    return new AL_Point3d(AlignmentAllJNI.ALPoint3dArr_doSet(swigCPtr, this, index, AL_Point3d.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.ALPoint3dArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
