/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ALRelease extends ALElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ALRelease(long cPtr, boolean cMemoryOwn) {
    super(AlignmentAllJNI.ALRelease_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ALRelease obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AlignmentAllJNI.delete_ALRelease(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ALRelease() {
    this(AlignmentAllJNI.new_ALRelease__SWIG_0(), true);
  }

  public ALRelease(AL_Point3d stPt, AL_Vector3d stVec, double dLength, double stMileage, double radius1, double radius2, int dir, int nIndex) {
    this(AlignmentAllJNI.new_ALRelease__SWIG_1(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, dLength, stMileage, radius1, radius2, dir, nIndex), true);
  }

  public ALRelease(AL_Point3d stPt, AL_Vector3d stVec, double dLength, double stMileage, double radius1, double radius2, int dir) {
    this(AlignmentAllJNI.new_ALRelease__SWIG_2(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, dLength, stMileage, radius1, radius2, dir), true);
  }

  public ALRelease(AL_Point3d stPt, AL_Vector3d stVec, double dLength, double edMileage, double radius, int type, int dir, int nIndex) {
    this(AlignmentAllJNI.new_ALRelease__SWIG_3(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, dLength, edMileage, radius, type, dir, nIndex), true);
  }

  public ALRelease(AL_Point3d stPt, AL_Vector3d stVec, double dLength, double edMileage, double radius, int type, int dir) {
    this(AlignmentAllJNI.new_ALRelease__SWIG_4(AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, dLength, edMileage, radius, type, dir), true);
  }

  public void SetCompDataPara(double startRadius) {
    AlignmentAllJNI.ALRelease_SetCompDataPara(swigCPtr, this, startRadius);
  }

  public boolean GetPointByRM(AL_Point3d pt, AL_Vector3d vec, double rm) {
    return AlignmentAllJNI.ALRelease_GetPointByRM(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, AL_Vector3d.getCPtr(vec), vec, rm);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt, double dTol) {
    return AlignmentAllJNI.ALRelease_GetPerPtByOutPoint__SWIG_0(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt, dTol);
  }

  public boolean GetPerPtByOutPoint(double[] rm, AL_Point3d perPt, AL_Vector3d tanVec, double[] dDis, AL_Point3d outPt) {
    return AlignmentAllJNI.ALRelease_GetPerPtByOutPoint__SWIG_1(swigCPtr, this, rm, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, dDis, AL_Point3d.getCPtr(outPt), outPt);
  }

  public boolean GetRMByPoint(double[] rm, AL_Point3d pt) {
    return AlignmentAllJNI.ALRelease_GetRMByPoint(swigCPtr, this, rm, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean GetHeightByRM(double[] height, double rm) {
    return AlignmentAllJNI.ALRelease_GetHeightByRM(swigCPtr, this, height, rm);
  }

  public ALElement Clone() {
    long cPtr = AlignmentAllJNI.ALRelease_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ALElement(cPtr, true);
  }

  public boolean GetRangePts(ALPoint3dArr offsetPts, ALVector3dArr vecs, double dMargin, double dStartMileage, double dEndMileage) {
    return AlignmentAllJNI.ALRelease_GetRangePts(swigCPtr, this, ALPoint3dArr.getCPtr(offsetPts), offsetPts, ALVector3dArr.getCPtr(vecs), vecs, dMargin, dStartMileage, dEndMileage);
  }

  public boolean IntersectWithLine(AL_Point3d linePt, AL_Vector3d lineVec, ALPoint3dArr interPts) {
    return AlignmentAllJNI.ALRelease_IntersectWithLine(swigCPtr, this, AL_Point3d.getCPtr(linePt), linePt, AL_Vector3d.getCPtr(lineVec), lineVec, ALPoint3dArr.getCPtr(interPts), interPts);
  }

  public void setM_radius2(double value) {
    AlignmentAllJNI.ALRelease_m_radius2_set(swigCPtr, this, value);
  }

  public double getM_radius2() {
    return AlignmentAllJNI.ALRelease_m_radius2_get(swigCPtr, this);
  }

}
