/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ChainArr extends java.util.AbstractList<ALChain> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChainArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChainArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ChainArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ChainArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChainArr(ALChain[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ALChain element : initialElements) {
      add(element);
    }
  }

  public ChainArr(Iterable<ALChain> initialElements) {
    this();
    for (ALChain element : initialElements) {
      add(element);
    }
  }

  public ALChain get(int index) {
    return doGet(index);
  }

  public ALChain set(int index, ALChain e) {
    return doSet(index, e);
  }

  public boolean add(ALChain e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ALChain e) {
    modCount++;
    doAdd(index, e);
  }

  public ALChain remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public ChainArr() {
    this(AlignmentAllJNI.new_ChainArr__SWIG_0(), true);
  }

  public ChainArr(ChainArr other) {
    this(AlignmentAllJNI.new_ChainArr__SWIG_1(ChainArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.ChainArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.ChainArr_clear(swigCPtr, this);
  }

  public ChainArr(int count, ALChain value) {
    this(AlignmentAllJNI.new_ChainArr__SWIG_2(count, ALChain.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.ChainArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.ChainArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.ChainArr_doSize(swigCPtr, this);
  }

  private void doAdd(ALChain x) {
    AlignmentAllJNI.ChainArr_doAdd__SWIG_0(swigCPtr, this, ALChain.getCPtr(x), x);
  }

  private void doAdd(int index, ALChain x) {
    AlignmentAllJNI.ChainArr_doAdd__SWIG_1(swigCPtr, this, index, ALChain.getCPtr(x), x);
  }

  private ALChain doRemove(int index) {
    return new ALChain(AlignmentAllJNI.ChainArr_doRemove(swigCPtr, this, index), true);
  }

  private ALChain doGet(int index) {
    return new ALChain(AlignmentAllJNI.ChainArr_doGet(swigCPtr, this, index), false);
  }

  private ALChain doSet(int index, ALChain val) {
    return new ALChain(AlignmentAllJNI.ChainArr_doSet(swigCPtr, this, index, ALChain.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.ChainArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
