/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class CheckData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CheckData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CheckData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CheckData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_CheckData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CheckData() {
    this(AlignmentAllJNI.new_CheckData(), true);
  }

  public void setM_Speed(double value) {
    AlignmentAllJNI.CheckData_m_Speed_set(swigCPtr, this, value);
  }

  public double getM_Speed() {
    return AlignmentAllJNI.CheckData_m_Speed_get(swigCPtr, this);
  }

  public void setM_TQI_Limit_Hori(double value) {
    AlignmentAllJNI.CheckData_m_TQI_Limit_Hori_set(swigCPtr, this, value);
  }

  public double getM_TQI_Limit_Hori() {
    return AlignmentAllJNI.CheckData_m_TQI_Limit_Hori_get(swigCPtr, this);
  }

  public void setM_TQI_Limit_Vert(double value) {
    AlignmentAllJNI.CheckData_m_TQI_Limit_Vert_set(swigCPtr, this, value);
  }

  public double getM_TQI_Limit_Vert() {
    return AlignmentAllJNI.CheckData_m_TQI_Limit_Vert_get(swigCPtr, this);
  }

  public void setM_TQI_limit_Margin(double value) {
    AlignmentAllJNI.CheckData_m_TQI_limit_Margin_set(swigCPtr, this, value);
  }

  public double getM_TQI_limit_Margin() {
    return AlignmentAllJNI.CheckData_m_TQI_limit_Margin_get(swigCPtr, this);
  }

  public void setM_TQI_limit_Twist(double value) {
    AlignmentAllJNI.CheckData_m_TQI_limit_Twist_set(swigCPtr, this, value);
  }

  public double getM_TQI_limit_Twist() {
    return AlignmentAllJNI.CheckData_m_TQI_limit_Twist_get(swigCPtr, this);
  }

  public void setM_TQI_limit_Gauge_Min(double value) {
    AlignmentAllJNI.CheckData_m_TQI_limit_Gauge_Min_set(swigCPtr, this, value);
  }

  public double getM_TQI_limit_Gauge_Min() {
    return AlignmentAllJNI.CheckData_m_TQI_limit_Gauge_Min_get(swigCPtr, this);
  }

  public void setM_TQI_limit_Gauge_Max(double value) {
    AlignmentAllJNI.CheckData_m_TQI_limit_Gauge_Max_set(swigCPtr, this, value);
  }

  public double getM_TQI_limit_Gauge_Max() {
    return AlignmentAllJNI.CheckData_m_TQI_limit_Gauge_Max_get(swigCPtr, this);
  }

  public void setM_TQI_limit_Gauge_Rate(double value) {
    AlignmentAllJNI.CheckData_m_TQI_limit_Gauge_Rate_set(swigCPtr, this, value);
  }

  public double getM_TQI_limit_Gauge_Rate() {
    return AlignmentAllJNI.CheckData_m_TQI_limit_Gauge_Rate_get(swigCPtr, this);
  }

  public void setM_Chord_Hori_20(double value) {
    AlignmentAllJNI.CheckData_m_Chord_Hori_20_set(swigCPtr, this, value);
  }

  public double getM_Chord_Hori_20() {
    return AlignmentAllJNI.CheckData_m_Chord_Hori_20_get(swigCPtr, this);
  }

  public void setM_Chord_Hori_30(double value) {
    AlignmentAllJNI.CheckData_m_Chord_Hori_30_set(swigCPtr, this, value);
  }

  public double getM_Chord_Hori_30() {
    return AlignmentAllJNI.CheckData_m_Chord_Hori_30_get(swigCPtr, this);
  }

  public void setM_Chord_Hori_60(double value) {
    AlignmentAllJNI.CheckData_m_Chord_Hori_60_set(swigCPtr, this, value);
  }

  public double getM_Chord_Hori_60() {
    return AlignmentAllJNI.CheckData_m_Chord_Hori_60_get(swigCPtr, this);
  }

  public void setM_Chord_Vert_20(double value) {
    AlignmentAllJNI.CheckData_m_Chord_Vert_20_set(swigCPtr, this, value);
  }

  public double getM_Chord_Vert_20() {
    return AlignmentAllJNI.CheckData_m_Chord_Vert_20_get(swigCPtr, this);
  }

  public void setM_Chord_Vert_30(double value) {
    AlignmentAllJNI.CheckData_m_Chord_Vert_30_set(swigCPtr, this, value);
  }

  public double getM_Chord_Vert_30() {
    return AlignmentAllJNI.CheckData_m_Chord_Vert_30_get(swigCPtr, this);
  }

  public void setM_Chord_Vert_60(double value) {
    AlignmentAllJNI.CheckData_m_Chord_Vert_60_set(swigCPtr, this, value);
  }

  public double getM_Chord_Vert_60() {
    return AlignmentAllJNI.CheckData_m_Chord_Vert_60_get(swigCPtr, this);
  }

}
