/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class CMultiLineUndoManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CMultiLineUndoManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CMultiLineUndoManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CMultiLineUndoManager obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_CMultiLineUndoManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CMultiLineUndoManager(long maxHistorySize) {
    this(AlignmentAllJNI.new_CMultiLineUndoManager__SWIG_0(maxHistorySize), true);
  }

  public CMultiLineUndoManager() {
    this(AlignmentAllJNI.new_CMultiLineUndoManager__SWIG_1(), true);
  }

  public void BindMultiLine(CMultiLine multiLine) {
    AlignmentAllJNI.CMultiLineUndoManager_BindMultiLine(swigCPtr, this, CMultiLine.getCPtr(multiLine), multiLine);
  }

  public void SaveSnapshot(String description) {
    AlignmentAllJNI.CMultiLineUndoManager_SaveSnapshot__SWIG_0(swigCPtr, this, description);
  }

  public void SaveSnapshot() {
    AlignmentAllJNI.CMultiLineUndoManager_SaveSnapshot__SWIG_1(swigCPtr, this);
  }

  public boolean Undo() {
    return AlignmentAllJNI.CMultiLineUndoManager_Undo(swigCPtr, this);
  }

  public boolean Redo() {
    return AlignmentAllJNI.CMultiLineUndoManager_Redo(swigCPtr, this);
  }

  public void Clear() {
    AlignmentAllJNI.CMultiLineUndoManager_Clear(swigCPtr, this);
  }

  public boolean RollbackTo(String description) {
    return AlignmentAllJNI.CMultiLineUndoManager_RollbackTo(swigCPtr, this, description);
  }

  public boolean CanUndo() {
    return AlignmentAllJNI.CMultiLineUndoManager_CanUndo(swigCPtr, this);
  }

  public boolean CanRedo() {
    return AlignmentAllJNI.CMultiLineUndoManager_CanRedo(swigCPtr, this);
  }

  public long GetUndoCount() {
    return AlignmentAllJNI.CMultiLineUndoManager_GetUndoCount(swigCPtr, this);
  }

  public long GetRedoCount() {
    return AlignmentAllJNI.CMultiLineUndoManager_GetRedoCount(swigCPtr, this);
  }

}
