/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class CMultiLine {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected CMultiLine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CMultiLine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_CMultiLine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CMultiLine() {
    this(AlignmentAllJNI.new_CMultiLine__SWIG_0(), true);
  }

  public CMultiLine(SurveyVector datas, int nStIndex) {
    this(AlignmentAllJNI.new_CMultiLine__SWIG_1(SurveyVector.getCPtr(datas), datas, nStIndex), true);
  }

  public void Init(SurveyVector datas, int nStIndex) {
    AlignmentAllJNI.CMultiLine_Init(swigCPtr, this, SurveyVector.getCPtr(datas), datas, nStIndex);
  }

  public boolean DelteKeyPt(int nIndex) {
    return AlignmentAllJNI.CMultiLine_DelteKeyPt(swigCPtr, this, nIndex);
  }

  public boolean InsertKetPt(AL_Point3d pt) {
    return AlignmentAllJNI.CMultiLine_InsertKetPt(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean InsertKeyPtAuto(double dMargin) {
    return AlignmentAllJNI.CMultiLine_InsertKeyPtAuto__SWIG_0(swigCPtr, this, dMargin);
  }

  public boolean InsertKeyPtAuto() {
    return AlignmentAllJNI.CMultiLine_InsertKeyPtAuto__SWIG_1(swigCPtr, this);
  }

  public int FindeKeyPt(AL_Point3d pt, double dTol) {
    return AlignmentAllJNI.CMultiLine_FindeKeyPt__SWIG_0(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, dTol);
  }

  public int FindeKeyPt(AL_Point3d pt) {
    return AlignmentAllJNI.CMultiLine_FindeKeyPt__SWIG_1(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean MoveKeyPt(AL_Point3d disPt, int nIndex) {
    return AlignmentAllJNI.CMultiLine_MoveKeyPt(swigCPtr, this, AL_Point3d.getCPtr(disPt), disPt, nIndex);
  }

  public InterPtArr GetInterPts(ALPoint3dArr pts, ALVector3dArr vecs) {
    return new InterPtArr(AlignmentAllJNI.CMultiLine_GetInterPts(swigCPtr, this, ALPoint3dArr.getCPtr(pts), pts, ALVector3dArr.getCPtr(vecs), vecs), true);
  }

  public int CheckResult() {
    return AlignmentAllJNI.CMultiLine_CheckResult(swigCPtr, this);
  }

  public ALPoint3dArr GetPoints() {
    return new ALPoint3dArr(AlignmentAllJNI.CMultiLine_GetPoints(swigCPtr, this), true);
  }

  public int GetStartIndex() {
    return AlignmentAllJNI.CMultiLine_GetStartIndex(swigCPtr, this);
  }

  public ALPoint3dArr GetKeyPoints() {
    return new ALPoint3dArr(AlignmentAllJNI.CMultiLine_GetKeyPoints(swigCPtr, this), true);
  }

}
