/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class CMultiLineSnapshot {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected CMultiLineSnapshot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CMultiLineSnapshot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_CMultiLineSnapshot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CMultiLineSnapshot(CMultiLine multiLine, String description) {
    this(AlignmentAllJNI.new_CMultiLineSnapshot__SWIG_0(CMultiLine.getCPtr(multiLine), multiLine, description), true);
  }

  public CMultiLineSnapshot(CMultiLine multiLine) {
    this(AlignmentAllJNI.new_CMultiLineSnapshot__SWIG_1(CMultiLine.getCPtr(multiLine), multiLine), true);
  }

  public void RestoreTo(CMultiLine multiLine) {
    AlignmentAllJNI.CMultiLineSnapshot_RestoreTo(swigCPtr, this, CMultiLine.getCPtr(multiLine), multiLine);
  }

  public String GetDescription() {
    return AlignmentAllJNI.CMultiLineSnapshot_GetDescription(swigCPtr, this);
  }

}
