/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ComCurveDesignerUndoManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ComCurveDesignerUndoManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ComCurveDesignerUndoManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ComCurveDesignerUndoManager obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ComCurveDesignerUndoManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ComCurveDesignerUndoManager(long maxHistorySize) {
    this(AlignmentAllJNI.new_ComCurveDesignerUndoManager__SWIG_0(maxHistorySize), true);
  }

  public ComCurveDesignerUndoManager() {
    this(AlignmentAllJNI.new_ComCurveDesignerUndoManager__SWIG_1(), true);
  }

  public void BindDesigner(ComCurveDesigner designer) {
    AlignmentAllJNI.ComCurveDesignerUndoManager_BindDesigner(swigCPtr, this, ComCurveDesigner.getCPtr(designer), designer);
  }

  public void SaveSnapshot(String description) {
    AlignmentAllJNI.ComCurveDesignerUndoManager_SaveSnapshot__SWIG_0(swigCPtr, this, description);
  }

  public void SaveSnapshot() {
    AlignmentAllJNI.ComCurveDesignerUndoManager_SaveSnapshot__SWIG_1(swigCPtr, this);
  }

  public boolean Undo() {
    return AlignmentAllJNI.ComCurveDesignerUndoManager_Undo(swigCPtr, this);
  }

  public boolean Redo() {
    return AlignmentAllJNI.ComCurveDesignerUndoManager_Redo(swigCPtr, this);
  }

  public void Clear() {
    AlignmentAllJNI.ComCurveDesignerUndoManager_Clear(swigCPtr, this);
  }

  public boolean RollbackTo(String description) {
    return AlignmentAllJNI.ComCurveDesignerUndoManager_RollbackTo(swigCPtr, this, description);
  }

  public boolean CanUndo() {
    return AlignmentAllJNI.ComCurveDesignerUndoManager_CanUndo(swigCPtr, this);
  }

  public boolean CanRedo() {
    return AlignmentAllJNI.ComCurveDesignerUndoManager_CanRedo(swigCPtr, this);
  }

}
