/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ComCurveDesignerSnapshot {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ComCurveDesignerSnapshot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ComCurveDesignerSnapshot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ComCurveDesignerSnapshot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ComCurveDesignerSnapshot(ComCurveDesigner designer, String description) {
    this(AlignmentAllJNI.new_ComCurveDesignerSnapshot__SWIG_0(ComCurveDesigner.getCPtr(designer), designer, description), true);
  }

  public ComCurveDesignerSnapshot(ComCurveDesigner designer) {
    this(AlignmentAllJNI.new_ComCurveDesignerSnapshot__SWIG_1(ComCurveDesigner.getCPtr(designer), designer), true);
  }

  public void RestoreTo(ComCurveDesigner designer) {
    AlignmentAllJNI.ComCurveDesignerSnapshot_RestoreTo(swigCPtr, this, ComCurveDesigner.getCPtr(designer), designer);
  }

  public String GetDescription() {
    return AlignmentAllJNI.ComCurveDesignerSnapshot_GetDescription(swigCPtr, this);
  }

}
