/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ComCurvePara {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ComCurvePara(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ComCurvePara obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ComCurvePara obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ComCurvePara(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNRadiusDig(int value) {
    AlignmentAllJNI.ComCurvePara_nRadiusDig_set(swigCPtr, this, value);
  }

  public int getNRadiusDig() {
    return AlignmentAllJNI.ComCurvePara_nRadiusDig_get(swigCPtr, this);
  }

  public void setDSpiralDig(double value) {
    AlignmentAllJNI.ComCurvePara_dSpiralDig_set(swigCPtr, this, value);
  }

  public double getDSpiralDig() {
    return AlignmentAllJNI.ComCurvePara_dSpiralDig_get(swigCPtr, this);
  }

  public void setNSplitFliterNum(int value) {
    AlignmentAllJNI.ComCurvePara_nSplitFliterNum_set(swigCPtr, this, value);
  }

  public int getNSplitFliterNum() {
    return AlignmentAllJNI.ComCurvePara_nSplitFliterNum_get(swigCPtr, this);
  }

  public void setNMaxInterCount(int value) {
    AlignmentAllJNI.ComCurvePara_nMaxInterCount_set(swigCPtr, this, value);
  }

  public int getNMaxInterCount() {
    return AlignmentAllJNI.ComCurvePara_nMaxInterCount_get(swigCPtr, this);
  }

  public ComCurvePara() {
    this(AlignmentAllJNI.new_ComCurvePara(), true);
  }

}
