/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class ComCurveDesigner {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ComCurveDesigner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ComCurveDesigner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_ComCurveDesigner(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ComCurveDesigner() {
    this(AlignmentAllJNI.new_ComCurveDesigner__SWIG_0(), true);
  }

  public ComCurveDesigner(SurveyVector datas, int nStIndex, int nEdIndex) {
    this(AlignmentAllJNI.new_ComCurveDesigner__SWIG_1(SurveyVector.getCPtr(datas), datas, nStIndex, nEdIndex), true);
  }

  public void SetSurveyDatas(SurveyVector datas, int nStIndex, int nEdIndex) {
    AlignmentAllJNI.ComCurveDesigner_SetSurveyDatas(swigCPtr, this, SurveyVector.getCPtr(datas), datas, nStIndex, nEdIndex);
  }

  public IntIntPair GetStAndEdIndex() {
    return new IntIntPair(AlignmentAllJNI.ComCurveDesigner_GetStAndEdIndex(swigCPtr, this), true);
  }

  public InterPtArr GetInterPts() {
    return new InterPtArr(AlignmentAllJNI.ComCurveDesigner_GetInterPts(swigCPtr, this), true);
  }

  public SurveyVector GetSurveyDatas() {
    return new SurveyVector(AlignmentAllJNI.ComCurveDesigner_GetSurveyDatas(swigCPtr, this), true);
  }

  public double GetComCurveLen(int nIndex) {
    return AlignmentAllJNI.ComCurveDesigner_GetComCurveLen(swigCPtr, this, nIndex);
  }

  public void SetComCurvePara(ComCurvePara para) {
    AlignmentAllJNI.ComCurveDesigner_SetComCurvePara(swigCPtr, this, ComCurvePara.getCPtr(para), para);
  }

  public ALPoint3dArr GetCurvation() {
    return new ALPoint3dArr(AlignmentAllJNI.ComCurveDesigner_GetCurvation(swigCPtr, this), true);
  }

  public IntArr AutoKeyPts() {
    return new IntArr(AlignmentAllJNI.ComCurveDesigner_AutoKeyPts(swigCPtr, this), true);
  }

  public boolean StartComCurveFitting(IntArr keyPts) {
    return AlignmentAllJNI.ComCurveDesigner_StartComCurveFitting(swigCPtr, this, IntArr.getCPtr(keyPts), keyPts);
  }

  public boolean ComCurveOpting(double dSpiral1, double dSpiral2, double dSpiral3, boolean isManual) {
    return AlignmentAllJNI.ComCurveDesigner_ComCurveOpting__SWIG_0(swigCPtr, this, dSpiral1, dSpiral2, dSpiral3, isManual);
  }

  public boolean ComCurveOpting(double dSpiral1, double dSpiral2, double dSpiral3) {
    return AlignmentAllJNI.ComCurveDesigner_ComCurveOpting__SWIG_1(swigCPtr, this, dSpiral1, dSpiral2, dSpiral3);
  }

  public boolean InitKeyPts(IntArr keyPts) {
    return AlignmentAllJNI.ComCurveDesigner_InitKeyPts(swigCPtr, this, IntArr.getCPtr(keyPts), keyPts);
  }

  public boolean CalHoriMargin() {
    return AlignmentAllJNI.ComCurveDesigner_CalHoriMargin(swigCPtr, this);
  }

}
