/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class CompositeSnapshot {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected CompositeSnapshot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompositeSnapshot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_CompositeSnapshot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CompositeSnapshot(AlignmentFitting fitting, String description) {
    this(AlignmentAllJNI.new_CompositeSnapshot(AlignmentFitting.getCPtr(fitting), fitting, description), true);
  }

  public void RestoreTo(AlignmentFitting fitting) {
    AlignmentAllJNI.CompositeSnapshot_RestoreTo(swigCPtr, this, AlignmentFitting.getCPtr(fitting), fitting);
  }

  public String GetDescription() {
    return AlignmentAllJNI.CompositeSnapshot_GetDescription(swigCPtr, this);
  }

  public long GetTimestamp() {
    return AlignmentAllJNI.CompositeSnapshot_GetTimestamp(swigCPtr, this);
  }

  public long EstimateSize() {
    return AlignmentAllJNI.CompositeSnapshot_EstimateSize(swigCPtr, this);
  }

}
