/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class CStandCode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CStandCode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CStandCode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CStandCode obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_CStandCode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CStandCode() {
    this(AlignmentAllJNI.new_CStandCode(), true);
  }

  public void setM_DesignSpeed(double value) {
    AlignmentAllJNI.CStandCode_m_DesignSpeed_set(swigCPtr, this, value);
  }

  public double getM_DesignSpeed() {
    return AlignmentAllJNI.CStandCode_m_DesignSpeed_get(swigCPtr, this);
  }

  public void setM_minRadius_Normal(double value) {
    AlignmentAllJNI.CStandCode_m_minRadius_Normal_set(swigCPtr, this, value);
  }

  public double getM_minRadius_Normal() {
    return AlignmentAllJNI.CStandCode_m_minRadius_Normal_get(swigCPtr, this);
  }

  public void setM_minRadius_Diff(double value) {
    AlignmentAllJNI.CStandCode_m_minRadius_Diff_set(swigCPtr, this, value);
  }

  public double getM_minRadius_Diff() {
    return AlignmentAllJNI.CStandCode_m_minRadius_Diff_get(swigCPtr, this);
  }

  public void setM_LA_Normal(double value) {
    AlignmentAllJNI.CStandCode_m_LA_Normal_set(swigCPtr, this, value);
  }

  public double getM_LA_Normal() {
    return AlignmentAllJNI.CStandCode_m_LA_Normal_get(swigCPtr, this);
  }

  public void setM_LA_Diff(double value) {
    AlignmentAllJNI.CStandCode_m_LA_Diff_set(swigCPtr, this, value);
  }

  public double getM_LA_Diff() {
    return AlignmentAllJNI.CStandCode_m_LA_Diff_get(swigCPtr, this);
  }

  public void setM_LA_LestLevel(double value) {
    AlignmentAllJNI.CStandCode_m_LA_LestLevel_set(swigCPtr, this, value);
  }

  public double getM_LA_LestLevel() {
    return AlignmentAllJNI.CStandCode_m_LA_LestLevel_get(swigCPtr, this);
  }

  public void setM_SlpLen_Normal(double value) {
    AlignmentAllJNI.CStandCode_m_SlpLen_Normal_set(swigCPtr, this, value);
  }

  public double getM_SlpLen_Normal() {
    return AlignmentAllJNI.CStandCode_m_SlpLen_Normal_get(swigCPtr, this);
  }

  public void setM_Slp_Margin(double value) {
    AlignmentAllJNI.CStandCode_m_Slp_Margin_set(swigCPtr, this, value);
  }

  public double getM_Slp_Margin() {
    return AlignmentAllJNI.CStandCode_m_Slp_Margin_get(swigCPtr, this);
  }

  public void setM_V_minRadius(double value) {
    AlignmentAllJNI.CStandCode_m_V_minRadius_set(swigCPtr, this, value);
  }

  public double getM_V_minRadius() {
    return AlignmentAllJNI.CStandCode_m_V_minRadius_get(swigCPtr, this);
  }

  public void setM_V_MaxRadius(double value) {
    AlignmentAllJNI.CStandCode_m_V_MaxRadius_set(swigCPtr, this, value);
  }

  public double getM_V_MaxRadius() {
    return AlignmentAllJNI.CStandCode_m_V_MaxRadius_get(swigCPtr, this);
  }

}
