/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DisplayMileage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DisplayMileage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DisplayMileage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DisplayMileage obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DisplayMileage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DisplayMileage() {
    this(AlignmentAllJNI.new_DisplayMileage__SWIG_0(), true);
  }

  public DisplayMileage(double dMileage, int nIndex) {
    this(AlignmentAllJNI.new_DisplayMileage__SWIG_1(dMileage, nIndex), true);
  }

  public void setDMileage(double value) {
    AlignmentAllJNI.DisplayMileage_dMileage_set(swigCPtr, this, value);
  }

  public double getDMileage() {
    return AlignmentAllJNI.DisplayMileage_dMileage_get(swigCPtr, this);
  }

  public void setNIndex(int value) {
    AlignmentAllJNI.DisplayMileage_nIndex_set(swigCPtr, this, value);
  }

  public int getNIndex() {
    return AlignmentAllJNI.DisplayMileage_nIndex_get(swigCPtr, this);
  }

  public void setStrWord(String value) {
    AlignmentAllJNI.DisplayMileage_strWord_set(swigCPtr, this, value);
  }

  public String getStrWord() {
    return AlignmentAllJNI.DisplayMileage_strWord_get(swigCPtr, this);
  }

}
