/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DisplayMileagePair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DisplayMileagePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DisplayMileagePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DisplayMileagePair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DisplayMileagePair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DisplayMileagePair() {
    this(AlignmentAllJNI.new_DisplayMileagePair__SWIG_0(), true);
  }

  public DisplayMileagePair(DisplayMileage first, DisplayMileage second) {
    this(AlignmentAllJNI.new_DisplayMileagePair__SWIG_1(DisplayMileage.getCPtr(first), first, DisplayMileage.getCPtr(second), second), true);
  }

  public DisplayMileagePair(DisplayMileagePair other) {
    this(AlignmentAllJNI.new_DisplayMileagePair__SWIG_2(DisplayMileagePair.getCPtr(other), other), true);
  }

  public void setFirst(DisplayMileage value) {
    AlignmentAllJNI.DisplayMileagePair_first_set(swigCPtr, this, DisplayMileage.getCPtr(value), value);
  }

  public DisplayMileage getFirst() {
    long cPtr = AlignmentAllJNI.DisplayMileagePair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DisplayMileage(cPtr, false);
  }

  public void setSecond(DisplayMileage value) {
    AlignmentAllJNI.DisplayMileagePair_second_set(swigCPtr, this, DisplayMileage.getCPtr(value), value);
  }

  public DisplayMileage getSecond() {
    long cPtr = AlignmentAllJNI.DisplayMileagePair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DisplayMileage(cPtr, false);
  }

}
