/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DisplayMileageDoublePairVector extends java.util.AbstractList<DisplayMileageDoublePair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DisplayMileageDoublePairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DisplayMileageDoublePairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DisplayMileageDoublePairVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DisplayMileageDoublePairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DisplayMileageDoublePairVector(DisplayMileageDoublePair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (DisplayMileageDoublePair element : initialElements) {
      add(element);
    }
  }

  public DisplayMileageDoublePairVector(Iterable<DisplayMileageDoublePair> initialElements) {
    this();
    for (DisplayMileageDoublePair element : initialElements) {
      add(element);
    }
  }

  public DisplayMileageDoublePair get(int index) {
    return doGet(index);
  }

  public DisplayMileageDoublePair set(int index, DisplayMileageDoublePair e) {
    return doSet(index, e);
  }

  public boolean add(DisplayMileageDoublePair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, DisplayMileageDoublePair e) {
    modCount++;
    doAdd(index, e);
  }

  public DisplayMileageDoublePair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public DisplayMileageDoublePairVector() {
    this(AlignmentAllJNI.new_DisplayMileageDoublePairVector__SWIG_0(), true);
  }

  public DisplayMileageDoublePairVector(DisplayMileageDoublePairVector other) {
    this(AlignmentAllJNI.new_DisplayMileageDoublePairVector__SWIG_1(DisplayMileageDoublePairVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.DisplayMileageDoublePairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.DisplayMileageDoublePairVector_clear(swigCPtr, this);
  }

  public DisplayMileageDoublePairVector(int count, DisplayMileageDoublePair value) {
    this(AlignmentAllJNI.new_DisplayMileageDoublePairVector__SWIG_2(count, DisplayMileageDoublePair.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.DisplayMileageDoublePairVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.DisplayMileageDoublePairVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.DisplayMileageDoublePairVector_doSize(swigCPtr, this);
  }

  private void doAdd(DisplayMileageDoublePair x) {
    AlignmentAllJNI.DisplayMileageDoublePairVector_doAdd__SWIG_0(swigCPtr, this, DisplayMileageDoublePair.getCPtr(x), x);
  }

  private void doAdd(int index, DisplayMileageDoublePair x) {
    AlignmentAllJNI.DisplayMileageDoublePairVector_doAdd__SWIG_1(swigCPtr, this, index, DisplayMileageDoublePair.getCPtr(x), x);
  }

  private DisplayMileageDoublePair doRemove(int index) {
    return new DisplayMileageDoublePair(AlignmentAllJNI.DisplayMileageDoublePairVector_doRemove(swigCPtr, this, index), true);
  }

  private DisplayMileageDoublePair doGet(int index) {
    return new DisplayMileageDoublePair(AlignmentAllJNI.DisplayMileageDoublePairVector_doGet(swigCPtr, this, index), false);
  }

  private DisplayMileageDoublePair doSet(int index, DisplayMileageDoublePair val) {
    return new DisplayMileageDoublePair(AlignmentAllJNI.DisplayMileageDoublePairVector_doSet(swigCPtr, this, index, DisplayMileageDoublePair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.DisplayMileageDoublePairVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
