/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DisplayMileageDoublePair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DisplayMileageDoublePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DisplayMileageDoublePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DisplayMileageDoublePair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DisplayMileageDoublePair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DisplayMileageDoublePair() {
    this(AlignmentAllJNI.new_DisplayMileageDoublePair__SWIG_0(), true);
  }

  public DisplayMileageDoublePair(DisplayMileage first, double second) {
    this(AlignmentAllJNI.new_DisplayMileageDoublePair__SWIG_1(DisplayMileage.getCPtr(first), first, second), true);
  }

  public DisplayMileageDoublePair(DisplayMileageDoublePair other) {
    this(AlignmentAllJNI.new_DisplayMileageDoublePair__SWIG_2(DisplayMileageDoublePair.getCPtr(other), other), true);
  }

  public void setFirst(DisplayMileage value) {
    AlignmentAllJNI.DisplayMileageDoublePair_first_set(swigCPtr, this, DisplayMileage.getCPtr(value), value);
  }

  public DisplayMileage getFirst() {
    long cPtr = AlignmentAllJNI.DisplayMileageDoublePair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DisplayMileage(cPtr, false);
  }

  public void setSecond(double value) {
    AlignmentAllJNI.DisplayMileageDoublePair_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return AlignmentAllJNI.DisplayMileageDoublePair_second_get(swigCPtr, this);
  }

}
