/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DisplayMileageIntPairVector extends java.util.AbstractList<DisplayMileageIntPair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DisplayMileageIntPairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DisplayMileageIntPairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DisplayMileageIntPairVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DisplayMileageIntPairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DisplayMileageIntPairVector(DisplayMileageIntPair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (DisplayMileageIntPair element : initialElements) {
      add(element);
    }
  }

  public DisplayMileageIntPairVector(Iterable<DisplayMileageIntPair> initialElements) {
    this();
    for (DisplayMileageIntPair element : initialElements) {
      add(element);
    }
  }

  public DisplayMileageIntPair get(int index) {
    return doGet(index);
  }

  public DisplayMileageIntPair set(int index, DisplayMileageIntPair e) {
    return doSet(index, e);
  }

  public boolean add(DisplayMileageIntPair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, DisplayMileageIntPair e) {
    modCount++;
    doAdd(index, e);
  }

  public DisplayMileageIntPair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public DisplayMileageIntPairVector() {
    this(AlignmentAllJNI.new_DisplayMileageIntPairVector__SWIG_0(), true);
  }

  public DisplayMileageIntPairVector(DisplayMileageIntPairVector other) {
    this(AlignmentAllJNI.new_DisplayMileageIntPairVector__SWIG_1(DisplayMileageIntPairVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.DisplayMileageIntPairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.DisplayMileageIntPairVector_clear(swigCPtr, this);
  }

  public DisplayMileageIntPairVector(int count, DisplayMileageIntPair value) {
    this(AlignmentAllJNI.new_DisplayMileageIntPairVector__SWIG_2(count, DisplayMileageIntPair.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.DisplayMileageIntPairVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.DisplayMileageIntPairVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.DisplayMileageIntPairVector_doSize(swigCPtr, this);
  }

  private void doAdd(DisplayMileageIntPair x) {
    AlignmentAllJNI.DisplayMileageIntPairVector_doAdd__SWIG_0(swigCPtr, this, DisplayMileageIntPair.getCPtr(x), x);
  }

  private void doAdd(int index, DisplayMileageIntPair x) {
    AlignmentAllJNI.DisplayMileageIntPairVector_doAdd__SWIG_1(swigCPtr, this, index, DisplayMileageIntPair.getCPtr(x), x);
  }

  private DisplayMileageIntPair doRemove(int index) {
    return new DisplayMileageIntPair(AlignmentAllJNI.DisplayMileageIntPairVector_doRemove(swigCPtr, this, index), true);
  }

  private DisplayMileageIntPair doGet(int index) {
    return new DisplayMileageIntPair(AlignmentAllJNI.DisplayMileageIntPairVector_doGet(swigCPtr, this, index), false);
  }

  private DisplayMileageIntPair doSet(int index, DisplayMileageIntPair val) {
    return new DisplayMileageIntPair(AlignmentAllJNI.DisplayMileageIntPairVector_doSet(swigCPtr, this, index, DisplayMileageIntPair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.DisplayMileageIntPairVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
