/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DoubleIntPairVector extends java.util.AbstractList<DoubleIntPair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleIntPairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleIntPairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DoubleIntPairVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DoubleIntPairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleIntPairVector(DoubleIntPair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (DoubleIntPair element : initialElements) {
      add(element);
    }
  }

  public DoubleIntPairVector(Iterable<DoubleIntPair> initialElements) {
    this();
    for (DoubleIntPair element : initialElements) {
      add(element);
    }
  }

  public DoubleIntPair get(int index) {
    return doGet(index);
  }

  public DoubleIntPair set(int index, DoubleIntPair e) {
    return doSet(index, e);
  }

  public boolean add(DoubleIntPair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, DoubleIntPair e) {
    modCount++;
    doAdd(index, e);
  }

  public DoubleIntPair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public DoubleIntPairVector() {
    this(AlignmentAllJNI.new_DoubleIntPairVector__SWIG_0(), true);
  }

  public DoubleIntPairVector(DoubleIntPairVector other) {
    this(AlignmentAllJNI.new_DoubleIntPairVector__SWIG_1(DoubleIntPairVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.DoubleIntPairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.DoubleIntPairVector_clear(swigCPtr, this);
  }

  public DoubleIntPairVector(int count, DoubleIntPair value) {
    this(AlignmentAllJNI.new_DoubleIntPairVector__SWIG_2(count, DoubleIntPair.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.DoubleIntPairVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.DoubleIntPairVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.DoubleIntPairVector_doSize(swigCPtr, this);
  }

  private void doAdd(DoubleIntPair x) {
    AlignmentAllJNI.DoubleIntPairVector_doAdd__SWIG_0(swigCPtr, this, DoubleIntPair.getCPtr(x), x);
  }

  private void doAdd(int index, DoubleIntPair x) {
    AlignmentAllJNI.DoubleIntPairVector_doAdd__SWIG_1(swigCPtr, this, index, DoubleIntPair.getCPtr(x), x);
  }

  private DoubleIntPair doRemove(int index) {
    return new DoubleIntPair(AlignmentAllJNI.DoubleIntPairVector_doRemove(swigCPtr, this, index), true);
  }

  private DoubleIntPair doGet(int index) {
    return new DoubleIntPair(AlignmentAllJNI.DoubleIntPairVector_doGet(swigCPtr, this, index), false);
  }

  private DoubleIntPair doSet(int index, DoubleIntPair val) {
    return new DoubleIntPair(AlignmentAllJNI.DoubleIntPairVector_doSet(swigCPtr, this, index, DoubleIntPair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.DoubleIntPairVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
