/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DoubleIntPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleIntPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleIntPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DoubleIntPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DoubleIntPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleIntPair() {
    this(AlignmentAllJNI.new_DoubleIntPair__SWIG_0(), true);
  }

  public DoubleIntPair(double first, int second) {
    this(AlignmentAllJNI.new_DoubleIntPair__SWIG_1(first, second), true);
  }

  public DoubleIntPair(DoubleIntPair other) {
    this(AlignmentAllJNI.new_DoubleIntPair__SWIG_2(DoubleIntPair.getCPtr(other), other), true);
  }

  public void setFirst(double value) {
    AlignmentAllJNI.DoubleIntPair_first_set(swigCPtr, this, value);
  }

  public double getFirst() {
    return AlignmentAllJNI.DoubleIntPair_first_get(swigCPtr, this);
  }

  public void setSecond(int value) {
    AlignmentAllJNI.DoubleIntPair_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return AlignmentAllJNI.DoubleIntPair_second_get(swigCPtr, this);
  }

}
