/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DoubleDoublePairVector extends java.util.AbstractList<DoubleDoublePair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleDoublePairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleDoublePairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DoubleDoublePairVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DoubleDoublePairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleDoublePairVector(DoubleDoublePair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (DoubleDoublePair element : initialElements) {
      add(element);
    }
  }

  public DoubleDoublePairVector(Iterable<DoubleDoublePair> initialElements) {
    this();
    for (DoubleDoublePair element : initialElements) {
      add(element);
    }
  }

  public DoubleDoublePair get(int index) {
    return doGet(index);
  }

  public DoubleDoublePair set(int index, DoubleDoublePair e) {
    return doSet(index, e);
  }

  public boolean add(DoubleDoublePair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, DoubleDoublePair e) {
    modCount++;
    doAdd(index, e);
  }

  public DoubleDoublePair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public DoubleDoublePairVector() {
    this(AlignmentAllJNI.new_DoubleDoublePairVector__SWIG_0(), true);
  }

  public DoubleDoublePairVector(DoubleDoublePairVector other) {
    this(AlignmentAllJNI.new_DoubleDoublePairVector__SWIG_1(DoubleDoublePairVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.DoubleDoublePairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.DoubleDoublePairVector_clear(swigCPtr, this);
  }

  public DoubleDoublePairVector(int count, DoubleDoublePair value) {
    this(AlignmentAllJNI.new_DoubleDoublePairVector__SWIG_2(count, DoubleDoublePair.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.DoubleDoublePairVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.DoubleDoublePairVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.DoubleDoublePairVector_doSize(swigCPtr, this);
  }

  private void doAdd(DoubleDoublePair x) {
    AlignmentAllJNI.DoubleDoublePairVector_doAdd__SWIG_0(swigCPtr, this, DoubleDoublePair.getCPtr(x), x);
  }

  private void doAdd(int index, DoubleDoublePair x) {
    AlignmentAllJNI.DoubleDoublePairVector_doAdd__SWIG_1(swigCPtr, this, index, DoubleDoublePair.getCPtr(x), x);
  }

  private DoubleDoublePair doRemove(int index) {
    return new DoubleDoublePair(AlignmentAllJNI.DoubleDoublePairVector_doRemove(swigCPtr, this, index), true);
  }

  private DoubleDoublePair doGet(int index) {
    return new DoubleDoublePair(AlignmentAllJNI.DoubleDoublePairVector_doGet(swigCPtr, this, index), false);
  }

  private DoubleDoublePair doSet(int index, DoubleDoublePair val) {
    return new DoubleDoublePair(AlignmentAllJNI.DoubleDoublePairVector_doSet(swigCPtr, this, index, DoubleDoublePair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.DoubleDoublePairVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
