/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class DoubleDoublePair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleDoublePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleDoublePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DoubleDoublePair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_DoubleDoublePair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleDoublePair() {
    this(AlignmentAllJNI.new_DoubleDoublePair__SWIG_0(), true);
  }

  public DoubleDoublePair(double first, double second) {
    this(AlignmentAllJNI.new_DoubleDoublePair__SWIG_1(first, second), true);
  }

  public DoubleDoublePair(DoubleDoublePair other) {
    this(AlignmentAllJNI.new_DoubleDoublePair__SWIG_2(DoubleDoublePair.getCPtr(other), other), true);
  }

  public void setFirst(double value) {
    AlignmentAllJNI.DoubleDoublePair_first_set(swigCPtr, this, value);
  }

  public double getFirst() {
    return AlignmentAllJNI.DoubleDoublePair_first_get(swigCPtr, this);
  }

  public void setSecond(double value) {
    AlignmentAllJNI.DoubleDoublePair_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return AlignmentAllJNI.DoubleDoublePair_second_get(swigCPtr, this);
  }

}
