/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class FittingModeArr extends java.util.AbstractList<Integer> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FittingModeArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FittingModeArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FittingModeArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_FittingModeArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FittingModeArr(int[] initialElements) {
    this();
    reserve(initialElements.length);

    for (int element : initialElements) {
      add(element);
    }
  }

  public FittingModeArr(Iterable<Integer> initialElements) {
    this();
    for (Integer element : initialElements) {
      add(element);
    }
  }

  public Integer get(int index) {
    long cptr = SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type.getCPtr(doGet(index));
    return (int)cptr;
  }

  public Integer set(int index, Integer e) {
    long oldCptr = SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type.getCPtr(doSet(index, new SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type(e.longValue(), false)));
    return (int)oldCptr;
  }

  public boolean add(Integer e) {
    modCount++;
    doAdd(new SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type(e.longValue(), false));
    return true;
  }

  public void add(int index, Integer e) {
    modCount++;
    doAdd(index, new SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type(e.longValue(), false));
  }

  public Integer remove(int index) {
    modCount++;
    long cptr = SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type.getCPtr(doRemove(index));
    return (int)cptr;
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public FittingModeArr() {
    this(AlignmentAllJNI.new_FittingModeArr__SWIG_0(), true);
  }

  public FittingModeArr(FittingModeArr other) {
    this(AlignmentAllJNI.new_FittingModeArr__SWIG_1(FittingModeArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.FittingModeArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.FittingModeArr_clear(swigCPtr, this);
  }

  public FittingModeArr(int count, int value) {
    this(AlignmentAllJNI.new_FittingModeArr__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.FittingModeArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.FittingModeArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.FittingModeArr_doSize(swigCPtr, this);
  }

  private void doAdd(SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type x) {
    AlignmentAllJNI.FittingModeArr_doAdd__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type.getCPtr(x));
  }

  private void doAdd(int index, SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type x) {
    AlignmentAllJNI.FittingModeArr_doAdd__SWIG_1(swigCPtr, this, index, SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type.getCPtr(x));
  }

  private SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type doRemove(int index) {
    return new SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type(AlignmentAllJNI.FittingModeArr_doRemove(swigCPtr, this, index), true);
  }

  private SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type doGet(int index) {
    return new SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type(AlignmentAllJNI.FittingModeArr_doGet(swigCPtr, this, index), false);
  }

  private SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type doSet(int index, SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type val) {
    return new SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type(AlignmentAllJNI.FittingModeArr_doSet(swigCPtr, this, index, SWIGTYPE_p_std__vectorT_AlignmentFittingCore__ALFITMODE_t__value_type.getCPtr(val)), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.FittingModeArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
