/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class GradeChangePointArr extends java.util.AbstractList<ALGradeChangePoint> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GradeChangePointArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GradeChangePointArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GradeChangePointArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_GradeChangePointArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GradeChangePointArr(ALGradeChangePoint[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ALGradeChangePoint element : initialElements) {
      add(element);
    }
  }

  public GradeChangePointArr(Iterable<ALGradeChangePoint> initialElements) {
    this();
    for (ALGradeChangePoint element : initialElements) {
      add(element);
    }
  }

  public ALGradeChangePoint get(int index) {
    return doGet(index);
  }

  public ALGradeChangePoint set(int index, ALGradeChangePoint e) {
    return doSet(index, e);
  }

  public boolean add(ALGradeChangePoint e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ALGradeChangePoint e) {
    modCount++;
    doAdd(index, e);
  }

  public ALGradeChangePoint remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public GradeChangePointArr() {
    this(AlignmentAllJNI.new_GradeChangePointArr__SWIG_0(), true);
  }

  public GradeChangePointArr(GradeChangePointArr other) {
    this(AlignmentAllJNI.new_GradeChangePointArr__SWIG_1(GradeChangePointArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.GradeChangePointArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.GradeChangePointArr_clear(swigCPtr, this);
  }

  public GradeChangePointArr(int count, ALGradeChangePoint value) {
    this(AlignmentAllJNI.new_GradeChangePointArr__SWIG_2(count, ALGradeChangePoint.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.GradeChangePointArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.GradeChangePointArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.GradeChangePointArr_doSize(swigCPtr, this);
  }

  private void doAdd(ALGradeChangePoint x) {
    AlignmentAllJNI.GradeChangePointArr_doAdd__SWIG_0(swigCPtr, this, ALGradeChangePoint.getCPtr(x), x);
  }

  private void doAdd(int index, ALGradeChangePoint x) {
    AlignmentAllJNI.GradeChangePointArr_doAdd__SWIG_1(swigCPtr, this, index, ALGradeChangePoint.getCPtr(x), x);
  }

  private ALGradeChangePoint doRemove(int index) {
    return new ALGradeChangePoint(AlignmentAllJNI.GradeChangePointArr_doRemove(swigCPtr, this, index), true);
  }

  private ALGradeChangePoint doGet(int index) {
    return new ALGradeChangePoint(AlignmentAllJNI.GradeChangePointArr_doGet(swigCPtr, this, index), false);
  }

  private ALGradeChangePoint doSet(int index, ALGradeChangePoint val) {
    return new ALGradeChangePoint(AlignmentAllJNI.GradeChangePointArr_doSet(swigCPtr, this, index, ALGradeChangePoint.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.GradeChangePointArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
