/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class IntArr extends java.util.AbstractList<Integer> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IntArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_IntArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntArr(int[] initialElements) {
    this();
    reserve(initialElements.length);

    for (int element : initialElements) {
      add(element);
    }
  }

  public IntArr(Iterable<Integer> initialElements) {
    this();
    for (int element : initialElements) {
      add(element);
    }
  }

  public Integer get(int index) {
    return doGet(index);
  }

  public Integer set(int index, Integer e) {
    return doSet(index, e);
  }

  public boolean add(Integer e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Integer e) {
    modCount++;
    doAdd(index, e);
  }

  public Integer remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public IntArr() {
    this(AlignmentAllJNI.new_IntArr__SWIG_0(), true);
  }

  public IntArr(IntArr other) {
    this(AlignmentAllJNI.new_IntArr__SWIG_1(IntArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.IntArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.IntArr_clear(swigCPtr, this);
  }

  public IntArr(int count, int value) {
    this(AlignmentAllJNI.new_IntArr__SWIG_2(count, value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.IntArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.IntArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.IntArr_doSize(swigCPtr, this);
  }

  private void doAdd(int x) {
    AlignmentAllJNI.IntArr_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, int x) {
    AlignmentAllJNI.IntArr_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private int doRemove(int index) {
    return AlignmentAllJNI.IntArr_doRemove(swigCPtr, this, index);
  }

  private int doGet(int index) {
    return AlignmentAllJNI.IntArr_doGet(swigCPtr, this, index);
  }

  private int doSet(int index, int val) {
    return AlignmentAllJNI.IntArr_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.IntArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
