/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class IntDoublePairVector extends java.util.AbstractList<IntDoublePair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntDoublePairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntDoublePairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IntDoublePairVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_IntDoublePairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntDoublePairVector(IntDoublePair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (IntDoublePair element : initialElements) {
      add(element);
    }
  }

  public IntDoublePairVector(Iterable<IntDoublePair> initialElements) {
    this();
    for (IntDoublePair element : initialElements) {
      add(element);
    }
  }

  public IntDoublePair get(int index) {
    return doGet(index);
  }

  public IntDoublePair set(int index, IntDoublePair e) {
    return doSet(index, e);
  }

  public boolean add(IntDoublePair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, IntDoublePair e) {
    modCount++;
    doAdd(index, e);
  }

  public IntDoublePair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public IntDoublePairVector() {
    this(AlignmentAllJNI.new_IntDoublePairVector__SWIG_0(), true);
  }

  public IntDoublePairVector(IntDoublePairVector other) {
    this(AlignmentAllJNI.new_IntDoublePairVector__SWIG_1(IntDoublePairVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.IntDoublePairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.IntDoublePairVector_clear(swigCPtr, this);
  }

  public IntDoublePairVector(int count, IntDoublePair value) {
    this(AlignmentAllJNI.new_IntDoublePairVector__SWIG_2(count, IntDoublePair.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.IntDoublePairVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.IntDoublePairVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.IntDoublePairVector_doSize(swigCPtr, this);
  }

  private void doAdd(IntDoublePair x) {
    AlignmentAllJNI.IntDoublePairVector_doAdd__SWIG_0(swigCPtr, this, IntDoublePair.getCPtr(x), x);
  }

  private void doAdd(int index, IntDoublePair x) {
    AlignmentAllJNI.IntDoublePairVector_doAdd__SWIG_1(swigCPtr, this, index, IntDoublePair.getCPtr(x), x);
  }

  private IntDoublePair doRemove(int index) {
    return new IntDoublePair(AlignmentAllJNI.IntDoublePairVector_doRemove(swigCPtr, this, index), true);
  }

  private IntDoublePair doGet(int index) {
    return new IntDoublePair(AlignmentAllJNI.IntDoublePairVector_doGet(swigCPtr, this, index), false);
  }

  private IntDoublePair doSet(int index, IntDoublePair val) {
    return new IntDoublePair(AlignmentAllJNI.IntDoublePairVector_doSet(swigCPtr, this, index, IntDoublePair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.IntDoublePairVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
