/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class IntDoublePair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntDoublePair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntDoublePair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IntDoublePair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_IntDoublePair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntDoublePair() {
    this(AlignmentAllJNI.new_IntDoublePair__SWIG_0(), true);
  }

  public IntDoublePair(int first, double second) {
    this(AlignmentAllJNI.new_IntDoublePair__SWIG_1(first, second), true);
  }

  public IntDoublePair(IntDoublePair other) {
    this(AlignmentAllJNI.new_IntDoublePair__SWIG_2(IntDoublePair.getCPtr(other), other), true);
  }

  public void setFirst(int value) {
    AlignmentAllJNI.IntDoublePair_first_set(swigCPtr, this, value);
  }

  public int getFirst() {
    return AlignmentAllJNI.IntDoublePair_first_get(swigCPtr, this);
  }

  public void setSecond(double value) {
    AlignmentAllJNI.IntDoublePair_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return AlignmentAllJNI.IntDoublePair_second_get(swigCPtr, this);
  }

}
