/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class InterPtArr extends java.util.AbstractList<ALIntersectionPoint> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InterPtArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InterPtArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(InterPtArr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_InterPtArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InterPtArr(ALIntersectionPoint[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ALIntersectionPoint element : initialElements) {
      add(element);
    }
  }

  public InterPtArr(Iterable<ALIntersectionPoint> initialElements) {
    this();
    for (ALIntersectionPoint element : initialElements) {
      add(element);
    }
  }

  public ALIntersectionPoint get(int index) {
    return doGet(index);
  }

  public ALIntersectionPoint set(int index, ALIntersectionPoint e) {
    return doSet(index, e);
  }

  public boolean add(ALIntersectionPoint e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ALIntersectionPoint e) {
    modCount++;
    doAdd(index, e);
  }

  public ALIntersectionPoint remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public InterPtArr() {
    this(AlignmentAllJNI.new_InterPtArr__SWIG_0(), true);
  }

  public InterPtArr(InterPtArr other) {
    this(AlignmentAllJNI.new_InterPtArr__SWIG_1(InterPtArr.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.InterPtArr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.InterPtArr_clear(swigCPtr, this);
  }

  public InterPtArr(int count, ALIntersectionPoint value) {
    this(AlignmentAllJNI.new_InterPtArr__SWIG_2(count, ALIntersectionPoint.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.InterPtArr_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.InterPtArr_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.InterPtArr_doSize(swigCPtr, this);
  }

  private void doAdd(ALIntersectionPoint x) {
    AlignmentAllJNI.InterPtArr_doAdd__SWIG_0(swigCPtr, this, ALIntersectionPoint.getCPtr(x), x);
  }

  private void doAdd(int index, ALIntersectionPoint x) {
    AlignmentAllJNI.InterPtArr_doAdd__SWIG_1(swigCPtr, this, index, ALIntersectionPoint.getCPtr(x), x);
  }

  private ALIntersectionPoint doRemove(int index) {
    return new ALIntersectionPoint(AlignmentAllJNI.InterPtArr_doRemove(swigCPtr, this, index), true);
  }

  private ALIntersectionPoint doGet(int index) {
    return new ALIntersectionPoint(AlignmentAllJNI.InterPtArr_doGet(swigCPtr, this, index), false);
  }

  private ALIntersectionPoint doSet(int index, ALIntersectionPoint val) {
    return new ALIntersectionPoint(AlignmentAllJNI.InterPtArr_doSet(swigCPtr, this, index, ALIntersectionPoint.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.InterPtArr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
