/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public final class InterType {
  public final static InterType ELE_NULL = new InterType("ELE_NULL", AlignmentAllJNI.InterType_ELE_NULL_get());
  public final static InterType ELE_PRE = new InterType("ELE_PRE", AlignmentAllJNI.InterType_ELE_PRE_get());
  public final static InterType ELE_SUB = new InterType("ELE_SUB", AlignmentAllJNI.InterType_ELE_SUB_get());
  public final static InterType ELE_BOTH = new InterType("ELE_BOTH", AlignmentAllJNI.InterType_ELE_BOTH_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static InterType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + InterType.class + " with value " + swigValue);
  }

  private InterType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private InterType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private InterType(String swigName, InterType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static InterType[] swigValues = { ELE_NULL, ELE_PRE, ELE_SUB, ELE_BOTH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

