/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class IntIntPairVector extends java.util.AbstractList<IntIntPair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntIntPairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntIntPairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IntIntPairVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_IntIntPairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntIntPairVector(IntIntPair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (IntIntPair element : initialElements) {
      add(element);
    }
  }

  public IntIntPairVector(Iterable<IntIntPair> initialElements) {
    this();
    for (IntIntPair element : initialElements) {
      add(element);
    }
  }

  public IntIntPair get(int index) {
    return doGet(index);
  }

  public IntIntPair set(int index, IntIntPair e) {
    return doSet(index, e);
  }

  public boolean add(IntIntPair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, IntIntPair e) {
    modCount++;
    doAdd(index, e);
  }

  public IntIntPair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public IntIntPairVector() {
    this(AlignmentAllJNI.new_IntIntPairVector__SWIG_0(), true);
  }

  public IntIntPairVector(IntIntPairVector other) {
    this(AlignmentAllJNI.new_IntIntPairVector__SWIG_1(IntIntPairVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.IntIntPairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.IntIntPairVector_clear(swigCPtr, this);
  }

  public IntIntPairVector(int count, IntIntPair value) {
    this(AlignmentAllJNI.new_IntIntPairVector__SWIG_2(count, IntIntPair.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.IntIntPairVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.IntIntPairVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.IntIntPairVector_doSize(swigCPtr, this);
  }

  private void doAdd(IntIntPair x) {
    AlignmentAllJNI.IntIntPairVector_doAdd__SWIG_0(swigCPtr, this, IntIntPair.getCPtr(x), x);
  }

  private void doAdd(int index, IntIntPair x) {
    AlignmentAllJNI.IntIntPairVector_doAdd__SWIG_1(swigCPtr, this, index, IntIntPair.getCPtr(x), x);
  }

  private IntIntPair doRemove(int index) {
    return new IntIntPair(AlignmentAllJNI.IntIntPairVector_doRemove(swigCPtr, this, index), true);
  }

  private IntIntPair doGet(int index) {
    return new IntIntPair(AlignmentAllJNI.IntIntPairVector_doGet(swigCPtr, this, index), false);
  }

  private IntIntPair doSet(int index, IntIntPair val) {
    return new IntIntPair(AlignmentAllJNI.IntIntPairVector_doSet(swigCPtr, this, index, IntIntPair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.IntIntPairVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
