/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SingleAlignmentBase {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected SingleAlignmentBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SingleAlignmentBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SingleAlignmentBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SingleAlignmentBase() {
    this(AlignmentAllJNI.new_SingleAlignmentBase__SWIG_0(), true);
  }

  public SingleAlignmentBase(SingleAlignmentBase singleLine) {
    this(AlignmentAllJNI.new_SingleAlignmentBase__SWIG_1(SingleAlignmentBase.getCPtr(singleLine), singleLine), true);
  }

  public SingleAlignmentBase GetCopy() {
    long cPtr = AlignmentAllJNI.SingleAlignmentBase_GetCopy(swigCPtr, this);
    return (cPtr == 0) ? null : new SingleAlignmentBase(cPtr, true);
  }

  public void CopyFrom(SingleAlignmentBase singleLine) {
    AlignmentAllJNI.SingleAlignmentBase_CopyFrom(swigCPtr, this, SingleAlignmentBase.getCPtr(singleLine), singleLine);
  }

  public void SetLineName(String lineName) {
    AlignmentAllJNI.SingleAlignmentBase_SetLineName(swigCPtr, this, lineName);
  }

  public String GetLineName() {
    return AlignmentAllJNI.SingleAlignmentBase_GetLineName(swigCPtr, this);
  }

  public void SetBaseLine(boolean isBaseLine, String baseLineName) {
    AlignmentAllJNI.SingleAlignmentBase_SetBaseLine(swigCPtr, this, isBaseLine, baseLineName);
  }

  public boolean IsBaseLine() {
    return AlignmentAllJNI.SingleAlignmentBase_IsBaseLine(swigCPtr, this);
  }

  public String GetBaseLineName() {
    return AlignmentAllJNI.SingleAlignmentBase_GetBaseLineName(swigCPtr, this);
  }

  public ALPoint3dArr Get3DPoints(double dMargin) {
    return new ALPoint3dArr(AlignmentAllJNI.SingleAlignmentBase_Get3DPoints(swigCPtr, this, dMargin), true);
  }

  public boolean CreateHoriByElement(ALElementPtrArr baseEle, ChainArr chains) {
    return AlignmentAllJNI.SingleAlignmentBase_CreateHoriByElement(swigCPtr, this, ALElementPtrArr.getCPtr(baseEle), baseEle, ChainArr.getCPtr(chains), chains);
  }

  public boolean CreateVertByElement(ALElementPtrArr baseEle) {
    return AlignmentAllJNI.SingleAlignmentBase_CreateVertByElement(swigCPtr, this, ALElementPtrArr.getCPtr(baseEle), baseEle);
  }

  public boolean ReplaceChains(ChainArr chains) {
    return AlignmentAllJNI.SingleAlignmentBase_ReplaceChains(swigCPtr, this, ChainArr.getCPtr(chains), chains);
  }

  public ChainArr GetChains() {
    return new ChainArr(AlignmentAllJNI.SingleAlignmentBase_GetChains(swigCPtr, this), true);
  }

  public boolean GetPointsOnRelease(ALPoint3dArr outPts, AL_Point3d stPt, AL_Vector3d stVec, double dRadius, double dLength, int dir, int type, double dMargin) {
    return AlignmentAllJNI.SingleAlignmentBase_GetPointsOnRelease(swigCPtr, this, ALPoint3dArr.getCPtr(outPts), outPts, AL_Point3d.getCPtr(stPt), stPt, AL_Vector3d.getCPtr(stVec), stVec, dRadius, dLength, dir, type, dMargin);
  }

  public boolean CreateVertByGradePts(GradeChangePointArr gcps, int mode) {
    return AlignmentAllJNI.SingleAlignmentBase_CreateVertByGradePts(swigCPtr, this, GradeChangePointArr.getCPtr(gcps), gcps, mode);
  }

  public InterPtArr GetIntersectionsPts() {
    return new InterPtArr(AlignmentAllJNI.SingleAlignmentBase_GetIntersectionsPts(swigCPtr, this), true);
  }

  public boolean GetIntersectionPt(ALIntersectionPoint pt, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_GetIntersectionPt(swigCPtr, this, ALIntersectionPoint.getCPtr(pt), pt, nIndex);
  }

  public int GetIntersectionPtCount() {
    return AlignmentAllJNI.SingleAlignmentBase_GetIntersectionPtCount(swigCPtr, this);
  }

  public boolean InsertIntersectionPoint(int nIndex, InterPtArr interPts, double dK1, double dK2, double dB1, double dB2) {
    return AlignmentAllJNI.SingleAlignmentBase_InsertIntersectionPoint__SWIG_0(swigCPtr, this, nIndex, InterPtArr.getCPtr(interPts), interPts, dK1, dK2, dB1, dB2);
  }

  public boolean InsertIntersectionPoint(int nIndex, InterPtArr interPts, AL_Point3d linept1, AL_Point3d linept2, AL_Vector3d linevec1, AL_Vector3d linevec2) {
    return AlignmentAllJNI.SingleAlignmentBase_InsertIntersectionPoint__SWIG_1(swigCPtr, this, nIndex, InterPtArr.getCPtr(interPts), interPts, AL_Point3d.getCPtr(linept1), linept1, AL_Point3d.getCPtr(linept2), linept2, AL_Vector3d.getCPtr(linevec1), linevec1, AL_Vector3d.getCPtr(linevec2), linevec2);
  }

  public GradeChangePointArr GetGradeChangePoints() {
    return new GradeChangePointArr(AlignmentAllJNI.SingleAlignmentBase_GetGradeChangePoints(swigCPtr, this), true);
  }

  public boolean GetGradeChangePoint(ALGradeChangePoint gcp, int index) {
    return AlignmentAllJNI.SingleAlignmentBase_GetGradeChangePoint(swigCPtr, this, ALGradeChangePoint.getCPtr(gcp), gcp, index);
  }

  public int GetGradeChangePointCount() {
    return AlignmentAllJNI.SingleAlignmentBase_GetGradeChangePointCount(swigCPtr, this);
  }

  public void SynchroneVertToHori(boolean isReal) {
    AlignmentAllJNI.SingleAlignmentBase_SynchroneVertToHori__SWIG_0(swigCPtr, this, isReal);
  }

  public void SynchroneVertToHori() {
    AlignmentAllJNI.SingleAlignmentBase_SynchroneVertToHori__SWIG_1(swigCPtr, this);
  }

  public void Overlaped(boolean isReal) {
    AlignmentAllJNI.SingleAlignmentBase_Overlaped__SWIG_0(swigCPtr, this, isReal);
  }

  public void Overlaped() {
    AlignmentAllJNI.SingleAlignmentBase_Overlaped__SWIG_1(swigCPtr, this);
  }

  public boolean CreateOffsetInterPtsByMargin(DoubleArr lineMargins, InterPtArr interPts, boolean isCreate) {
    return AlignmentAllJNI.SingleAlignmentBase_CreateOffsetInterPtsByMargin__SWIG_0(swigCPtr, this, DoubleArr.getCPtr(lineMargins), lineMargins, InterPtArr.getCPtr(interPts), interPts, isCreate);
  }

  public boolean CreateOffsetInterPtsByMargin(DoubleArr lineMargins, InterPtArr interPts) {
    return AlignmentAllJNI.SingleAlignmentBase_CreateOffsetInterPtsByMargin__SWIG_1(swigCPtr, this, DoubleArr.getCPtr(lineMargins), lineMargins, InterPtArr.getCPtr(interPts), interPts);
  }

  public boolean GetRangePointsHori(ALPoint3dArr points, ALVector3dArr vecs, double stML, double edML, double dMargin) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRangePointsHori__SWIG_0(swigCPtr, this, ALPoint3dArr.getCPtr(points), points, ALVector3dArr.getCPtr(vecs), vecs, stML, edML, dMargin);
  }

  public boolean GetRangePointsHori(ALPoint3dArr points, ALVector3dArr vecs, double stML, double edML) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRangePointsHori__SWIG_1(swigCPtr, this, ALPoint3dArr.getCPtr(points), points, ALVector3dArr.getCPtr(vecs), vecs, stML, edML);
  }

  public boolean GetRangePointsVert(ALPoint3dArr points, ALVector3dArr vecs, double stML, double edML, double dMargin) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRangePointsVert__SWIG_0(swigCPtr, this, ALPoint3dArr.getCPtr(points), points, ALVector3dArr.getCPtr(vecs), vecs, stML, edML, dMargin);
  }

  public boolean GetRangePointsVert(ALPoint3dArr points, ALVector3dArr vecs, double stML, double edML) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRangePointsVert__SWIG_1(swigCPtr, this, ALPoint3dArr.getCPtr(points), points, ALVector3dArr.getCPtr(vecs), vecs, stML, edML);
  }

  public boolean GetElementIndexByLc(SWIGTYPE_p_int nIndex, double dLc, boolean isHori) {
    return AlignmentAllJNI.SingleAlignmentBase_GetElementIndexByLc__SWIG_0(swigCPtr, this, SWIGTYPE_p_int.getCPtr(nIndex), dLc, isHori);
  }

  public boolean GetElementIndexByLc(SWIGTYPE_p_int nIndex, double dLc) {
    return AlignmentAllJNI.SingleAlignmentBase_GetElementIndexByLc__SWIG_1(swigCPtr, this, SWIGTYPE_p_int.getCPtr(nIndex), dLc);
  }

  public int FindInterPtIndex(AL_Point3d pt, double dTol) {
    return AlignmentAllJNI.SingleAlignmentBase_FindInterPtIndex__SWIG_0(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, dTol);
  }

  public int FindInterPtIndex(AL_Point3d pt) {
    return AlignmentAllJNI.SingleAlignmentBase_FindInterPtIndex__SWIG_1(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean MoveInterPt(AL_Point3d pt, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_MoveInterPt(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, nIndex);
  }

  public boolean ModifyInterPt(ALIntersectionPoint pt, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_ModifyInterPt(swigCPtr, this, ALIntersectionPoint.getCPtr(pt), pt, nIndex);
  }

  public boolean DeleteInterPt(int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_DeleteInterPt(swigCPtr, this, nIndex);
  }

  public boolean RotateLine(int nIndex, double dAngle, boolean isFixedFront) {
    return AlignmentAllJNI.SingleAlignmentBase_RotateLine__SWIG_0(swigCPtr, this, nIndex, dAngle, isFixedFront);
  }

  public boolean RotateLine(int nIndex, double dAngle) {
    return AlignmentAllJNI.SingleAlignmentBase_RotateLine__SWIG_1(swigCPtr, this, nIndex, dAngle);
  }

  public boolean RotateLineByFixedPt(int nIndex, double dMaigin, boolean isFixedFront) {
    return AlignmentAllJNI.SingleAlignmentBase_RotateLineByFixedPt__SWIG_0(swigCPtr, this, nIndex, dMaigin, isFixedFront);
  }

  public boolean RotateLineByFixedPt(int nIndex, double dMaigin) {
    return AlignmentAllJNI.SingleAlignmentBase_RotateLineByFixedPt__SWIG_1(swigCPtr, this, nIndex, dMaigin);
  }

  public int FindGCP(AL_Point3d pt, double dTol) {
    return AlignmentAllJNI.SingleAlignmentBase_FindGCP__SWIG_0(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, dTol);
  }

  public int FindGCP(AL_Point3d pt) {
    return AlignmentAllJNI.SingleAlignmentBase_FindGCP__SWIG_1(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean MoveGCP(double dRealLc, double dHeight, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_MoveGCP(swigCPtr, this, dRealLc, dHeight, nIndex);
  }

  public boolean ModifyVertRadius(double dRadius, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_ModifyVertRadius(swigCPtr, this, dRadius, nIndex);
  }

  public boolean DeleteGCP(int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_DeleteGCP(swigCPtr, this, nIndex);
  }

  public void ClearGCPs() {
    AlignmentAllJNI.SingleAlignmentBase_ClearGCPs(swigCPtr, this);
  }

  public boolean InsertGCP(ALGradeChangePoint curGCP) {
    return AlignmentAllJNI.SingleAlignmentBase_InsertGCP(swigCPtr, this, ALGradeChangePoint.getCPtr(curGCP), curGCP);
  }

  public boolean ModifySlope(double dLen, double dRate, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_ModifySlope(swigCPtr, this, dLen, dRate, nIndex);
  }

  public boolean ModifySlopeFixedBackPt(double dLen, double dRate, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_ModifySlopeFixedBackPt(swigCPtr, this, dLen, dRate, nIndex);
  }

  public DoubleDoublePair GetVertHeightRange() {
    return new DoubleDoublePair(AlignmentAllJNI.SingleAlignmentBase_GetVertHeightRange(swigCPtr, this), true);
  }

  public ALEvaluationVector CheckHoriLA(CStandCode code) {
    return new ALEvaluationVector(AlignmentAllJNI.SingleAlignmentBase_CheckHoriLA(swigCPtr, this, CStandCode.getCPtr(code), code), true);
  }

  public ALEvaluationVector CheckHoriArcLen(CStandCode code) {
    return new ALEvaluationVector(AlignmentAllJNI.SingleAlignmentBase_CheckHoriArcLen(swigCPtr, this, CStandCode.getCPtr(code), code), true);
  }

  public ALEvaluationVector CheckVertSlopeLen(CStandCode code) {
    return new ALEvaluationVector(AlignmentAllJNI.SingleAlignmentBase_CheckVertSlopeLen(swigCPtr, this, CStandCode.getCPtr(code), code), true);
  }

  public double GetAlignmentLength() {
    return AlignmentAllJNI.SingleAlignmentBase_GetAlignmentLength(swigCPtr, this);
  }

  public double GetAlignmentStartDM() {
    return AlignmentAllJNI.SingleAlignmentBase_GetAlignmentStartDM(swigCPtr, this);
  }

  public IntDoublePair GetAlignmentEndDM() {
    return new IntDoublePair(AlignmentAllJNI.SingleAlignmentBase_GetAlignmentEndDM(swigCPtr, this), true);
  }

  public void SetAlignmentStartDM(double dm) {
    AlignmentAllJNI.SingleAlignmentBase_SetAlignmentStartDM(swigCPtr, this, dm);
  }

  public double GetRMByDM(DisplayMileage dm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRMByDM__SWIG_0(swigCPtr, this, DisplayMileage.getCPtr(dm), dm);
  }

  public double GetRMByDM(double dm, int nIndex) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRMByDM__SWIG_1(swigCPtr, this, dm, nIndex);
  }

  public boolean GetDMByRM(DisplayMileage dm, double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetDMByRM__SWIG_0(swigCPtr, this, DisplayMileage.getCPtr(dm), dm, rm);
  }

  public DoubleIntPair GetDMByRM(double rm) {
    return new DoubleIntPair(AlignmentAllJNI.SingleAlignmentBase_GetDMByRM__SWIG_1(swigCPtr, this, rm), true);
  }

  public double GetGMByDM(DisplayMileage dm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetGMByDM(swigCPtr, this, DisplayMileage.getCPtr(dm), dm);
  }

  public boolean GetDMByGM(DisplayMileage dm, double gm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetDMByGM(swigCPtr, this, DisplayMileage.getCPtr(dm), dm, gm);
  }

  public double GetRMByGM(double gm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRMByGM(swigCPtr, this, gm);
  }

  public double GetGMByRM(double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetGMByRM(swigCPtr, this, rm);
  }

  public boolean GetPointByRM(AL_Point3d pt, double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetPointByRM(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, rm);
  }

  public boolean GetPointByDM(AL_Point3d pt, DisplayMileage dm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetPointByDM(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, DisplayMileage.getCPtr(dm), dm);
  }

  public boolean GetTangentVectorByRM(AL_Vector3d vec, double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetTangentVectorByRM(swigCPtr, this, AL_Vector3d.getCPtr(vec), vec, rm);
  }

  public boolean GetPtAndVecByRM(AL_Point3d pt, AL_Vector3d vec, double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetPtAndVecByRM(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, AL_Vector3d.getCPtr(vec), vec, rm);
  }

  public boolean GetTangentVectorByDM(AL_Vector3d vec, DisplayMileage dm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetTangentVectorByDM(swigCPtr, this, AL_Vector3d.getCPtr(vec), vec, DisplayMileage.getCPtr(dm), dm);
  }

  public double GetRMByPoint(AL_Point3d pt) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRMByPoint(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public DoubleDoublePair GetPerPointByOutPoint(AL_Point3d perPt, AL_Vector3d tanVec, AL_Point3d outPt) {
    return new DoubleDoublePair(AlignmentAllJNI.SingleAlignmentBase_GetPerPointByOutPoint(swigCPtr, this, AL_Point3d.getCPtr(perPt), perPt, AL_Vector3d.getCPtr(tanVec), tanVec, AL_Point3d.getCPtr(outPt), outPt), true);
  }

  public ALElementPtrArr GetHoriElements() {
    return new ALElementPtrArr(AlignmentAllJNI.SingleAlignmentBase_GetHoriElements__SWIG_0(swigCPtr, this), true);
  }

  public ALElementPtrArr GetVertElements() {
    return new ALElementPtrArr(AlignmentAllJNI.SingleAlignmentBase_GetVertElements__SWIG_0(swigCPtr, this), true);
  }

  public boolean GetHoriElements(ALElementPtrArr horiEles) {
    return AlignmentAllJNI.SingleAlignmentBase_GetHoriElements__SWIG_1(swigCPtr, this, ALElementPtrArr.getCPtr(horiEles), horiEles);
  }

  public boolean GetVertElements(ALElementPtrArr vertEles) {
    return AlignmentAllJNI.SingleAlignmentBase_GetVertElements__SWIG_1(swigCPtr, this, ALElementPtrArr.getCPtr(vertEles), vertEles);
  }

  public double GetDesignHeightByRM(double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetDesignHeightByRM(swigCPtr, this, rm);
  }

  public double GetRealHeightByRM(double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRealHeightByRM__SWIG_0(swigCPtr, this, rm);
  }

  public double GetRealHeightByRM(int[] type, double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRealHeightByRM__SWIG_1(swigCPtr, this, type, rm);
  }

  public double GetDesignHeightByDM(DisplayMileage dm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetDesignHeightByDM(swigCPtr, this, DisplayMileage.getCPtr(dm), dm);
  }

  public double GetRealHeightByDM(DisplayMileage dm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRealHeightByDM__SWIG_0(swigCPtr, this, DisplayMileage.getCPtr(dm), dm);
  }

  public double GetRealHeightByDM(int[] type, DisplayMileage dm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetRealHeightByDM__SWIG_1(swigCPtr, this, type, DisplayMileage.getCPtr(dm), dm);
  }

  public int GetClosedInterPt(AL_Point3d outPt) {
    return AlignmentAllJNI.SingleAlignmentBase_GetClosedInterPt(swigCPtr, this, AL_Point3d.getCPtr(outPt), outPt);
  }

  public double GetSuperEleByRM(double rm) {
    return AlignmentAllJNI.SingleAlignmentBase_GetSuperEleByRM(swigCPtr, this, rm);
  }

  public void SetSuperEleRangeByRelease() {
    AlignmentAllJNI.SingleAlignmentBase_SetSuperEleRangeByRelease(swigCPtr, this);
  }

  public boolean SetSuperEleData(InterPtArr superEleData) {
    return AlignmentAllJNI.SingleAlignmentBase_SetSuperEleData(swigCPtr, this, InterPtArr.getCPtr(superEleData), superEleData);
  }

  public boolean ExportGeoData(String filePath, IntArr inValidIndexs, boolean isVert) {
    return AlignmentAllJNI.SingleAlignmentBase_ExportGeoData__SWIG_0(swigCPtr, this, filePath, IntArr.getCPtr(inValidIndexs), inValidIndexs, isVert);
  }

  public boolean ExportGeoData(String filePath, IntArr inValidIndexs) {
    return AlignmentAllJNI.SingleAlignmentBase_ExportGeoData__SWIG_1(swigCPtr, this, filePath, IntArr.getCPtr(inValidIndexs), inValidIndexs);
  }

  public boolean GetMilegaeMarksbyRM(DoubleArr dRealM, IntArr nMarks, StringArr keyWord) {
    return AlignmentAllJNI.SingleAlignmentBase_GetMilegaeMarksbyRM(swigCPtr, this, DoubleArr.getCPtr(dRealM), dRealM, IntArr.getCPtr(nMarks), nMarks, StringArr.getCPtr(keyWord), keyWord);
  }

  public boolean GetMilageMarksbyPoint(IntArr nMarks, ALVector3dArr vecs, ALPoint3dArr pts, StringArr keyWord) {
    return AlignmentAllJNI.SingleAlignmentBase_GetMilageMarksbyPoint(swigCPtr, this, IntArr.getCPtr(nMarks), nMarks, ALVector3dArr.getCPtr(vecs), vecs, ALPoint3dArr.getCPtr(pts), pts, StringArr.getCPtr(keyWord), keyWord);
  }

}
