/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SplitIndex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SplitIndex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SplitIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SplitIndex obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SplitIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SplitIndex() {
    this(AlignmentAllJNI.new_SplitIndex__SWIG_0(), true);
  }

  public SplitIndex(int nZH, int nHY, int nYH, int nHZ) {
    this(AlignmentAllJNI.new_SplitIndex__SWIG_1(nZH, nHY, nYH, nHZ), true);
  }

  public void setZHIndex(int value) {
    AlignmentAllJNI.SplitIndex_ZHIndex_set(swigCPtr, this, value);
  }

  public int getZHIndex() {
    return AlignmentAllJNI.SplitIndex_ZHIndex_get(swigCPtr, this);
  }

  public void setHYIndex(int value) {
    AlignmentAllJNI.SplitIndex_HYIndex_set(swigCPtr, this, value);
  }

  public int getHYIndex() {
    return AlignmentAllJNI.SplitIndex_HYIndex_get(swigCPtr, this);
  }

  public void setYHIndex(int value) {
    AlignmentAllJNI.SplitIndex_YHIndex_set(swigCPtr, this, value);
  }

  public int getYHIndex() {
    return AlignmentAllJNI.SplitIndex_YHIndex_get(swigCPtr, this);
  }

  public void setHZIndex(int value) {
    AlignmentAllJNI.SplitIndex_HZIndex_set(swigCPtr, this, value);
  }

  public int getHZIndex() {
    return AlignmentAllJNI.SplitIndex_HZIndex_get(swigCPtr, this);
  }

  public void setCenterPt(AL_Point3d value) {
    AlignmentAllJNI.SplitIndex_centerPt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getCenterPt() {
    long cPtr = AlignmentAllJNI.SplitIndex_centerPt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setDRadius(double value) {
    AlignmentAllJNI.SplitIndex_dRadius_set(swigCPtr, this, value);
  }

  public double getDRadius() {
    return AlignmentAllJNI.SplitIndex_dRadius_get(swigCPtr, this);
  }

}
