/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class StaticsDataHori {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StaticsDataHori(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StaticsDataHori obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StaticsDataHori obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_StaticsDataHori(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StaticsDataHori() {
    this(AlignmentAllJNI.new_StaticsDataHori__SWIG_0(), true);
  }

  public StaticsDataHori(int nCount) {
    this(AlignmentAllJNI.new_StaticsDataHori__SWIG_1(nCount), true);
  }

  public void setM_Indexs_HLine_Min(IntArr value) {
    AlignmentAllJNI.StaticsDataHori_m_Indexs_HLine_Min_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Indexs_HLine_Min() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_Indexs_HLine_Min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_Indexs_HCurve_Min(IntArr value) {
    AlignmentAllJNI.StaticsDataHori_m_Indexs_HCurve_Min_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Indexs_HCurve_Min() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_Indexs_HCurve_Min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_Indexs_HLine_Max(IntArr value) {
    AlignmentAllJNI.StaticsDataHori_m_Indexs_HLine_Max_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Indexs_HLine_Max() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_Indexs_HLine_Max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_Indexs_HCurve_Max(IntArr value) {
    AlignmentAllJNI.StaticsDataHori_m_Indexs_HCurve_Max_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Indexs_HCurve_Max() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_Indexs_HCurve_Max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_Count_Lines(IntArr value) {
    AlignmentAllJNI.StaticsDataHori_m_Count_Lines_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Count_Lines() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_Count_Lines_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_Count_Curves(IntArr value) {
    AlignmentAllJNI.StaticsDataHori_m_Count_Curves_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Count_Curves() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_Count_Curves_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_VarOfLine(DoubleArr value) {
    AlignmentAllJNI.StaticsDataHori_m_VarOfLine_set(swigCPtr, this, DoubleArr.getCPtr(value), value);
  }

  public DoubleArr getM_VarOfLine() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_VarOfLine_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleArr(cPtr, false);
  }

  public void setM_VarOfCurve(DoubleArr value) {
    AlignmentAllJNI.StaticsDataHori_m_VarOfCurve_set(swigCPtr, this, DoubleArr.getCPtr(value), value);
  }

  public DoubleArr getM_VarOfCurve() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_VarOfCurve_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleArr(cPtr, false);
  }

  public void setM_MarginOfLine(DoubleArr value) {
    AlignmentAllJNI.StaticsDataHori_m_MarginOfLine_set(swigCPtr, this, DoubleArr.getCPtr(value), value);
  }

  public DoubleArr getM_MarginOfLine() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_MarginOfLine_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleArr(cPtr, false);
  }

  public void setM_MarginOfCurve(DoubleArr value) {
    AlignmentAllJNI.StaticsDataHori_m_MarginOfCurve_set(swigCPtr, this, DoubleArr.getCPtr(value), value);
  }

  public DoubleArr getM_MarginOfCurve() {
    long cPtr = AlignmentAllJNI.StaticsDataHori_m_MarginOfCurve_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleArr(cPtr, false);
  }

  public void setM_SumOfVar(double value) {
    AlignmentAllJNI.StaticsDataHori_m_SumOfVar_set(swigCPtr, this, value);
  }

  public double getM_SumOfVar() {
    return AlignmentAllJNI.StaticsDataHori_m_SumOfVar_get(swigCPtr, this);
  }

  public void setM_AverOfMargin(double value) {
    AlignmentAllJNI.StaticsDataHori_m_AverOfMargin_set(swigCPtr, this, value);
  }

  public double getM_AverOfMargin() {
    return AlignmentAllJNI.StaticsDataHori_m_AverOfMargin_get(swigCPtr, this);
  }

  public void setM_AverOfVar(double value) {
    AlignmentAllJNI.StaticsDataHori_m_AverOfVar_set(swigCPtr, this, value);
  }

  public double getM_AverOfVar() {
    return AlignmentAllJNI.StaticsDataHori_m_AverOfVar_get(swigCPtr, this);
  }

  public void Clear() {
    AlignmentAllJNI.StaticsDataHori_Clear(swigCPtr, this);
  }

}
