/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class StaticsDataVert {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StaticsDataVert(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StaticsDataVert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StaticsDataVert obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_StaticsDataVert(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StaticsDataVert() {
    this(AlignmentAllJNI.new_StaticsDataVert(), true);
  }

  public void setM_Indexs_Min(IntArr value) {
    AlignmentAllJNI.StaticsDataVert_m_Indexs_Min_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Indexs_Min() {
    long cPtr = AlignmentAllJNI.StaticsDataVert_m_Indexs_Min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_Indexs_Max(IntArr value) {
    AlignmentAllJNI.StaticsDataVert_m_Indexs_Max_set(swigCPtr, this, IntArr.getCPtr(value), value);
  }

  public IntArr getM_Indexs_Max() {
    long cPtr = AlignmentAllJNI.StaticsDataVert_m_Indexs_Max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntArr(cPtr, false);
  }

  public void setM_VarOfSlope(DoubleArr value) {
    AlignmentAllJNI.StaticsDataVert_m_VarOfSlope_set(swigCPtr, this, DoubleArr.getCPtr(value), value);
  }

  public DoubleArr getM_VarOfSlope() {
    long cPtr = AlignmentAllJNI.StaticsDataVert_m_VarOfSlope_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleArr(cPtr, false);
  }

  public void setM_MarginOfSlope(DoubleArr value) {
    AlignmentAllJNI.StaticsDataVert_m_MarginOfSlope_set(swigCPtr, this, DoubleArr.getCPtr(value), value);
  }

  public DoubleArr getM_MarginOfSlope() {
    long cPtr = AlignmentAllJNI.StaticsDataVert_m_MarginOfSlope_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleArr(cPtr, false);
  }

  public void setM_SumOfVar(double value) {
    AlignmentAllJNI.StaticsDataVert_m_SumOfVar_set(swigCPtr, this, value);
  }

  public double getM_SumOfVar() {
    return AlignmentAllJNI.StaticsDataVert_m_SumOfVar_get(swigCPtr, this);
  }

  public void setM_AverOfMargin(double value) {
    AlignmentAllJNI.StaticsDataVert_m_AverOfMargin_set(swigCPtr, this, value);
  }

  public double getM_AverOfMargin() {
    return AlignmentAllJNI.StaticsDataVert_m_AverOfMargin_get(swigCPtr, this);
  }

  public void setM_AverOfVar(double value) {
    AlignmentAllJNI.StaticsDataVert_m_AverOfVar_set(swigCPtr, this, value);
  }

  public double getM_AverOfVar() {
    return AlignmentAllJNI.StaticsDataVert_m_AverOfVar_get(swigCPtr, this);
  }

  public void Clear() {
    AlignmentAllJNI.StaticsDataVert_Clear(swigCPtr, this);
  }

}
