/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SuperCheckData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SuperCheckData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SuperCheckData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SuperCheckData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SuperCheckData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SuperCheckData() {
    this(AlignmentAllJNI.new_SuperCheckData__SWIG_0(), true);
  }

  public SuperCheckData(double under, double over, double rateFront, double rateBack) {
    this(AlignmentAllJNI.new_SuperCheckData__SWIG_1(under, over, rateFront, rateBack), true);
  }

  public void setDUnderEle(double value) {
    AlignmentAllJNI.SuperCheckData_dUnderEle_set(swigCPtr, this, value);
  }

  public double getDUnderEle() {
    return AlignmentAllJNI.SuperCheckData_dUnderEle_get(swigCPtr, this);
  }

  public void setDOverEle(double value) {
    AlignmentAllJNI.SuperCheckData_dOverEle_set(swigCPtr, this, value);
  }

  public double getDOverEle() {
    return AlignmentAllJNI.SuperCheckData_dOverEle_get(swigCPtr, this);
  }

  public void setDRateEleFront(double value) {
    AlignmentAllJNI.SuperCheckData_dRateEleFront_set(swigCPtr, this, value);
  }

  public double getDRateEleFront() {
    return AlignmentAllJNI.SuperCheckData_dRateEleFront_get(swigCPtr, this);
  }

  public void setDRateEleBack(double value) {
    AlignmentAllJNI.SuperCheckData_dRateEleBack_set(swigCPtr, this, value);
  }

  public double getDRateEleBack() {
    return AlignmentAllJNI.SuperCheckData_dRateEleBack_get(swigCPtr, this);
  }

}
