/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SurveyVector extends java.util.AbstractList<SurveyImfo> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SurveyVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SurveyVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SurveyVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SurveyVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SurveyVector(SurveyImfo[] initialElements) {
    this();
    reserve(initialElements.length);

    for (SurveyImfo element : initialElements) {
      add(element);
    }
  }

  public SurveyVector(Iterable<SurveyImfo> initialElements) {
    this();
    for (SurveyImfo element : initialElements) {
      add(element);
    }
  }

  public SurveyImfo get(int index) {
    return doGet(index);
  }

  public SurveyImfo set(int index, SurveyImfo e) {
    return doSet(index, e);
  }

  public boolean add(SurveyImfo e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SurveyImfo e) {
    modCount++;
    doAdd(index, e);
  }

  public SurveyImfo remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public SurveyVector() {
    this(AlignmentAllJNI.new_SurveyVector__SWIG_0(), true);
  }

  public SurveyVector(SurveyVector other) {
    this(AlignmentAllJNI.new_SurveyVector__SWIG_1(SurveyVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.SurveyVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.SurveyVector_clear(swigCPtr, this);
  }

  public SurveyVector(int count, SurveyImfo value) {
    this(AlignmentAllJNI.new_SurveyVector__SWIG_2(count, SurveyImfo.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.SurveyVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.SurveyVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.SurveyVector_doSize(swigCPtr, this);
  }

  private void doAdd(SurveyImfo x) {
    AlignmentAllJNI.SurveyVector_doAdd__SWIG_0(swigCPtr, this, SurveyImfo.getCPtr(x), x);
  }

  private void doAdd(int index, SurveyImfo x) {
    AlignmentAllJNI.SurveyVector_doAdd__SWIG_1(swigCPtr, this, index, SurveyImfo.getCPtr(x), x);
  }

  private SurveyImfo doRemove(int index) {
    return new SurveyImfo(AlignmentAllJNI.SurveyVector_doRemove(swigCPtr, this, index), true);
  }

  private SurveyImfo doGet(int index) {
    return new SurveyImfo(AlignmentAllJNI.SurveyVector_doGet(swigCPtr, this, index), false);
  }

  private SurveyImfo doSet(int index, SurveyImfo val) {
    return new SurveyImfo(AlignmentAllJNI.SurveyVector_doSet(swigCPtr, this, index, SurveyImfo.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.SurveyVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
