/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public final class SURVEYTYPE {
  public final static int LEFT = 0;
  public final static int RIGHT = 1;
  public final static int CENTER = 2;
  public final static int HEIGHTRAIL = 3;
  public final static int LOWRAIL = 4;
}

