/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SurveyParaVert {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SurveyParaVert(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SurveyParaVert obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SurveyParaVert obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SurveyParaVert(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SurveyParaVert() {
    this(AlignmentAllJNI.new_SurveyParaVert(), true);
  }

  public void setM_V_minLength(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_minLength_set(swigCPtr, this, value);
  }

  public double getM_V_minLength() {
    return AlignmentAllJNI.SurveyParaVert_m_V_minLength_get(swigCPtr, this);
  }

  public void setM_V_upLimit(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_upLimit_set(swigCPtr, this, value);
  }

  public double getM_V_upLimit() {
    return AlignmentAllJNI.SurveyParaVert_m_V_upLimit_get(swigCPtr, this);
  }

  public void setM_V_downLimit(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_downLimit_set(swigCPtr, this, value);
  }

  public double getM_V_downLimit() {
    return AlignmentAllJNI.SurveyParaVert_m_V_downLimit_get(swigCPtr, this);
  }

  public void setM_V_Radius_Max(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Radius_Max_set(swigCPtr, this, value);
  }

  public double getM_V_Radius_Max() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Radius_Max_get(swigCPtr, this);
  }

  public void setM_V_Radius_Min(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Radius_Min_set(swigCPtr, this, value);
  }

  public double getM_V_Radius_Min() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Radius_Min_get(swigCPtr, this);
  }

  public void setM_V_Check_rateMargin(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Check_rateMargin_set(swigCPtr, this, value);
  }

  public double getM_V_Check_rateMargin() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Check_rateMargin_get(swigCPtr, this);
  }

  public void setM_V_Check_upLimit(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Check_upLimit_set(swigCPtr, this, value);
  }

  public double getM_V_Check_upLimit() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Check_upLimit_get(swigCPtr, this);
  }

  public void setM_V_Check_downLimit(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Check_downLimit_set(swigCPtr, this, value);
  }

  public double getM_V_Check_downLimit() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Check_downLimit_get(swigCPtr, this);
  }

  public void setM_V_Curvature_Margin(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Curvature_Margin_set(swigCPtr, this, value);
  }

  public double getM_V_Curvature_Margin() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Curvature_Margin_get(swigCPtr, this);
  }

  public void setM_V_Curvature_Weight_Margin(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Curvature_Weight_Margin_set(swigCPtr, this, value);
  }

  public double getM_V_Curvature_Weight_Margin() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Curvature_Weight_Margin_get(swigCPtr, this);
  }

  public void setM_V_Chord_Length(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Chord_Length_set(swigCPtr, this, value);
  }

  public double getM_V_Chord_Length() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Chord_Length_get(swigCPtr, this);
  }

  public void setM_overhead_V_limit(double value) {
    AlignmentAllJNI.SurveyParaVert_m_overhead_V_limit_set(swigCPtr, this, value);
  }

  public double getM_overhead_V_limit() {
    return AlignmentAllJNI.SurveyParaVert_m_overhead_V_limit_get(swigCPtr, this);
  }

  public void setM_overhead_H_limit(double value) {
    AlignmentAllJNI.SurveyParaVert_m_overhead_H_limit_set(swigCPtr, this, value);
  }

  public double getM_overhead_H_limit() {
    return AlignmentAllJNI.SurveyParaVert_m_overhead_H_limit_get(swigCPtr, this);
  }

  public void setM_V_Keep_Rate(int value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Keep_Rate_set(swigCPtr, this, value);
  }

  public int getM_V_Keep_Rate() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Keep_Rate_get(swigCPtr, this);
  }

  public void setM_V_Keep_Lc(double value) {
    AlignmentAllJNI.SurveyParaVert_m_V_Keep_Lc_set(swigCPtr, this, value);
  }

  public double getM_V_Keep_Lc() {
    return AlignmentAllJNI.SurveyParaVert_m_V_Keep_Lc_get(swigCPtr, this);
  }

}
