/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SurveyParaHori {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SurveyParaHori(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SurveyParaHori obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SurveyParaHori obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SurveyParaHori(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SurveyParaHori() {
    this(AlignmentAllJNI.new_SurveyParaHori(), true);
  }

  public void setM_H_LinearIndentify_ChordLength(double value) {
    AlignmentAllJNI.SurveyParaHori_m_H_LinearIndentify_ChordLength_set(swigCPtr, this, value);
  }

  public double getM_H_LinearIndentify_ChordLength() {
    return AlignmentAllJNI.SurveyParaHori_m_H_LinearIndentify_ChordLength_get(swigCPtr, this);
  }

  public void setM_H_LinearIndentify_RadiusUp(double value) {
    AlignmentAllJNI.SurveyParaHori_m_H_LinearIndentify_RadiusUp_set(swigCPtr, this, value);
  }

  public double getM_H_LinearIndentify_RadiusUp() {
    return AlignmentAllJNI.SurveyParaHori_m_H_LinearIndentify_RadiusUp_get(swigCPtr, this);
  }

  public void setM_H_LinearIndentify_RadiusDown(double value) {
    AlignmentAllJNI.SurveyParaHori_m_H_LinearIndentify_RadiusDown_set(swigCPtr, this, value);
  }

  public double getM_H_LinearIndentify_RadiusDown() {
    return AlignmentAllJNI.SurveyParaHori_m_H_LinearIndentify_RadiusDown_get(swigCPtr, this);
  }

  public void setM_H_Radius_Precision(double value) {
    AlignmentAllJNI.SurveyParaHori_m_H_Radius_Precision_set(swigCPtr, this, value);
  }

  public double getM_H_Radius_Precision() {
    return AlignmentAllJNI.SurveyParaHori_m_H_Radius_Precision_get(swigCPtr, this);
  }

  public void setM_H_Spiral_Precision(double value) {
    AlignmentAllJNI.SurveyParaHori_m_H_Spiral_Precision_set(swigCPtr, this, value);
  }

  public double getM_H_Spiral_Precision() {
    return AlignmentAllJNI.SurveyParaHori_m_H_Spiral_Precision_get(swigCPtr, this);
  }

  public void setM_H_Average_MileageMargin(double value) {
    AlignmentAllJNI.SurveyParaHori_m_H_Average_MileageMargin_set(swigCPtr, this, value);
  }

  public double getM_H_Average_MileageMargin() {
    return AlignmentAllJNI.SurveyParaHori_m_H_Average_MileageMargin_get(swigCPtr, this);
  }

  public void setM_H_Vacuate_Length(double value) {
    AlignmentAllJNI.SurveyParaHori_m_H_Vacuate_Length_set(swigCPtr, this, value);
  }

  public double getM_H_Vacuate_Length() {
    return AlignmentAllJNI.SurveyParaHori_m_H_Vacuate_Length_get(swigCPtr, this);
  }

}
