/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SurveyDatas {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected SurveyDatas(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SurveyDatas obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SurveyDatas(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SurveyDatas() {
    this(AlignmentAllJNI.new_SurveyDatas__SWIG_0(), true);
  }

  public SurveyDatas(SurveyVector datas, int type) {
    this(AlignmentAllJNI.new_SurveyDatas__SWIG_1(SurveyVector.getCPtr(datas), datas, type), true);
  }

  public SurveyDatas(SurveyDatas datas) {
    this(AlignmentAllJNI.new_SurveyDatas__SWIG_2(SurveyDatas.getCPtr(datas), datas), true);
  }

  public IntDoublePairVector GetCurvation(double dChordLen, double dMargin) {
    return new IntDoublePairVector(AlignmentAllJNI.SurveyDatas_GetCurvation__SWIG_0(swigCPtr, this, dChordLen, dMargin), true);
  }

  public IntDoublePairVector GetCurvation(double dChordLen) {
    return new IntDoublePairVector(AlignmentAllJNI.SurveyDatas_GetCurvation__SWIG_1(swigCPtr, this, dChordLen), true);
  }

  public boolean AutoKeyPts(double dChordLen, double dMargin) {
    return AlignmentAllJNI.SurveyDatas_AutoKeyPts__SWIG_0(swigCPtr, this, dChordLen, dMargin);
  }

  public boolean AutoKeyPts(double dChordLen) {
    return AlignmentAllJNI.SurveyDatas_AutoKeyPts__SWIG_1(swigCPtr, this, dChordLen);
  }

  public boolean AddKeyPts(AL_Point3d pt) {
    return AlignmentAllJNI.SurveyDatas_AddKeyPts(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean DelKetPts(AL_Point3d pt, double dTol) {
    return AlignmentAllJNI.SurveyDatas_DelKetPts__SWIG_0(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, dTol);
  }

  public boolean DelKetPts(AL_Point3d pt) {
    return AlignmentAllJNI.SurveyDatas_DelKetPts__SWIG_1(swigCPtr, this, AL_Point3d.getCPtr(pt), pt);
  }

  public boolean MoveKeyPts(AL_Point3d pt, AL_Point3d ptNew, double dTol) {
    return AlignmentAllJNI.SurveyDatas_MoveKeyPts__SWIG_0(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, AL_Point3d.getCPtr(ptNew), ptNew, dTol);
  }

  public boolean MoveKeyPts(AL_Point3d pt, AL_Point3d ptNew) {
    return AlignmentAllJNI.SurveyDatas_MoveKeyPts__SWIG_1(swigCPtr, this, AL_Point3d.getCPtr(pt), pt, AL_Point3d.getCPtr(ptNew), ptNew);
  }

  public boolean GetKeyPts(IntIntPairVector vecKeyPts) {
    return AlignmentAllJNI.SurveyDatas_GetKeyPts(swigCPtr, this, IntIntPairVector.getCPtr(vecKeyPts), vecKeyPts);
  }

  public void ReCalGMileage() {
    AlignmentAllJNI.SurveyDatas_ReCalGMileage(swigCPtr, this);
  }

  public void setM_SurveyImfos(SurveyVector value) {
    AlignmentAllJNI.SurveyDatas_m_SurveyImfos_set(swigCPtr, this, SurveyVector.getCPtr(value), value);
  }

  public SurveyVector getM_SurveyImfos() {
    long cPtr = AlignmentAllJNI.SurveyDatas_m_SurveyImfos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SurveyVector(cPtr, false);
  }

  public void setM_keyPts(DoubleIntPairVector value) {
    AlignmentAllJNI.SurveyDatas_m_keyPts_set(swigCPtr, this, DoubleIntPairVector.getCPtr(value), value);
  }

  public DoubleIntPairVector getM_keyPts() {
    long cPtr = AlignmentAllJNI.SurveyDatas_m_keyPts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleIntPairVector(cPtr, false);
  }

  public void setM_SurveyType(int value) {
    AlignmentAllJNI.SurveyDatas_m_SurveyType_set(swigCPtr, this, value);
  }

  public int getM_SurveyType() {
    return AlignmentAllJNI.SurveyDatas_m_SurveyType_get(swigCPtr, this);
  }

}
