/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class SurveyImfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SurveyImfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SurveyImfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SurveyImfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_SurveyImfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SurveyImfo() {
    this(AlignmentAllJNI.new_SurveyImfo__SWIG_0(), true);
  }

  public SurveyImfo(AL_Point3d ptCor, double dMileage, double gauge, double dSuperEleS) {
    this(AlignmentAllJNI.new_SurveyImfo__SWIG_1(AL_Point3d.getCPtr(ptCor), ptCor, dMileage, gauge, dSuperEleS), true);
  }

  public SurveyImfo(AL_Point3d ptCor, double dMileage, double gauge) {
    this(AlignmentAllJNI.new_SurveyImfo__SWIG_2(AL_Point3d.getCPtr(ptCor), ptCor, dMileage, gauge), true);
  }

  public SurveyImfo(AL_Point3d ptCor, double dMileage) {
    this(AlignmentAllJNI.new_SurveyImfo__SWIG_3(AL_Point3d.getCPtr(ptCor), ptCor, dMileage), true);
  }

  public void setM_content(String value) {
    AlignmentAllJNI.SurveyImfo_m_content_set(swigCPtr, this, value);
  }

  public String getM_content() {
    return AlignmentAllJNI.SurveyImfo_m_content_get(swigCPtr, this);
  }

  public void setM_surveyPoint(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_surveyPoint_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_surveyPoint() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_surveyPoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_H_type(int value) {
    AlignmentAllJNI.SurveyImfo_m_H_type_set(swigCPtr, this, value);
  }

  public int getM_H_type() {
    return AlignmentAllJNI.SurveyImfo_m_H_type_get(swigCPtr, this);
  }

  public void setM_Direction(int value) {
    AlignmentAllJNI.SurveyImfo_m_Direction_set(swigCPtr, this, value);
  }

  public int getM_Direction() {
    return AlignmentAllJNI.SurveyImfo_m_Direction_get(swigCPtr, this);
  }

  public void setM_V_type(int value) {
    AlignmentAllJNI.SurveyImfo_m_V_type_set(swigCPtr, this, value);
  }

  public int getM_V_type() {
    return AlignmentAllJNI.SurveyImfo_m_V_type_get(swigCPtr, this);
  }

  public void setM_mileage(double value) {
    AlignmentAllJNI.SurveyImfo_m_mileage_set(swigCPtr, this, value);
  }

  public double getM_mileage() {
    return AlignmentAllJNI.SurveyImfo_m_mileage_get(swigCPtr, this);
  }

  public void setM_mileage_Survey(double value) {
    AlignmentAllJNI.SurveyImfo_m_mileage_Survey_set(swigCPtr, this, value);
  }

  public double getM_mileage_Survey() {
    return AlignmentAllJNI.SurveyImfo_m_mileage_Survey_get(swigCPtr, this);
  }

  public void setM_Mileage_Origin(double value) {
    AlignmentAllJNI.SurveyImfo_m_Mileage_Origin_set(swigCPtr, this, value);
  }

  public double getM_Mileage_Origin() {
    return AlignmentAllJNI.SurveyImfo_m_Mileage_Origin_get(swigCPtr, this);
  }

  public void setM_InterPointIndex(int value) {
    AlignmentAllJNI.SurveyImfo_m_InterPointIndex_set(swigCPtr, this, value);
  }

  public int getM_InterPointIndex() {
    return AlignmentAllJNI.SurveyImfo_m_InterPointIndex_get(swigCPtr, this);
  }

  public void setM_mileage_Display(DisplayMileage value) {
    AlignmentAllJNI.SurveyImfo_m_mileage_Display_set(swigCPtr, this, DisplayMileage.getCPtr(value), value);
  }

  public DisplayMileage getM_mileage_Display() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_mileage_Display_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DisplayMileage(cPtr, false);
  }

  public void setM_V_curvature(double value) {
    AlignmentAllJNI.SurveyImfo_m_V_curvature_set(swigCPtr, this, value);
  }

  public double getM_V_curvature() {
    return AlignmentAllJNI.SurveyImfo_m_V_curvature_get(swigCPtr, this);
  }

  public void setM_SuperEle_Survey(double value) {
    AlignmentAllJNI.SurveyImfo_m_SuperEle_Survey_set(swigCPtr, this, value);
  }

  public double getM_SuperEle_Survey() {
    return AlignmentAllJNI.SurveyImfo_m_SuperEle_Survey_get(swigCPtr, this);
  }

  public void setM_SuperEle_Design(double value) {
    AlignmentAllJNI.SurveyImfo_m_SuperEle_Design_set(swigCPtr, this, value);
  }

  public double getM_SuperEle_Design() {
    return AlignmentAllJNI.SurveyImfo_m_SuperEle_Design_get(swigCPtr, this);
  }

  public void setM_nGCPIndex(int value) {
    AlignmentAllJNI.SurveyImfo_m_nGCPIndex_set(swigCPtr, this, value);
  }

  public int getM_nGCPIndex() {
    return AlignmentAllJNI.SurveyImfo_m_nGCPIndex_get(swigCPtr, this);
  }

  public void setM_H_margin(double value) {
    AlignmentAllJNI.SurveyImfo_m_H_margin_set(swigCPtr, this, value);
  }

  public double getM_H_margin() {
    return AlignmentAllJNI.SurveyImfo_m_H_margin_get(swigCPtr, this);
  }

  public void setM_V_margin(double value) {
    AlignmentAllJNI.SurveyImfo_m_V_margin_set(swigCPtr, this, value);
  }

  public double getM_V_margin() {
    return AlignmentAllJNI.SurveyImfo_m_V_margin_get(swigCPtr, this);
  }

  public void setM_H_Chord_Sine(double value) {
    AlignmentAllJNI.SurveyImfo_m_H_Chord_Sine_set(swigCPtr, this, value);
  }

  public double getM_H_Chord_Sine() {
    return AlignmentAllJNI.SurveyImfo_m_H_Chord_Sine_get(swigCPtr, this);
  }

  public void setM_V_Chord_Sine(double value) {
    AlignmentAllJNI.SurveyImfo_m_V_Chord_Sine_set(swigCPtr, this, value);
  }

  public double getM_V_Chord_Sine() {
    return AlignmentAllJNI.SurveyImfo_m_V_Chord_Sine_get(swigCPtr, this);
  }

  public void setM_Left_Gauge(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_Left_Gauge_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Left_Gauge() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_Left_Gauge_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_Right_Gauge(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_Right_Gauge_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Right_Gauge() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_Right_Gauge_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_Right_Margin(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_Right_Margin_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Right_Margin() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_Right_Margin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_Left_Margin(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_Left_Margin_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Left_Margin() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_Left_Margin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_gauge(double value) {
    AlignmentAllJNI.SurveyImfo_m_gauge_set(swigCPtr, this, value);
  }

  public double getM_gauge() {
    return AlignmentAllJNI.SurveyImfo_m_gauge_get(swigCPtr, this);
  }

  public void setM_level(double value) {
    AlignmentAllJNI.SurveyImfo_m_level_set(swigCPtr, this, value);
  }

  public double getM_level() {
    return AlignmentAllJNI.SurveyImfo_m_level_get(swigCPtr, this);
  }

  public void setM_LineProjectPt(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_LineProjectPt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_LineProjectPt() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_LineProjectPt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_LineProjectVec(AL_Vector3d value) {
    AlignmentAllJNI.SurveyImfo_m_LineProjectVec_set(swigCPtr, this, AL_Vector3d.getCPtr(value), value);
  }

  public AL_Vector3d getM_LineProjectVec() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_LineProjectVec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Vector3d(cPtr, false);
  }

  public void setM_V_Height_Design(double value) {
    AlignmentAllJNI.SurveyImfo_m_V_Height_Design_set(swigCPtr, this, value);
  }

  public double getM_V_Height_Design() {
    return AlignmentAllJNI.SurveyImfo_m_V_Height_Design_get(swigCPtr, this);
  }

  public void setM_centerPoint(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_centerPoint_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_centerPoint() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_centerPoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_V_centerPoint(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_V_centerPoint_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_V_centerPoint() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_V_centerPoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_Overhead_Origin(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_Overhead_Origin_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Overhead_Origin() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_Overhead_Origin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_Overhead_Limit(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_Overhead_Limit_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Overhead_Limit() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_Overhead_Limit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_Overhead_Opt(AL_Point3d value) {
    AlignmentAllJNI.SurveyImfo_m_Overhead_Opt_set(swigCPtr, this, AL_Point3d.getCPtr(value), value);
  }

  public AL_Point3d getM_Overhead_Opt() {
    long cPtr = AlignmentAllJNI.SurveyImfo_m_Overhead_Opt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AL_Point3d(cPtr, false);
  }

  public void setM_isRemoved(boolean value) {
    AlignmentAllJNI.SurveyImfo_m_isRemoved_set(swigCPtr, this, value);
  }

  public boolean getM_isRemoved() {
    return AlignmentAllJNI.SurveyImfo_m_isRemoved_get(swigCPtr, this);
  }

}
