/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class TQICal {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TQICal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TQICal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TQICal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_TQICal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TQICal() {
    this(AlignmentAllJNI.new_TQICal__SWIG_0(), true);
  }

  public TQICal(TQIValueVector vals, ChainArr chains) {
    this(AlignmentAllJNI.new_TQICal__SWIG_1(TQIValueVector.getCPtr(vals), vals, ChainArr.getCPtr(chains), chains), true);
  }

  public static void setGMargin(double value) {
    AlignmentAllJNI.TQICal_gMargin_set(value);
  }

  public static double getGMargin() {
    return AlignmentAllJNI.TQICal_gMargin_get();
  }

  public static void setGCharge(double value) {
    AlignmentAllJNI.TQICal_gCharge_set(value);
  }

  public static double getGCharge() {
    return AlignmentAllJNI.TQICal_gCharge_get();
  }

  public boolean GetTQIVal(TQIValueVector resultVals, DoubleDoublePairVector splitRanges, double stMileage, int nStIndex, double edMileage, int nEdIndex) {
    return AlignmentAllJNI.TQICal_GetTQIVal(swigCPtr, this, TQIValueVector.getCPtr(resultVals), resultVals, DoubleDoublePairVector.getCPtr(splitRanges), splitRanges, stMileage, nStIndex, edMileage, nEdIndex);
  }

  public void CalRealMileage() {
    AlignmentAllJNI.TQICal_CalRealMileage(swigCPtr, this);
  }

  public void SetTQIVal(TQIValueVector vals) {
    AlignmentAllJNI.TQICal_SetTQIVal(swigCPtr, this, TQIValueVector.getCPtr(vals), vals);
  }

  public boolean CalPit(int nMargin) {
    return AlignmentAllJNI.TQICal_CalPit__SWIG_0(swigCPtr, this, nMargin);
  }

  public boolean CalPit() {
    return AlignmentAllJNI.TQICal_CalPit__SWIG_1(swigCPtr, this);
  }

  public ChainArr GetChains() {
    return new ChainArr(AlignmentAllJNI.TQICal_GetChains(swigCPtr, this), true);
  }

  public TQIValueVector GetOriginDatas() {
    return new TQIValueVector(AlignmentAllJNI.TQICal_GetOriginDatas(swigCPtr, this), true);
  }

  public static boolean InsertTQIValue(TQIValue resultVal, TQIValue tqiVal1, TQIValue tqiVal2, double rm) {
    return AlignmentAllJNI.TQICal_InsertTQIValue(TQIValue.getCPtr(resultVal), resultVal, TQIValue.getCPtr(tqiVal1), tqiVal1, TQIValue.getCPtr(tqiVal2), tqiVal2, rm);
  }

  public boolean GetChanIndexByValue(IntArr nIndexs, double dDm) {
    return AlignmentAllJNI.TQICal_GetChanIndexByValue(swigCPtr, this, IntArr.getCPtr(nIndexs), nIndexs, dDm);
  }

}
