/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class TQIValueVector extends java.util.AbstractList<TQIValue> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TQIValueVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TQIValueVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TQIValueVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_TQIValueVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TQIValueVector(TQIValue[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TQIValue element : initialElements) {
      add(element);
    }
  }

  public TQIValueVector(Iterable<TQIValue> initialElements) {
    this();
    for (TQIValue element : initialElements) {
      add(element);
    }
  }

  public TQIValue get(int index) {
    return doGet(index);
  }

  public TQIValue set(int index, TQIValue e) {
    return doSet(index, e);
  }

  public boolean add(TQIValue e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TQIValue e) {
    modCount++;
    doAdd(index, e);
  }

  public TQIValue remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TQIValueVector() {
    this(AlignmentAllJNI.new_TQIValueVector__SWIG_0(), true);
  }

  public TQIValueVector(TQIValueVector other) {
    this(AlignmentAllJNI.new_TQIValueVector__SWIG_1(TQIValueVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return AlignmentAllJNI.TQIValueVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AlignmentAllJNI.TQIValueVector_clear(swigCPtr, this);
  }

  public TQIValueVector(int count, TQIValue value) {
    this(AlignmentAllJNI.new_TQIValueVector__SWIG_2(count, TQIValue.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return AlignmentAllJNI.TQIValueVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    AlignmentAllJNI.TQIValueVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return AlignmentAllJNI.TQIValueVector_doSize(swigCPtr, this);
  }

  private void doAdd(TQIValue x) {
    AlignmentAllJNI.TQIValueVector_doAdd__SWIG_0(swigCPtr, this, TQIValue.getCPtr(x), x);
  }

  private void doAdd(int index, TQIValue x) {
    AlignmentAllJNI.TQIValueVector_doAdd__SWIG_1(swigCPtr, this, index, TQIValue.getCPtr(x), x);
  }

  private TQIValue doRemove(int index) {
    return new TQIValue(AlignmentAllJNI.TQIValueVector_doRemove(swigCPtr, this, index), true);
  }

  private TQIValue doGet(int index) {
    return new TQIValue(AlignmentAllJNI.TQIValueVector_doGet(swigCPtr, this, index), false);
  }

  private TQIValue doSet(int index, TQIValue val) {
    return new TQIValue(AlignmentAllJNI.TQIValueVector_doSet(swigCPtr, this, index, TQIValue.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AlignmentAllJNI.TQIValueVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
