/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class TQIValue {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TQIValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TQIValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TQIValue obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_TQIValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TQIValue() {
    this(AlignmentAllJNI.new_TQIValue__SWIG_0(), true);
  }

  public TQIValue(double dMileage, int nIndex, double dHori_L, double dHori_R, double dVert_L, double dVert_R, double dGauge, double dMargin, double dPit) {
    this(AlignmentAllJNI.new_TQIValue__SWIG_1(dMileage, nIndex, dHori_L, dHori_R, dVert_L, dVert_R, dGauge, dMargin, dPit), true);
  }

  public double CalTQI() {
    return AlignmentAllJNI.TQIValue_CalTQI(swigCPtr, this);
  }

  public void setM_mileage(double value) {
    AlignmentAllJNI.TQIValue_m_mileage_set(swigCPtr, this, value);
  }

  public double getM_mileage() {
    return AlignmentAllJNI.TQIValue_m_mileage_get(swigCPtr, this);
  }

  public void setM_nChainType(int value) {
    AlignmentAllJNI.TQIValue_m_nChainType_set(swigCPtr, this, value);
  }

  public int getM_nChainType() {
    return AlignmentAllJNI.TQIValue_m_nChainType_get(swigCPtr, this);
  }

  public void setM_mileage_origin(double value) {
    AlignmentAllJNI.TQIValue_m_mileage_origin_set(swigCPtr, this, value);
  }

  public double getM_mileage_origin() {
    return AlignmentAllJNI.TQIValue_m_mileage_origin_get(swigCPtr, this);
  }

}
