/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package AlignmentCore;

public class UndoGuard {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UndoGuard(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UndoGuard obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UndoGuard obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AlignmentAllJNI.delete_UndoGuard(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UndoGuard(AlignmentFittingUndoManager manager, String description) {
    this(AlignmentAllJNI.new_UndoGuard(AlignmentFittingUndoManager.getCPtr(manager), manager, description), true);
  }

  public void Commit() {
    AlignmentAllJNI.UndoGuard_Commit(swigCPtr, this);
  }

}
